### ISSUE TITLE
Phalcon\Loader::autoLoad wall time

### ISSUE THREAD

**Issue by dcboy** [phalcon/cphalcon#10472]
![qq20150605-1 2x](https://cloud.githubusercontent.com/assets/3503568/7997525/f87a0c42-0b60-11e5-8812-8656905df87a.png)

when i use ab -c 200 -n 3000 to benchmark test and use xhprof mt_rand(1, 100) == 50 to save_run
and detect the elapsed more then 1s

**Comment by andresgutierrez** [comment]
It means that many files are being autoloaded so that method has most of the calls and most of the time is spent loading files. Also loading files involves reading from the filesystem which is an expensive operation. Do you already have opcache installed?

**Comment by sergeyklay** [comment]
@dcboy Can you provide your test for my little research?

**Comment by dugwood** [comment]
@sergeyklay @andresgutierrez just hit the same issue (Phalcon 3.3.2), but in another way.

After reading the code again, it seems that @dcboy is using the `registerFiles` instead of `registerClasses`. Seeing https://github.com/phalcon/cphalcon/blob/master/phalcon/loader.zep#L272 implies that for `registerFiles`, Phalcon will test the file even if it's not loaded. With `registerClasses` Phalcon will check the files only if called (`autoLoad`). So @dcboy you should change the way you load classes in `Phalcon\Loader`.

Although I have opcache installed, each loaded file is a 1ms delay... so 32 files ~ 36ms. 17% of the whole time spent in my script was in the `is_file()` function.

As a default, opcache doesn't cache `is_file`: http://php.net/manual/fr/opcache.configuration.php#ini.opcache.enable-file-override so your suggestion seems wrong. And asking to enable this option doesn't seem to be a good idea either (many users don't have access to opcache configuration). But I'll definitely look into it for my own setup.

I don't have any idea on how to ignore the `is_file`: so far I always used a unique path for loading classes, so I always did a `return require $filename`, which would crash the script if the class isn't found (so far so good). But as you must test multiple directories, it's not possible to bypass the `is_file` function.

@dcboy you can use tideways along with xhprof (old) interface.

**Comment by sergeyklay** [comment]
@dugwood Hm... Did you use absolute paths? Depending on your `include_path` setting PHP checks all these dirs if you check relative file paths. Just for test you might unset `include_path` temporarily before checking the existence. Anyway file access I/O is always slow. A hard disk access is slower than calculating something in the processor, normally.

Could you please try to test this:

```zep
if false !== stream_resolve_include_path(filePath) { 
  // do stuff 
}
```

**Comment by dugwood** [comment]
@sergeyklay I used absolute paths with some level down:
`'MyProject\Frontend\Controllers' => __DIR__.'/../frontend/controllers/',`
Is this okay?

Although I don't compile Phalcon anymore (yeah packagecloud!), I think the test is the very same in PHP.

So, for a list of 119 existing files, with an absolute path including a `/../`:
 - is_file: about 35-50ms
 - stream_resolve_include_path: about 80-100ms, then after a few hits: about 1ms (if I test on non existing files, I keep the 80-100ms range all the time, as expected)

Changes in opcache:
 - enable_file_override=1: no changes at all
 - validate_timestamps=0: no changes at all

Really strange :-) So `stream_resolvê_include_path` is the way to go, isn't it? But it seems that PHP caches the output, hence on a deletion it would go wrong: http://php.net/manual/fr/function.stream-resolve-include-path.php#111790

Perhaps we could use an APCu adapter, so that we limit the hit on the filesystem for nothing, don't you think? Isn't composer doing something like this?

**Comment by dugwood** [comment]
@sergeyklay my option is to create my own loader that doesn't fire a `is_file`. I know that the namespace is very specific, hence there's no way another path than the one defined for Phalcon would hold the file. So just a big fatal error if there's no class in the directory defined for this namespace.

`stream_resolve_include_path` would work most of the time, if no one remove the file at all. But we can't expect that to be true.

So I don't know what to do in the end... my choices won't work for most of the people. Maybe we can add a parameter (reminds me the no cache parameter I proposed a while ago: #3183). Something like `fileCheck: default=is_file|stream=stream_resolve_include_path|none=no test`.

**Comment by Jurigag** [comment]
Well according to PHP result of is_file is cached. Can you check code in php if it gives you also big results? Maybe zephir is_file is not caching results?

**Comment by dugwood** [comment]
@Jurigag in fact I was only testing a PHP code, not a compilation in Zephir. I don't recall `is_file` to be cached, or perhaps if you call multiple times `is_file` for the same file in the same script.

Perhaps I'll remove the Phalcon\Loader to create my own one, because I don't think it will fit everyone's needs (especially if you want to depend on the filesystem).

**Comment by Jurigag** [comment]
Yea, i guess it's about the same file, maybe if called in php-fpm process it would be cached. In cli most likely not. How you were testing it?

**Comment by sergeyklay** [comment]
@dugwood 

> Something like fileCheck: default=is_file|stream=stream_resolve_include_path|none=no test.

Could you create a new issue with this NFR and ping me?

**Comment by dugwood** [comment]
@sergeyklay sorry I've read PR instead of NFR, so the NFR is added: #13360. I've pasted some relevant test code.
