### ISSUE TITLE
Is not 2.0.4 intended to be backward compatible?

### ISSUE THREAD

**Issue by salarmehr** [phalcon/cphalcon#10636]
Upgrading from 2.0.3 to 2.0.4 I had to change ` validate(Phalcon\Mvc\ModelInterface $model)` to `validate Phalcon\Mvc\EntityInterface $model` in all models. Is it intended behavior? Is there any upgrade guild-line? I thought minor versions are totally backward compatible.

**Comment by dschissler** [comment]
Adding typed parameters to methods has been a major theme of the `2.*` releases.  Hopefully this all slows down with `2.1.*`.

**Comment by stefanchiriac** [comment]
well, phalcon team doesn't seems to care so much about backwards compatibility. Since version 2 started, each update breaks compatibility with something.

Every feature that breaks compatibility even a bit, should have been put on 2.1.x branch and on 2.0.x to add only features that keeps the backward compatibility and fixes.

**Comment by dschissler** [comment]
Phalcon doesn't use [semver](http://semver.org/).  It wouldn't be a bad thing in my opinion if the Phalcon team wasn't so allergic to increasing the minor version.  Push forward with some new features, bump the minor version, kill a few old bugs then bump the patch version, and repeat.

**Comment by andresgutierrez** [comment]
Phalcon 2.0.0 to 2.0.3 broke compatibility with Phalcon 1.3.x, and this change in Phalcon 2.0.4 is fixing that
