### ISSUE TITLE
[2.0.4] getSessionToken() returns different values on each page refresh

### ISSUE THREAD

**Issue by chipco** [phalcon/cphalcon#10637]
For testing use vokuro login form https://github.com/phalcon/vokuro/blob/master/app/forms/SignUpForm.php

CSRF validation fails since the value of the token changes.

**Comment by stefanchiriac** [comment]
well, seems like if you fail the login form, 2nd time the csrf keys are out of sync. To keep it working you either have to refresh the page, or do a hack of some sort. This problem is quite old so I added this in LoginForm until gets fixed.

    /**
     * @var null $lastCsrfValue
     */
    private $lastCsrfValue = null;

    /**
     * Get last Csrf value
     */
    public function getCsrf()
    {
        return ($this->lastCsrfValue !== null) ? $this->lastCsrfValue : $this->lastCsrfValue = $this->security->getSessionToken();
    }

**Comment by sszdh** [comment]
Search the forum, u can find usefull topics there...

**Comment by dschissler** [comment]
@chipco I based my [Webird](https://github.com/perchlayer/webird) project on Vokuro and so csrf code suddenly stopped working as well with 2.0.4 but I was able to fix it rather easily.  I'm not longer using the form to validate the csrf and I'm doing that in the controller.  I think that this new way is better because the serious security code is in the controller.

* [SigninForm](https://github.com/perchlayer/webird/blob/master/app/phalcon/modules/web/forms/SigninForm.php) - I deleted the csrf code.
* [SessionController.php line 80](https://github.com/perchlayer/webird/blob/master/app/phalcon/modules/web/controllers/SessionController.php#L80)
* [signin.volt](https://github.com/perchlayer/webird/blob/master/app/phalcon/modules/web/views/session/signin.volt).

Notice in `signin.volt` I've placed this at the top: `<!-- security token: {{security.getToken()}} -->`.  That sets up a new token and then below I use `security.getSessionToken()` and `security.getSessionTokenKey()` to access it as many times as needed (for Oauth plus normal signin.

**Comment by dschissler** [comment]
Damn.  I just realized that there is not a `Session::getSessionTokenKey()` method and a recent quick fix of mine is broken.  I checked the Phalcon 2 source and both `Security::getToken()` and `Security::getTokenKey` both change their respective session variable.  The problem is that there is no way to use the token key twice in the view without passing the variable in from the controller.

While I currently don't need to use the token key twice in the form its simply unnecessarily confusing.

I would much prefer an method like `<!-- {{ session.generateAllNewSessionTokenStuff() }} -->` at the top of my Volt view template and then to be able to have all of the getters not destroy the session tokens.  Two sets of getters (one destructive and one not) is just strange for me.

At least a `Security::getSessionTokenKey` could be added.  The ease of use and simplicity falls apart when putting additional signin methods (like OAuth) in the signin screen.

I'd like to see something more like this:

```
* Security::generateAllNewEverythingSessionTokenStuff()
* Security::getNewSessionTokeyKey()
* Security::getNewSessionToken()
* Security::getSessionTokenKey()
* Security::getSessionKey()
```

**Comment by akudryav** [comment]
I use the same action in IndexController in Vokuro and Invo application:
```
public function testAction()
    {
        $this->view->disable();
        echo $this->security->getSessionToken();
    }
```
So in Invo there is no changes in token on refresh, but in Vokuro it changes every time you reload page WHY?!!!

**Comment by akudryav** [comment]
Seems like action Index in IndexController (where I use getToken function) executed when you open any url behind the scene)

**Comment by akudryav** [comment]
I've got the answer here: https://forum.phalconphp.com/discussion/922/csrf-protection-not-working
The problem was in favicon.ico, this is the Zend bug!

**Comment by chipco** [comment]
I appreciate the time you took to find workarounds and possible fixes. But to me this looks like a phalcon bug and nothing more.

A php session should last as long as the user's browser is opened, no matter what pages, favicons etc. the browser loads. Since we are in the same session, the session token should be identical no matter what page I load or how many times I reload the page.

I can only speculate that either phalcon resets the entire php session or it resets the session token.

Note that this problem appeared after upgrading from phalcon 2.0.3 to 2.0.4 Reverting to 2.0.3 makes the problem go away.

**Comment by chipco** [comment]
After some further testing, it looks like the csrf is good and it's the Identical validator that fails.

**Comment by chipco** [comment]
It seems that the Identical validator no longer works with the '**value**' key, instead we must use '**accepted**'.
```
$csrf->addValidator(new Identical(array(
	'accepted' => $this->security->getSessionToken(),
	'message' => 'CSRF validation failed'
)));
```

**Comment by akudryav** [comment]
looks like one more undocumented phalcon feature)

**Comment by zhilevan** [comment]
still, has different values on each page refresh !!!!

**Comment by sergeyklay** [comment]
@zhilevan Could you please open a ned issue with script to reproduce
