### ISSUE TITLE
Please obey semantic versioning, and stop merge BC

### ISSUE THREAD

**Issue by ovr** [phalcon/cphalcon#10759]
As I known Phalcon is using Semantic Versioning

http://semver.org/

```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

Current Minor - `2.0.x`

Examples:
https://github.com/phalcon/cphalcon/commit/b8244b94f7b1742103fdf31fbeecdc7d5550b2f4
BC breake, you cannot modify interface in PATCH release, it's need another MINOR - 2.1.x

Another example
https://github.com/phalcon/cphalcon/blob/2.0.x/phalcon/mvc/model/validatorinterface.zep
```zep
public function validate(EntityInterface record){}
insteadof
public function validate(ModelInterface record) {}
```
BC breake, you cannot modify interface in PATCH release, it's need another MINOR - 2.1.x

I will show you an example of current chaos
I can't bind my dependency like this ~2.0.4 via you can break it!

For example
If some of Linux's contributors will do this, you will get unstable system or if you bind
your dependency like 2.0.1 by static way, you will hold this for all system and can't install another package with this package as dependency in another version

Steps
- [ ] Create 2.1.x branch

**Comment by sergeyklay** [comment]
> Create 2.1.x branch

:+1:

**Comment by KorsaR-ZN** [comment]
I propose to exclude `fromInput` method from the interface, where it is not needed!

**Comment by ovr** [comment]
@KorsaR-ZN 
Yeap, but don't forget you can do this in patch release
Patch release We are using to stable our system... for upcoming releases with security fixes or bug fixes

**Comment by KorsaR-ZN** [comment]
> Create 2.1.x branch
:+1:

**Comment by KorsaR-ZN** [comment]
@ovr If we remove the method `fromInput` from the interface, he will not break semver
Who supports the exclusion of this method?

**Comment by ovr** [comment]
@KorsaR-ZN 
You will break this code

```php
interface IntefaceA {
    public function test1();
}

class A implements IntefaceA
{
public function test1() {
return true;
}
}


class ServiceA {
     public function testInterfaceA(IntefaceA $a)
     {
           $a->test1();
     }
}

$tmp = new A();
$tmp->test1();
```

And bind version like

```
library:2.0.*

but in 2.0.7 you are intersted to remove it from interface
and someone don't known that it's needed to implement test1
```

**Comment by KorsaR-ZN** [comment]
@ovr Here you are right, I do not argue.
I just put the voice of the exclusion of this method from the interface, not because of the implementation, but only from the interface.

**Comment by phalcon** [comment]
Who tell you that we are following semantic versioning?

**Comment by ovr** [comment]
@phalcon 
You version system
2.0.x

**Comment by andresgutierrez** [comment]
So, employing a universally adopted scheme for versions make us follow this page? http://semver.org/

**Comment by dschissler** [comment]
It seems to me that the issue is wanting to improve Phalcon but being stuck in this idea 2.0.x will support PHP 5.3 and then later versions will be deprecating/discontinuing PHP 5.3 and so breaking changes are forced into the 2.0.x versions.  I propose that PHP 5.3 can be deprecated at any moment and it won't affect things and deprecation just means that it is marked for later removal - and not even actively removed yet.  Hell, so it could even be deprecated now while being still supported and many projects run deprecated features for YEARS prior to getting around to removing the supporting code.  Its actually better to deprecate sooner since it gives more people time to get the message about it.

Phalcon is just coming out of a major overhaul (obviously) and so I think that having the 2.0.x tree be slightly unstable compatibility wise is understandable but I think that Phalcon really should get with the semver scene now that those first 100 bugs have been ironed out. 

I propose that 2.0.x continues just as it is for however long that is needed got get things where they need to be and then starting with 2.1 Phalcon begins follows semver.  So then its no great sin to simply bump the minor.  Then the project doesn't need to outright declare when PHP 5.3 is dropped as deprecating it sends the message that its time to move on.  If the period of time for ACTUALLY dropping PHP 5.3 support is too short after deprecation then that probably is a failure of the 2.x strategy to begin with.

**Comment by ovr** [comment]
@andresgutierrez 
Because it's best practice and needed for dependency project(s)
I can't bind version for next paches
Are you intersted to economize branches?

@dschissler 
It's possible and easy to create another minnor branch and do changes in it

**Comment by ovr** [comment]
ping @andresgutierrez

**Comment by andresgutierrez** [comment]
Branch 2.1.x was created
