### ISSUE TITLE
[NFR] Log file size limit.

### ISSUE THREAD

**Issue by liverbool** [phalcon/cphalcon#1089]
Request for when the log file size reaches the specified size limit, the contents are archived in a new name.

ref: [https://logging.apache.org/log4php/docs/appenders/rolling-file.html](https://logging.apache.org/log4php/docs/appenders/rolling-file.html)
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
