### ISSUE TITLE
[NFR] \Phalcon\Mvc\Model\Resultset\Complex :: toArray

### ISSUE THREAD

**Issue by galki** [phalcon/cphalcon#10922]
I'm guessing this would be a simple method so can we get this convenience method made?

``` php
foreach ($results as $i => $rows) {
    foreach ($rows as $modelName => $row) {
        $array[$i][$modelName] = $row->toArray();
    }
}
```

perhaps with a bonus flag for a flattened result:

``` php
foreach ($results as $rows) {
    $tempArray = [];
    foreach ($rows as $modelName => $row) {
        $tempArray[$modelName] = $row->toArray();
    }
    $array[] = call_user_func_array('array_merge', $tempArray);
}
```

I think if most people end up writing the above, this should definitely be made.

**Comment by dschissler** [comment]
Perhaps you should try getting into Zephir as this is a perfect feature to start with.  I recently fixed a complicated AST related bug in Phalcon (should be out in 2.0.8) and the total time was about 2.5 days but I think that you could have this feature implemented with a pull request in less than a day (considering its the first try with the new tools).  I recommend cloning from the Zephir master tree so that you can get a caching on the builds as this will reduce the compile times to 1/3 or 1/2 of the total time (and that really is the largest time sync of the process by far).

**Comment by galki** [comment]
Thanks, that sounds really interesting. I'll take a look.
