### ISSUE TITLE
duplicate view file

### ISSUE THREAD

**Issue by DracotMolver** [phalcon/cphalcon#11008]
I'm starting using the latest version of Phalcon and when I refresh the site I'm having a duplicate view. What I'm doing is this:
IndexControoler
```php
public function indexAction(){
   $this->assets
          ->collection('header')
          ->addJs('js/react.min.js', true)
	  ->addJs('js/JSXTransformer.js', true);
}
```
Then in mi services.php file I have this in the view component
...
```php
$view->registerEngines([
    '.phtml' => 'Phalcon\Mvc\View\Engine\Volt'	
]);
```
and in mi view folder 
* view
 * index
   * index.phtml
    * index.phtml.php (Duplicate file which is generated by Phalcon)

I just want to know if this is a bug, this is right or I am doing something wrong.

**Comment by shoother** [comment]
how did you produce the duplicate file? I can't replicate your bug.

**Comment by daison12006013** [comment]
It seems you didn't imported your ``$view->setViewsDir('path here')`` something like this https://github.com/phalconslayer/slayer/blob/dev/components/Providers/Slayer/View.php#L20

**Comment by SidRoberts** [comment]
I think that's the file that Phalcon "compiles" into pure PHP (.phtml is Volt; .phtml.php is pure PHP).

Here's how you set a custom compile path:

```php
$di->set(
    'volt',
    function (\Phalcon\Mvc\ViewInterface $view, \Phalcon\DiInterface $di) {
        $volt = new \Phalcon\Mvc\View\Engine\Volt($view, $di);

        // ...

        $volt->setOptions(
            [
                "compiledPath"      => "cache/views/",
                "compiledExtension" => ".compiled",
                "compiledSeparator" => "%%"
            ]
        );

        // ...

        return $volt;
    }
);
```

**Comment by dracot25** [comment]
well. What I did was follow the instructions of the page: https://docs.phalconphp.com/en/latest/reference/volt.html

and I have all configured like said in the INVO tutorial. The only thing I changed was the path of the view because as it appears in the doc, doesn't work for me (I'm working using xampp and the patth is localhost/phalcontest/...)

```php
[application]
controllersDir = app/controllers/
modelsDir      = app/models/
viewsDir       = app/views/  /* to make view works I had to change it for this .../app/views/ */
libraryDir     = app/library/
```

so, then I just configured the view in the service.php file like this:

```php
 $di->set('view', function () {
        $view = new View();
        $view->setViewsDir($config->application->viewsDir);
        $view->registerEngines([
                '.phtml' => 'Phalcon\Mvc\View\Engine\Volt'   
         ]);
        return $view;
    });;
```
If I comment the $view->registerEngines, It works right. but if I don't do that, I've got a duplicate file (phtml.php) with the same content as the original but instead using volt sintax it is pure php (ofcourse xdxd).
I will do what you say me above and I will tell you later what is going on. Thanks guys.
