### ISSUE TITLE
Phalcon afterDelete() is not executing

### ISSUE THREAD

**Issue by JellyM** [phalcon/cphalcon#11069]
When I add ```afterDelete()``` method to my model (version 2.0.7), it is not executed, however ```afterUpdate()``` is executed.

**Comment by SidRoberts** [comment]
Could you post your code?

**Comment by JellyM** [comment]
@SidRoberts 

````<?php
namespace App\Models;

use Phalcon\DI\FactoryDefault;
use Phalcon\Mvc\Model\Behavior\SoftDelete;

class Test extends ModelBase
{
    public $id;
    
    public $source;
    
    public $target;
    
    public $deleted;
    
    const DELETED = 1;
    
    const NOT_DELETED = 0;
    
    public function getSource()
    {
        return "test";
    }
    
    public function initialize()
    {
        $this->setSource("test");

        // Soft delete
        $this->addBehavior(new softDelete([
            "field" => "deleted",
            "value" => self::DELETED
        ]));
    }
    
    public function afterDelete()
    {
        $records = Members::findFirstById($source);
        $records->delete();
        die("Executed");
    }
}````

There is also another problem with this. If I put code in ```afterDelete()``` in ```beforeDelete()``` then I get 404. If I remove ```$records->delete()``` everything works just fine!

So I thought maybe the problem is in ```Members``` model and tested it in a controller with the same code (except I passed an id instead of variable) and it works as expected.

Does this mean somehow I can't use Model CRUD within another model?

**Comment by dschissler** [comment]
The default SoftDelete doesn't delete anything, it merely updates the field value to the deleted value and then it skips the delete operation.  I've ported the Phalcon 2 Zephir SoftDelete back to PHP and I've extended it and given it a Trait to help setup it up and to give it additional functionality.  One user said that it didn't work for them and its been a long time since I've run the code but you can check it out below:

SoftDelete:

* [Behavior](https://github.com/perchlayer/webird/blob/master/app/phalcon/common/library/Mvc/Model/Behavior/SoftDelete.php)
* [Trait](https://github.com/perchlayer/webird/blob/master/app/phalcon/common/library/Mvc/Model/Traits/SoftDeleteModelTrait.php)
* [How to activate it with the added Trait method](https://github.com/perchlayer/webird/blob/master/app/phalcon/common/models/Users.php#L154)
