### ISSUE TITLE
Change mcrypt on openssl

### ISSUE THREAD

**Issue by Studentsov** [phalcon/cphalcon#11486]
Due to the obsolescence of mcrypt (absence of updates of nearly 10 years) and its loss on openssl speed, I offer an exception it from dependences of a framework and its changeover by openssl. It is possible to mention as arguments that it want to exclude from PHP kernel long ago (https://wiki.php.net/rfc/removal_of_dead_sapis_and_exts, https://wiki.php.net/rfc/mcrypt-viking-funeral), and also the fact that Phalcon already depends on openssl.

**Comment by sergeyklay** [comment]
:+1:

**Comment by Studentsov** [comment]
It is necessary to break backward compatibility as these extensions aren't interchanged. It would be interesting to listen to judgements of the people who are responsible for development of a framework.

**Comment by sergeyklay** [comment]
I agree. 
@andresgutierrez @niden @xboston @carvajaldiazeduar

**Comment by xboston** [comment]
:+1:

**Comment by niden** [comment]
I think that this is a good idea. Yes we will break backwards compatibility but we will break it for a very good reason and that is security. It is the same argument for using an older version of PHP vs a newer one and thus we dropped support for PHP 5.3.

Nothing beats a good design with solid security enhancements in place, but the tools have to match the effort and this move IMHO is more than welcome. We just have to make sure everyone knows about it so that they can adjust their code accordingly.

**Comment by sergeyklay** [comment]
Implemented in 2.1.x branch
