### ISSUE TITLE
findFirst() not work by 2.1 rc on php 7.0.5

### ISSUE THREAD

**Issue by JokeZhang** [phalcon/cphalcon#11641]
Code:
`$model = Brand::findFirst(); `
run message on nginx：
`502 Bad Gateway`

the code is run  success in php 5.6 phalcon 2.0.8；

**Comment by Jurigag** [comment]
Phalcon don't support php 7 yet. This bug was already reported many times.

It's problem with modelsManager. It's caused by zephir create_instance_params. Zephir cant create instance of class if it's provided as string.

For instance and now if you still want to use php7(i really don't recommend it) you need to register in your di service called:
```Phalcon\\Mvc\\Model\\Query``` which will return Query object.
