### ISSUE TITLE
Model Object Stored in Session

### ISSUE THREAD

**Issue by SoccerField24x7** [phalcon/cphalcon#11679]
When storing an object in the session in the following manner:

```
$this->session->set("wall", Area::findFirst("areaid=" . $areaid));
```

it seems to be corrupting (destroying?) the session variable and causing me to log in again due to missing session data.  It's not always right away, but usually within a few seconds.  If I store the `findFirst()` results in a variable, and put $var->toArray() into the session, it doesn't produce the corruption.  I'm wondering if the recursion of the object causes it to overrun the session.

Let me know what additional information I can send you to assist.

**Comment by makerlabs** [comment]
Actually passing the object model to the session does the same thing it calls the serialize() method which returns 
`return serialize($this->toArray());` check in your code that the storing of the object is the problem because I think the problem could be in the unserialize() call maybe some fancy code in your model initialize() method which is called after get the object from the session.

**Comment by SoccerField24x7** [comment]
I don't think I was doing anything fancy:

    {% set wall = session.get("wall") %}

Then went on to use it as an object:

    {{ wall.name }}

Perhaps there's something in the unserialize()?  Or the relationships?  I still think there may be a bug here worth hunting.
