### ISSUE TITLE
Join as relation alias

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#11824]
Well there is some weird behaviour. This code here:

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query.zep#L1525 to line 1546 is supposed to allow joining related models using an relation alias. So if we have for example:

``` php
$this->belongsTo('somefield','SomeNameSpace\SomeClass','id',['alias'=>'SomeClass']);
```

Then we could possibly use:

``` php
->leftJoin('SomeClass')
```

But it doesn't work beacause phalcon is trying to load it as a model beacause of https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/query.zep#L1316

It just looks like someone was starting to develop such an ability - to join related models using just an alias, without fully qualified namespace with class name but forgot about finishing it.

**Comment by lajosbencz** [comment]
Suppose I have 3 tables, **user**, **group** and **user_group**.
The User model has a hasMany relationship to UserGroup with the alias of Group.

In this case ```->leftJoin('Group')``` would be ambigious... Which would take precedence?

**Comment by Jurigag** [comment]
Well, im guessing this is solving this question, beacause yea, this will be a big problem.

**Comment by lajosbencz** [comment]
I don't know, it's not a bad idea... I can see how it would make life easier for lazy people like me.

It just needs to be well thought through, I'd suggest that model names take precedence and then the relation aliases. This way it wouldn't break existing code.

**Comment by Jurigag** [comment]
Well, when I will have time I will look into it. But why ? Maybe we want to name relation alias same as class name and we want to join this alias - and the way you wrote we will have model joined if we have such a model too. Well, I think I will add global variable so it will look first for relation alias, then for model class, but default behaviour will be the one you wrote.

**Comment by lajosbencz** [comment]
Maybe we could use the ```Phalcon\Mvc\Model\Manager::registerNamespaceAlias()``` (or similar) method to assign a prefix for relation aliases.

For eg:
```php
// services
$modelsManager->registerNamespaceAlias('m','MyProject\Models');
$modelsManager->registerRelationAlias('r');

// usage
$di->get('modelsManager')->createBuilder()
    ->addFrom('m:User')
    ->innerJoin('m:Group')
    ->innerJoin('r:Group')
```

Just thinking aloud...

**Comment by Jurigag** [comment]
Well, this is not the bad idea.

**Comment by dschissler** [comment]
@Jurigag Aliases break in many use cases in my experience.  If you can locate some specific code then I can try to get into it over say the next two weeks.  Aliases need a lot of work in edge and unusual cases.

**Comment by Jurigag** [comment]
I think @lajosbencz last post here is nice idea imho. So we could just register relation alias for using in query builder and it will always look for model relations if we use it instead of model aliases. Well it would be nice if you could look into it, well sooner or later i would do it myself, don't know if in two weeks, but this could be nice thing to have, beacause someone people think that they can use aliases just from model relation definition and have problems. It's just something like in doctrine etc, you can in it just join related records directly from model from which you select. In phalcon currently you have to join some model, no matter you already did relations, this can be helpful imho.

**Comment by dschissler** [comment]
Well I don't see myself having time over the next 1-2 months to just start opening Phalcon source files and looking for issues without a starting point but if the scope can be narrowed down then I can put in some time.  I've been thinking for 1-2 years that aliasing in general is the weakest part of Phalcon.  I've made numerous grumblings about aliasing, created issues, etc.  I just haven't been able to have a productive dialog with anyone and so I was unable to make any progress on the matter.  Also I have been unable to target the exact nature of the issues and so I was only really looking at final symptoms.  A lot of that code is pretty heavy and complicated and so I think would require caffeine and 2-3 days of heavy involvement to get into it to isolate the problem code paths or bad architecture.

Also while thinking about this issue consider this bug demonstrated at my [alias_bug](https://github.com/dschissler/alias_bug) repo.

It might all be related and possibly and maybe due to ambiguity the current behaviours are correct for what he could done but its not satisfactory to me how quite Phalcon is about everything.

**Comment by Jurigag** [comment]
But this isn't really an issue. It's NFR.

**Comment by dschissler** [comment]
Ok but for me its fits under and umbrella that when it comes to aliases and joining that either;

1) I don't agree with the implicit behaviour
2) I just can't do something that seems that I ought to be able to
3) There is a bug

To the point that really whenever it comes to joins I go "Oh *!!@#^ lets see if this is possible with Phalcon as it currently is".

**Comment by Jurigag** [comment]
Well actually this is duplicate of https://github.com/phalcon/cphalcon/issues/1111
