### ISSUE TITLE
When finally phalcon will fully support php7?

### ISSUE THREAD

**Issue by googlle** [phalcon/cphalcon#11847]
We've been waiting for. I'm sorry but it's really long

**Comment by Jurigag** [comment]
When 2.1.0 version will be released.

**Comment by googlle** [comment]
I know that

**Comment by stamster** [comment]
@googlle 
What exact feature of PHP7 you're missing with current stack combined with Phalcon?

**Comment by googlle** [comment]
I am not missing any features with current stack. Just want to phalcon support the latest trends

**Comment by googlle** [comment]
Already PHP 7.0 is the default PHP package shipping in Ubuntu LTS 16.04

**Comment by Jurigag** [comment]
I wrote when it will be relasead. Here you have how latest build looks with php 7 : https://travis-ci.org/phalcon/cphalcon/jobs/132122392 as you see in old tests one test fail, in new tests there is some weird seg fault.

**Comment by stamster** [comment]
Ubuntu 16.04 LTS is only a month 'old' distro. 
Take a look at other popular software packages, they still require PHP 5.3 due to ```array()```syntax. 

We all want Phalcon to be well supported, and PHP7 is major milestone in that direction. Working as a software developer / engineer you are probably aware of situation when you have a certain deadline but your project stalled for whatever reason, so you work under pressure. And then you spent your time fixing your dirty code later.

If we all can contribute to Phalcon 2.1.x release than great, if not - have a little patience.

This topic is more for a forum, since it is not an issue of any kind with current stack.

**Comment by googlle** [comment]
I know we have to wait. Thanks for the replies. We will wait

**Comment by Jurigag** [comment]
Just install php5.6 on ubunty 16.04, don't know what's the problem.

**Comment by butamuh4o** [comment]
U know... we always want last and modern technology :) We know time is needed but- we are excited and cant wait :)

Good luck :)

**Comment by sergeyklay** [comment]
For questions like this, you have to use the forum: https://forum.phalconphp.com/
