### ISSUE TITLE
[NFR] mssql extension

### ISSUE THREAD

**Issue by fishjerky** [phalcon/cphalcon#1184]
no one use sqlserver?
i am ready to fly with phalcon... but... my db is sqlserver....
i plan to start a phalcon project in a week....
##

**Comment by ruudboon** [comment]
+1

**Comment by brunomdev** [comment]
+1

**Comment by Jurigag** [comment]
@fishjerky as far as i know you don't need to know C know, i know you posted here 3 years ago so you probably not even using phalcon but you can write this mysql dapter in more common language.

Im guessing that dev team like anders or klay are not using mssql anywhere, so to implement this there definitely must be someone who is using it and working on it and know all things about mssql stuff.

**Comment by niden** [comment]
Microsoft SQL server support is in the same realm as Oracle. We do have some interest but it is very small. As a result, the Oracle adapter has been moved to the Incubator repository, and the same should happen to MSSQL.

Frankly none of us has the means to accurately test these adapters and automated testing will not work since Travis does not support these.

If you or anyone from the community wants to take the lead and work on the adapter by all means. The documentation has examples on how to work with dialects and how to implement the adapter.

**Comment by fishjerky** [comment]
playing deaf...
by the way, @Jurigag!  i'm still using phalcon ....  1.3....

**Comment by Jurigag** [comment]
So maybe it's time to update it ? :D It will be never added to 1.3 since it's dropped like few years ago, you know this right ? Then you can write adapter in zephir. What you mean deaf ? We just don't know mssql, every sql engine has their "things" which can be diffrent from other. Probably no one in dev team know mssql, so why we should start making mssql adapter ? Better someone who already know mssql. And as i wrote - you don't need to know C now to implement it.

**Comment by ruudboon** [comment]
With the new mssql docker container available I would like to add this to the voting list @niden
