### ISSUE TITLE
Volt issue- array keys must be always a string...

### ISSUE THREAD

**Issue by borisdelev** [phalcon/cphalcon#11877]
Hi there :)

Today i find something wrong with volt (or i think is wrong), so let u show u by example (in volt template):

```
{% set weekdays = [1: 'Monday', 2: 'Tuesday'] %}
```

This example will **NOT** work- return error: _"Phalcon\Mvc\View\Exception: Syntax error, unexpected token COLON"_.

I notice smnth- this example will work only when the keys are strings, like: `['1': 'Monday', '2' ...]`. 
Is it normal that behavior?

phpinfo : Phalcon version is : 2.1.0r on PHP 5.6.3 (windows build)

Thank u :) Have a nice week!

**Comment by sergeyklay** [comment]
@butamuh4o Could you please provide script to reproduce (use case)?

**Comment by butamuh4o** [comment]
Hi @sergeyklay and thanks for respond :) 

Well... i am not sure what u mean by that (because that is all script u need, or i dont understand (sorrry)), but... just add in some of your volt templates this line:

```{% set weekdays = [1: 'Monday', 2: 'Tuesday'] %}``` - and u will notice respond of error. But if u modify keys and put it in quotes (like ```{% set weekdays = ['1': 'Monday', '2': 'Tuesday'] %}```) - will work.

Thats all :/ if it is need, i will do more to describe the issue, but for now i cant understand what (sorry about it).

**Comment by butamuh4o** [comment]
:/
