### ISSUE TITLE
Annotation router with namespace not working as expected

### ISSUE THREAD

**Issue by lordjancso** [phalcon/cphalcon#11896]
I would like to use annotation router and here is my code:

```
$di->setShared('router', function () use ($config) {
    $router = new RouterAnnotations(false);
    $router->removeExtraSlashes(true);

    $controllersDir = $config->application->controllersDir;
    $dir = new DirectoryIterator($controllersDir);

    foreach ($dir as $fileInfo) {
        if ($fileInfo->isDot() || false === strpos($fileInfo->getBasename(), 'Controller.php')) {
            continue;
        }

        $controller = $fileInfo->getBasename('Controller.php');
        $router->addResource('App\Controller\\'.$controller); // namespace here?
    }

    $router->setDefaultNamespace('App\Controller');
    $router->notFound(array('controller' => 'error', 'action' => 'route404'));

    return $router;
});
```

As you can see, I have to add namespace before the controller's name in addResource, but I set defaultNamespace.

**Comment by Jurigag** [comment]
`addResource` is method from `Phalcon\Mvc\Router\Annotations`, it's telling annotation router how it should look for controllers to read annotations inside of them, that's why you need full namespace. `setDefaultNamespace` is method from 'Phalcon\Mvc\Router`, it's telling phalcon for which namespace it should look if you don't provide it in `paths` in `@Route` (or other annotation).
