### ISSUE TITLE
Strange animation in DI documentation

### ISSUE THREAD

**Issue by galki** [phalcon/cphalcon#12107]
There is a strange div animation midway in the [DI documentation](https://docs.phalconphp.com/en/latest/reference/di.html)

**Comment by iankitpundir** [comment]
Actually this is what phalcon document want to say.

OBJECT¶
This type expects an object. Due to the fact that object does not need to be resolved as it is already an object, one could say that it is not really a dependency injection, however it is useful if you want to force the returned dependency to always be the same object/value:

```
<?php
use Phalcon\Http\Request;
// Return new Phalcon\Http\Request();
$di->set('request', new Request());
```

This is in div with id "object" somehow,i don't know why but they change object into webkit animation.

**Comment by stamster** [comment]
I also did noticed this odd animation. :) Front-end is just not straight these days :)

**Comment by sergeyklay** [comment]
Thanks fixed in the docs repo
