### ISSUE TITLE
phalcon takes 38 seconds while laravel takes 2.5 seconds

### ISSUE THREAD

**Issue by macnux** [phalcon/cphalcon#12115]
i try to load 41000 records from databaase using laravel 5.2 and phalcon 3 as a test

on phalcon i wrote

```php
$provinces = Provinces::find();

foreach ($provinces as $province) {
    echo $province->name;
}
```

on laravel i wrote

```php
$provinces = Province::all();

foreach ($provinces as $province) {
    echo $province->name;
}
```

phalcon takes 38 seconds to finsih loading while laravel takes 3 seconds only !!

why this big diffrerence ?

* Phalcon version: 3
* PHP Version:5.5
* Operating System:windows 8.1
* Installation type: via package manager
* Server: Apache

**Comment by sergeyklay** [comment]
Could you please provide model?

**Comment by Jurigag** [comment]
Adding alle properties to model should speed it up.

**Comment by macnux** [comment]
yes 
Adding all properties to model should speed it up.
thanks

**Comment by JCMais** [comment]
@macnux what was the result with the modifications?

**Comment by macnux** [comment]
@JCMais  super super speed

**Comment by sergeyklay** [comment]
@macnux Could you please check the `3.0.x` branch now?

**Comment by macnux** [comment]
@sergeyklay it is fast also
but little more time.. just half miute or little more .. but it is ok

**Comment by Jurigag** [comment]
Well @macnux having properties will always speed up your application :)

**Comment by stamster** [comment]
Funny thing is that getting metadata / table structure is not that intensive, and also can be nicely cached on Memcached for instance, since you don't change RDBMS structure every hour or so (in a production at least). 

If this was solved by simply manually defining all properties per each model, then it's great and weird at the same time, since on my own implementation of ORM-like system in Phalcon I never had such issues, and all the properties are defined at runtime, so the model literally does not have a single property defined, even the primary key is being fetched dynamically at runtime.

It is important to  disable stats update on metadata fetching on database server (at least for MySQL/MariaDB with InnoDB engine):

```
innodb_stats_on_metadata = 0

# INFO: this will prevent statistic update when we query information_schema
# Most likely we do not want it anyway. This will not make Innodb to operate without statistics at all as Innodb will still compute statistics for the table first time it opens it.
```

**Comment by Jurigag** [comment]
But this is not about queries or something. This is just how php works:

```php
<?php
class Test
{
    
}

class Test2
{
    public $test;
}

$startTime = microtime(true);
for($i = 0; $i < 10000; $i++)
{
    $varName = "test".$i;
    $$varName = new Test();
    $$varName->test = "test";
}
echo microtime(true)-$startTime.PHP_EOL;
$startTime = microtime(true);
for($i = 0; $i < 10000; $i++)
{
    $varName = "test2".$i;
    $$varName = new Test2();
    $$varName->test = "test";
}
echo microtime(true)-$startTime.PHP_EOL;
```

For me results are:

```
root@vps:/var/www/suzuki# php test.php
0.0072171688079834
0.003277063369751
root@vps:/var/www/suzuki# php test.php
0.0073139667510986
0.0038650035858154
root@vps:/var/www/suzuki# php test.php
0.0054700374603271
0.0034418106079102
root@vps:/var/www/suzuki# php test.php
0.0060641765594482
0.0033531188964844
root@vps:/var/www/suzuki# php test.php
0.0085699558258057
0.0058431625366211
root@vps:/var/www/suzuki# php test.php
0.0081551074981689
0.0055398941040039
root@vps:/var/www/suzuki# php test.php
0.0048890113830566
0.0029938220977783
root@vps:/var/www/suzuki# php test.php
0.008185863494873
0.0055429935455322
root@vps:/var/www/suzuki# php test.php
0.0064408779144287
0.0031049251556396
root@vps:/var/www/suzuki# php test.php
0.0073690414428711
0.005457878112793
root@vps:/var/www/suzuki# php test.php
0.0076348781585693
0.0033731460571289
root@vps:/var/www/suzuki# php test.php
0.0083630084991455
0.0072550773620605
root@vps:/var/www/suzuki# php test.php
0.0088629722595215
0.0054371356964111
root@vps:/var/www/suzuki# php test.php
0.0082969665527344
0.0042498111724854
root@vps:/var/www/suzuki# php test.php
0.0081648826599121
0.0035290718078613
```

**Comment by stamster** [comment]
I'm not sure what can be proven with that.

Models on average have how many properties - 3, 5, 10? 

PHP is certainly not the culprit here IMHO, but as with any other ORM there's an internal overhead.

**Comment by Jurigag** [comment]
If we are using model classes on 10k records:

```
root@vps:/var/www/suzuki# php test.php
0.46982383728027 // no properties
0.20505905151367 // public properties
0.22103595733643 // setters
```

Just for setting 10 properties for 10k records, it's like 0.2 seconds. So if you have big resultsets and many columns then it's great idea to make properties, it's even 2 times faster, as you see. And as i posted above - this is no because ORM OVERHEAD. This is just because of PHP, it just works like this - having properties will be always faster then adding them and set them(which php is doing).

**Comment by stamster** [comment]
This is a real world scenario, generating all the properties at runtime (from DB metadata column definition):

```
Models\WebserviceAudit Object
(
    [_messages:protected] => 
    [_pk] => WebserviceAuditID
    [WebserviceAuditID] => 
    [request_content] => 
    [request_endpoint] => 
    [request_action] => 
    [request_timestamp] => 
    [client_ip] => 
    [client_cookie] => 
    [success] => 
    [http_status] => 
    [result_code] => 
    [log_msg] => 
    [response_content] => 
    [response_timestamp] => 
    [runtime] => 
)
```
Runtime: 0.00055813789367676

Same model with 1000 iterations (since I don't have  a real model/table with 1000 columns/properties): 0.37274098396301
