### ISSUE TITLE
Default InArray/InclusionIn validator needed for Select

### ISSUE THREAD

**Issue by cbichis** [phalcon/cphalcon#12244]
Hello,

Select form elements are missing a default validator InclusionIn applied to options.

The current way to handle selects without applying by default such validator is totally unsecure and allows validation for arbitrary values, basically permitting an attacker to insert any kind of values into model field which is behind of Select.

By example Zend Framework has an InArray validator which is automatically applied to select form elements. Exactly to handle securely this case. Of course, this validator can be disabled if needed (maybe for some Ajax stuff).

**Comment by gguridi** [comment]
Instead of a default validator that can be disabled if needed, Phalcon has a validator that has to be enabled if necessary (and it's disabled by default).

Changing the default behaviour could cause problems to everyone that has already started using their own InclusionIn validators and are accepting anything (even arbitrary code) if not specified.
