### ISSUE TITLE
Container interface (PSR-11)

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#12295]
Phalcon's DI must be fully compatible with [Container interface (PSR-11)](https://www.php-fig.org/psr/psr-11/) for v4.0.0

---

Refs:
- https://github.com/phalcon/cphalcon/pull/13437

**Comment by virgofx** [comment]
How would this be implemented? Create similar container interface or would Phalcon somehow import/reference Psr* packages?

**Comment by sergeyklay** [comment]
I need research best way

**Comment by Jurigag** [comment]
@virgofx the same question is for psr request i guess

**Comment by SidRoberts** [comment]
I personally find this PSR a bit vague (it only has two methods) so I don't think it's absolutely essential that Phalcon should actually implement the interface. I think just following the spec should be enough.

Two things I'd like to recommend:

* Be able to specify dependencies/services in classes instead of anonymous functions (see https://github.com/SidRoberts/container for a working example).

* Inject things via the constructor instead of the accessing the DI/container inside the code (see https://github.com/phalcon/cphalcon/blob/master/phalcon/tag.zep#L205). I think all Phalcon components be completely independent of the DI/container **although this would involve changing how many classes operate**.

**Comment by sergeyklay** [comment]
@dragoonis Just assigned to you.

**Comment by Idrinth** [comment]
would likely be easiest for users if phalcon would just contain the psr-interfaces - having a similar one is not really going to help out much, since their implementations and the interfaces themselves would not be easily exchangeable.

**Comment by dschissler** [comment]
@Idrinth Sergei was doing a lot of work on the PSR extension and I'm sure that this was the idea.

**Comment by niden** [comment]
@Idrinth That is the package we are using for the interfaces (v4)

**Comment by niden** [comment]
Implemented
