### ISSUE TITLE
Acl default access

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12573]
### Expected and Actual Behavior

Currently when using setDefaultAccess in `Phalcon\Acl\Adapter\Memory` and then adding roles it's adding such an access:

```zep
let this->_access[roleName . "!*!*"] = this->_defaultAccess;
```

Since the memory adapter is just stopping when hit any key, it will first hit this key and ignore any other allow rules we will set. I think we can safely remove this line https://github.com/phalcon/cphalcon/blob/master/phalcon/acl/adapter/memory.zep#L210 and let this line https://github.com/phalcon/cphalcon/blob/master/phalcon/acl/adapter/memory.zep#L682 handle when no access was found. Right now things doesn't work as expected i think. Or maybe we should change allow/deny methods to always at add beginning of array, not at the end.

I was changing one time other issue, maybe it created this, i don't know. Will create PR with fix i guess.

> Provide minimal script to reproduce the issue

```php
$acl = new Memory();
$acl->setDefaultAccess(\Phalcon\Acl::DENY);
$acl->addResource('Test', ['one', 'two']);
$acl->addRole('ROLE1');
$acl->allow('ROLE1', 'Test', 'one');
$acl->isAllowed('ROLE1', 'Test', 'one'); // will return false
```
### Details

* Phalcon version: 3.1.x
* PHP Version: 7.0.13
* Operating System: Unbuntu 14.04
* Installation type: Compiling from source
* Zephir version: 0.9.5a-dev-bad1ef6b4d
* Server: cli

**Comment by dschissler** [comment]
@Jurigag While your head is still into this I suggest somehow breaking out that internal ACL logic in such a way (as discussed ~6 months ago) so that individual functions can be heavily tested.  In this case it is denying with a `false` but if some settings were inverted could it be made to erroneously return a `true`?  If so then that is scary and some work should be done to ensure that this is never possible.

**Comment by Jurigag** [comment]
What you mean? Could you provide some example?

**Comment by dschissler** [comment]
Do you remember when we were discussing this code?:
* https://github.com/phalcon/cphalcon/blob/3.1.x/phalcon/acl/adapter/memory.zep#L534
* https://github.com/phalcon/cphalcon/blob/3.1.x/phalcon/acl/adapter/memory.zep#L688

We had an idea about breaking some of that logic up into functions and then using PHP wizardry in a test suite to gain access to those private/protected methods so that they could be broken down into smaller tests.  Maybe that idea is not great but the general goal is to offer more assurances that the critical ACL code is working as it should.

**Comment by Jurigag** [comment]
But i don't really see a point of doing this. Any example of code what you mean? Or you mean add way to get just only this function?

**Comment by dschissler** [comment]
No big deal.

**Comment by Jurigag** [comment]
But i still don't mean what you exactly mean.
