### ISSUE TITLE
Are there any known issues with Phalcon/Mvc/Model/Resultset

### ISSUE THREAD

**Issue by yejune** [phalcon/cphalcon#12627]
https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/resultset.zep

456line:     record save fail
466~468line: rollback, break
481 line: return true

528line:     record delete fail
538~540line: rollback, break
553 line: return true

Is this right?
I think we should have 'return false' instead of 'break'.

**Comment by sergeyklay** [comment]
@yejune Could you please provide a small script to reproduce/show the issue?

**Comment by yejune** [comment]
@sergeyklay Why did you fail and return true?

**Comment by gguridi** [comment]
@yejune the method delete is designed to return always true no matter what happens there, leaving to the developer to check the result through the messages array.

```php
$model->delete();
if ($model->getMessages()) {
  //Something went wrong.
}
```

Maybe would be easier for developers if we just use that boolean to return if something went wrong or not, but this might impact some of the current implementation (even though I think it has sense). So instead of returning always true we could do:

```php
return empty(this->_errorMessages); 
```
