### ISSUE TITLE
Model validate method

### ISSUE THREAD

**Issue by Jurigag** [phalcon/cphalcon#12679]
### Expected and Actual Behavior

Currently validate method in model counts messages returned only from validation, ignoring currently appended to model https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep#L1514 I think this should be changed to count `this->_errorMessages`. Let me know what you think, i think this can be bug fix so it will be in 3.1.0, not sure if this can break some applications, but currently implemented way is wrong imho.

> Provide output if related. Provide coredump if any. Use https://github.com/phalcon/cphalcon/wiki/Generating-a-backtrace as reference

```php
class SomeModel extends Model
{
    public validation()
    {
        $validation = new Validation();
        $validation->add('name', new PresenceOf());
        if(empty($this->price)) {
            $this->appendMessage(new Message("price", "error"));
        }

        return $this->validate($validation);
    }
}

$test = new SomeModel();
$test->name = "xyz";
var_dump($test->create()); // will return true
```

**Comment by tempcke** [comment]
`Phalcon\Mvc\Model::validate(ValidationInterface $validator)` executes a single ValidationInterface and returns if it passed or failed.  So IMHO it should NOT return the count of this->_errorMessages.  However what your looking for is already exposed in `Phalcon\Mvc\Model::validationHasFailed()`

really, due to [CommandQuerySeperation](https://martinfowler.com/bliki/CommandQuerySeparation.html) the `validation` method should probably return void and the results accessed the bool accessed via the exposed `validationHasFailed()` method anyway....

**Comment by Jurigag** [comment]
Well i totally forgot about this method.
