### ISSUE TITLE
Cookie Bug

### ISSUE THREAD

**Issue by addinm** [phalcon/cphalcon#12959]
Hi,

Please check this:

session.cookie_httponly = TRUE:

```php
<?php

$di = new \Phalcon\Di\FactoryDefault();
$di::setDefault($di);

ini_set('session.cookie_httponly', true);
$session = $di->getShared('session');
$cookie = $di->getShared('cookies')->get($session->getName());
echo (new \Phalcon\Debug\Dump())->variable($cookie->getHttpOnly());

```
$cookie->getHttpOnly() = TRUE = OK

NEXT

session.cookie_httponly = FALSE:

```php
<?php

$di = new \Phalcon\Di\FactoryDefault();
$di::setDefault($di);

ini_set('session.cookie_httponly', false);
$session = $di->getShared('session');
$cookie = $di->getShared('cookies')->get($session->getName());
echo (new \Phalcon\Debug\Dump())->variable($cookie->getHttpOnly());

```
**$cookie->getHttpOnly() = TRUE = WRONG**

Same for secure:

session.cookie_secure = TRUE:

```php
<?php

$di = new \Phalcon\Di\FactoryDefault();
$di::setDefault($di);

ini_set('session.cookie_secure', true);
$session = $di->getShared('session');
$cookie = $di->getShared('cookies')->get($session->getName());
echo (new \Phalcon\Debug\Dump())->variable($cookie->getSecure());

```
**$cookie->getSecure() = NULL = WRONG**

NEXT

session.cookie_secure = FALSE:

```php
<?php

$di = new \Phalcon\Di\FactoryDefault();
$di::setDefault($di);

ini_set('session.cookie_secure', false);
$session = $di->getShared('session');
$cookie = $di->getShared('cookies')->get($session->getName());
echo (new \Phalcon\Debug\Dump())->variable($cookie->getSecure());

```
**$cookie->getSecure() = NULL = WRONG**

**Comment by addinm** [comment]
Please check the code https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L303

What is this?
let definition = session->get("_PHCOOKIE_" . this->_name);

**Comment by addinm** [comment]
Same for getExpiration, getDomain, getPath...

**Comment by kornerita** [comment]
Hi,

I believe this is not a bug; if you use i.e.:

```php
<?php

$di = new \Phalcon\Di\FactoryDefault();
$di::setDefault($di);

$session = $di->getShared('session');
$cookie = $di->getShared('cookies')->get($session->getName());
$cookie->setHttpOnly(false);
echo (new \Phalcon\Debug\Dump())->variable($cookie->getHttpOnly());
```
Then you get it false.

For what I have read, the [\Phalcon\Http\Cookie](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L281) uses the [setcookie](http://php.net/manual/en/function.setcookie.php) with its local value, so if you use the framework instead of `ini_set` it would work as expected.

To work as you intend, the [php_ini directives](http://php.net/manual/en/ini.list.php) should be taking into account if the `\Phalcon\Http\Cookie` values for those attributes that are not set (or null):

- Change [here](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L58) to default `NULL`.
- Add lines to load every optional value [before](https://github.com/phalcon/cphalcon/blob/master/phalcon/http/cookie.zep#L278) setcookie to load values from [cookie ini directives](http://php.net/manual/en/session.configuration.php#ini.session.cookie-domain)

Regards,
Federico.

**Comment by kornerita** [comment]
@sergeyklay 

Hi,

Maybe add a NFR to use [php_ini](http://php.net/manual/en/ini.list.php) defaults?

Regards,
Federico.

**Comment by sergeyklay** [comment]
@kornerita Could you please create a NFR?
