### ISSUE TITLE
Variant of flash message

### ISSUE THREAD

**Issue by tztztztz** [phalcon/cphalcon#12963]
New feature request

Simpler (small code compared to current classes) variant of flash message compatible with \Phalcon\Flash\Session, that can be used instead of \Phalcon\Flash\Session:

- automatic retreiving and saving messages in session in __construct and __destruct methods of the flash object
- ability to fetch messages of few message types at once using BITWISE OPERATORS
- messages limit (default 100)
- no default CSS/HTML decoration, just returning array of messages [ [message text, type], [message text, type], ... ]

PHP Code (look for new optimised version at the end of page):

https://forum.phalconphp.com/discussion/13383/variant-of-flash-message

Zephyr code (probably bad):

https://github.com/tztztztz/cphalcon/blob/4.0.x/phalcon/flashsimple.zep

The idea is NOT to remove current classes and replace it by \Phalcon\FlashSimple but, to give users choice which one he want to use.

**Comment by tztztztz** [comment]
If this feture request become accepted, I will make Zephyr code valid.

**Comment by kornerita** [comment]
Hi,

I would really like this feature since I use [https://notifyjs.com](https://notifyjs.com) and I had to extend / implement flash interface and rewrite some of the features, with a plain array response it would be much easier to implement and in a clearer way.

With this array version you could also extend volt to implement a function to show the messages in the way you want.

Regards,
Federico.

**Comment by tztztztz** [comment]
You can use PHP version for now, it works good. Just put it into the Dependency Injector at bootstgrap stage, for example under "FlashSimple' key.

**Comment by kornerita** [comment]
@tztztztz Thanks, I'll use it.

Also it would be better if you can formally implement [FlashInterfase](https://docs.phalconphp.com/en/3.2/api/Phalcon_FlashInterface).

**Comment by tztztztz** [comment]
Hello,

i think implementing Interface Phalcon\FlashInterface and Interface Phalcon\Di\InjectionAwareInterface makes sense.

Im not convinced about Interface Phalcon\Session\AdapterInterface as it's quite complex interface, and this class meant to be simple version of current Flash Message system, an alternative not replacement. 

Still there is plenty of time before ver. 4, and maybe whole concept of Flash Message will change.

**Comment by sergeyklay** [comment]
@tztztztz Could you please submit PR to the Incubator? If this proves successful, we can port it to the Phalcon core. Anyway I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :)

**Comment by tztztztz** [comment]
Do you mean creating pull request here?: https://github.com/phalcon/incubator/pulls

I will do it at later time, first in the next week I'll finish the project of new cache as I mentioned here:

https://github.com/phalcon/cphalcon/issues/12968
