### ISSUE TITLE
Column doesn't belong to any of the selected models (1)

### ISSUE THREAD

**Issue by mbrostami** [phalcon/cphalcon#13006]
### Expected and Actual Behavior
Related to this issues: #1731 , #10934
When I want to use subquery in where conditions and having beside that I got this error: 
```php
Column 'SomethingNotInModels' doesn't belong to any of the selected models (1), when preparing: SELECT "aaa" AS [SomethingNotInModels] FROM [Trumpet\Models\Ad] AS [a] WHERE a.IDCategory IN (SELECT c.ID from Trumpet\Models\Category c) HAVING SomethingNotInModels = "aaa"

#0 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#1 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#2 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#4 [internal function]: Phalcon\Mvc\Model\Query->parse()

```

> Reproduce the issue:
```php
$builder->columns('"aaa" as SomethingNotInModels')
            ->from(['a' => 'Trumpet\Models\Ad'])
            ->where('a.IDCategory IN (SELECT c.ID from Trumpet\Models\Category c)')
            ->having('SomethingNotInModels = "aaa"');
$builder->getQuery()->execute();
```
If I remove 'where' OR 'having' it doesn't trigger error.
### Details

* Phalcon version: 3.1.2
* PHP Version: 5.6.30-12~ubuntu14.04.1+deb.sury.org+1
* Operating System: Ubuntu
* Installation type: installing via package manager
* Server: Nginx
* Other related info (Database, table schema): 
```
create table Ad (ID INT(20), IDCategory INT(20));
create table Category (ID INT(20));
```

**Comment by alexbusu** [comment]
I have this issue as well.
So, to reproduce you just have to 
1. select a column with alias
2. use a sub-query in `WHERE` clause
3. use the alias further in `HAVING` OR `ORDER BY` (which in SQL will apply to selected result set, of course)
In my case the error trace is 
```
#0 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#1 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array)
#2 [internal function]: Phalcon\Mvc\Model\Query->_getOrderClause(Array)
#3 [internal function]: Phalcon\Mvc\Model\Query->_prepareSelect()
#4 [internal function]: Phalcon\Mvc\Model\Query->parse()
...
``` 
because I have used the alias in `ORDER BY` expression.

The issue is very strange, as after chasing the error it is not clear why this happens (looking at source code, this is not supposed to happen :smile:).

I have tried to debug by comparing `Query` of two cases: 
1. the failing case described above and 
2. a successful case, when I remove the sub-query in `WHERE` block.

What is the strange part I noticed is that all `_sql*` fields of `Phalcon\Mvc\Model\Query` are the same in both cases, except `_sqlColumnAliases` which, in failing case, was an empty array.
As I see, the `_sqlColumnAliases` variab;e is set only [here](https://github.com/phalcon/cphalcon/blob/v3.3.2/phalcon/mvc/model/query.zep#L2065) (I run Phalcon `v3.3.2` in prod, but the issue is still there for `v3.4.2` as well - tested on local). So the problem may _only_ be inside `for column in selectColumns` loop block above, right? Since the AST is the same except `where` property, then we should get the same result in `_sqlColumnAliases` (since column parsing happens before `where` and `having` and `orderBy`).
Here's the comparison (failing vs successful):
![image](https://user-images.githubusercontent.com/4104165/49392336-089b1800-f726-11e8-81d1-dfbeebb84388.png)
![image](https://user-images.githubusercontent.com/4104165/49392348-105abc80-f726-11e8-94f1-32b5e62acb56.png)

Since the columns in AST have aliases (and the `_ast.select.columns` is identical in both cases) they should always appear in `_sqlColumnAliases`, right?
![image](https://user-images.githubusercontent.com/4104165/49392660-01c0d500-f727-11e8-920f-e5344b5d5ffa.png)

Please help me sort this out!

**Comment by alexbusu** [comment]
Here is what I play with, trying to trace this issue
```php
$case = 'ok-without-where'; // can be 'fail', 'ok', 'ok-without-where'
$phql = sprintf(
    'SELECT [%1$s].[id], (SELECT [%2$s].[payout] FROM [%2$s] LIMIT 1) as publisherPayout '
    . 'FROM [%1$s] '
    . ([
            'fail' => 'WHERE [%1$s].[campaign_id] IN (SELECT [%2$s].[camapign_id] FROM [%2$s]) ',
            'ok' => 'WHERE [%1$s].[campaign_id] IN (1, 2, "a") ',
        ]
        [$case] ?? '')
    . 'ORDER BY publisherPayout DESC',
    Campaigns::class,
    CampaignPayoutHistory::class
);
$altQuery = new class($phql, \Phalcon\Di::getDefault()) extends \Phalcon\Mvc\Model\Query
{
    public function getAst()
    {
        try {
            $this->parse();
        } catch (\Exception $e) {
            fprintf(STDERR, $e->getMessage());
        }
        return $this->_ast;
    }
};
$ast = $altQuery->getAst();
```

It seems there is something wrong related to the `where` block, as the `AST.select.columns` are the same in all cases.

**Comment by alexbusu** [comment]
:information_source: **Workaround in Phalcon v3.x**
As v3.x will not include this update in further (security) releases, if any, here is a workaround for this issue, in v3.

```php
$parameters = [
  'conditions' => [ ... ],
  'columns' => [ ... ],
  //...
];
// adding aliases fix
$aliasFixConditionPhql = "EXISTS (SELECT 1 as myColNameOrAlias1, 1 as myColNameOrAlias2 FROM [\App\Model\DummyExistingModel])";
$parameters['conditions'][] = $aliasFixConditionPhql;
// fix is added, resume normal flow
$parameters['conditions'] .= implode(' AND ', $parameters['conditions']);
// ...
```
This basically adds a _fake_ sub-query that will _restore_ the aliases in `\Phalcon\Mvc\Model\Query` parser (as defined in `$parameters['columns']` or from other source, depending on your implementation).
