### ISSUE TITLE
Request Get Email with "+" in email

### ISSUE THREAD

**Issue by trentramseyer** [phalcon/cphalcon#13095]
Google allows you to use a "+" sign in your email to have multiple emails under one account.

The $request->get() removes that plus sign and leaves a space. 

If you add the $request->get("email","email") filter to it, it not only removes the "+" sign, it also removes the space.

**Comment by dugwood** [comment]
The issue isn't Phalcon, it the url encoder you use.

`/test?email=test+help@yourdomain.com` is encoded with a space in it, because `urlencode()` will replace space by a `+`. See: https://en.wikipedia.org/wiki/Query_string#URL_encoding

Try to use `rawurlencode` or something like this. 

If you want a plus sign, use: `%2B` (see: https://stackoverflow.com/a/1005699/781153)

Not a Phalcon bug, should be closed.

**Comment by dugwood** [comment]
Space is removed by Phalcon because it's not a valid character in emails (I recall that a lot of AOL users, back in the days, were using space which is forbidden, you were to remove it in order to send them an email).

**Comment by JABirchall** [comment]
Just tested this, not having any issues with phalcon and email suffix's

```php
        $user = new Users;
        $user->username = $request->getPost('username', ['trim', 'striptags']);
        $user->password = password_hash($request->getPost('password'), PASSWORD_BCRYPT);
        $user->email = $request->getPost('email', 'trim');
        $user->ip_address = $request->getClientAddress();
        return $user->save();
```

https://i.imgur.com/9Y0r69x.png

**Comment by dugwood** [comment]
@trentramseyer issue lies in the GET parameter:
`mydomain.com/form.php?email=mybadly+encoded@mail.com`
instead of:
`mydomain.com/form.php?email=mycorrectly%2Bencoded@mail.com`
