### ISSUE TITLE
Support for json and jsonb in PHQL for PostgreSQL dialect

### ISSUE THREAD

**Issue by tztztztz** [phalcon/cphalcon#13115]
### Actual Behavior

Right now trying to use jsonb condition in PHQL / Query builder:

SELECT ... FROM ... WHERE "priceInfo"::jsonb <@ '{"netto":23}'

resulting in parse error, while in psql console it is working properly.

### Enchancement:

Allow to use json and jsonb operators in PHQL queries.

Queries like this shoud'nt be a problem:

SELECT * FROM \k3\product\K3ProductEntity WHERE \k3\product\K3ProductEntity.picSmall::jsonb <@ '{"name":"Thor"}';

List of operators:

https://www.postgresql.org/docs/current/static/functions-json.html

Table 9.43. and Table 9.44.

### Temporary solution
There could be made temporary solution like "addNativeWhere" method for Query Builder, where Phalcon parser would simply igonore that section of where and pass it as it is to The PDO Adapter.

**Comment by Jurigag** [comment]
The temporary solution is simply dialect extension. And i guess it will be very long temporary solution, beacause to add anything to PHQL we need to change this lemon/c etc stuff.

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. There is a few approaches to achieve that:
1) As noted @Jurigag create new one or use dialect class from the Incubator
2) Using raw queries

Phalcon doesn't support json and jsonb in PHQL for now. If anyone wants to get started, I'd love that. Closing
