### ISSUE TITLE
Allow empty strings and orm.not_null_validations

### ISSUE THREAD

**Issue by NikolasSumrak** [phalcon/cphalcon#13161]
Hey guys!

I have one small question.

I have table with string field
```sql
`field` VARCHAR(255) NOT NULL
```
and i want to write empty string to this field 
```php
$model->field = '';
$model->save();
```

If enabled 
```ini
phalcon.orm.not_null_validations = On
```
i need to add 
```php
public function initialize()
    {
        parent::initialize();
        $this->allowEmptyStringValues([
            'field'
        ]);
```
to model.

I thing this is  wrong way!

I see at model.zep at 2104 line
```php
if isset emptyStringValues[field] {
   if value === null {
     let isNull = true;
   }
} else {
	if value === null || (value === "" && (!isset defaultValues[field] || value !== defaultValues[field])) {
		let isNull = true;
	}
}
```

I don't understand: what reason to adding
```php
(value === "" && (!isset defaultValues[field] || value !== defaultValues[field]))
```

It does not bring anything useful. I could not think of a single option when it came in handy.

*What do you think about it?*

**Comment by NikolasSumrak** [comment]
May be this code for non-string fields, like as timestamp, etc. But for string fields this isn't need, i think.

**Comment by Jurigag** [comment]
What's the point of saving empty string value to database when displaying it in view from database is the same thing(just empty stuff).

**Comment by stamster** [comment]
In general, you should design your database model in a way that `NULL` value will be set by default (if omitted), so simply on your middleware (app) you can simply omit empty properties. 
So instead of: `$model->field = '';` you could simply omit it, and value in DB will be `NULL`, which basically is what it is. Empty strings are rarely usable for human usage and can only lead to bugs and confusion.
