### ISSUE TITLE
Scripts blocking each other

### ISSUE THREAD

**Issue by aldos84** [phalcon/cphalcon#13283]
I have a problem with my Phalcon project.

In a Webpage I have ajax call to load analytic data from google, that took a few time. But if this script runs, my complete phalcon app are blocked until the script to get the google data has finished.

I test a workaround:
In a Controller Action you put a endless loop
```
public function loopAction() {
 while(true) {
 }
}
```

In a browser tab open the loop than the page is loading, now open another tab and navigate to another route of your project thats normaly works. By me now the both tabs are loading endlessly.
But only for me, if my collegue request the project, he can view and navigate without delays.

Can you help me? Is this a misconfiguration?

Thanks

Dominic

* Phalcon version: 3.0.1
* PHP Version: 7.0.27
* Operating System: Ubuntu 14.04
* Installation type: Compiling from source
* Zephir version (if any):
* Server: IntelliJ BuildIn Server

**Comment by Ark4ne** [comment]
Probably a problem on your web server, apache2 / nginx / ... it is not supposed to block simultaneous connections.

It's just an idea, but do you use xdebug?
Using xdebug with remote_enable will block simultaneous connections if your debbuger is listening.

**Comment by aldos84** [comment]
No, it wasn't my webserver. Sessions are that problem, because the file lock. If I write session_write_close(); before the loop, the loop function can run and the other pages loads.
My solution are to use Redis for sessions and not the FileAdapter.

**Comment by nadorator** [comment]
In fact, you can't do that. When you do a while(true) the cpu of the server is up to 100% then the server can't do anything else because the cpu is not an ARM ;)  So what you have to do is modify the algorithm of your php code to make it quicker and eventually do some of the treatment in javascript instead of php. You can also use workerprocess in your javascript to ease the usage of the browser while the ajax result is computed in your javascript.

**Comment by manyeung** [comment]
I met the similar case. I found that it is because of the file session.
