### ISSUE TITLE
javascript comments using // cause phalcon views to stop

### ISSUE THREAD

**Issue by eokenned** [phalcon/cphalcon#13304]
Including a javascript comment in a phalcon view will cause javascript to stop processing subsequent lines of code

Steps to recreate the problem

Place the following code at the end of a view phtml file
Script tag goes here
//this is a comment
alert("hello, world");
close script tag

The alert will not execute.
If you remove the javascript comment the view will work.

The problem does not seem to occur with /* */ style comments

Possible explanation/solution
This appears to be caused by line 42 of /public/index.php as generated by the phalcon project devtools command. This line appears to be attempting to strip carriage returns, line feeds and tabs from the output.

If I replace 
echo str_replace(["\n","\r","\t"], '', $application->handle()->getContent());

with

echo $application->handle()->getContent();

The problem with the javascript comments goes away.

### Details

* Phalcon version: 3.3.1
* PHP Version: 7.1.4
* Operating System: Windows 10
* Installation type: compiled phalcon dll
* Server: Apache - xampp

**Comment by trentramseyer** [comment]
Yes, that str_replace is not good for javascript in views. Been mentioned before and they need to remove it. 

If all else fails include a JS file and put the code there

**Comment by HACKHERS** [comment]
Well, please correct me if I'm wrong but this is not related to cphalcon that line is quick trick for htmlmin. When you delete all the lines with `str_replace` javascript comments make rest of the code commented out. So that's not a bug or error. For example in phalcon/forum there is [no str_replace after getContent();](https://github.com/phalcon/forum/blob/master/app/library/Bootstrap.php#L126)
