### ISSUE TITLE
Remove Beanstalkd from Phalcon

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#13364]
I propose to remove [beanstalkd][1] from Phalcon and move this functionality to the incubator or other repo. This may be done for 4.0.0 version.

Actually beanstalkd isn't a popular queue system. In addition, beanstalk doesn't provides any unique feature (except a bit magic terminology e.g. `tube`, `peek-ready`, etc.). This project has [zero activity][2] for many years, unanswered questions like [Is this project still active][3], lack of any out of box HA tools, replication tools, cluster integration, etc.

In fact many of our users do not use `beanstalkd` and even did not use. I think that in the framework there should be truly top requested and most used tools.

[1]: https://github.com/kr/beanstalkd
[2]: https://github.com/kr/beanstalkd/pulse/monthly
[3]: https://github.com/kr/beanstalkd/issues/299

**Comment by 409H** [comment]
> In fact many of our users do not use beanstalkd and even did not use.

I'm curious, how did you poll this?

I'm actually a user that uses the `beanstalkd` functionality of Phalcon, though I don't see how moving it into Incubator will affect me much, but is it a task worth doing? What would be the pros of moving it out of the core and into Incubator?

**Comment by niden** [comment]
@409H I too use `beanstalkd` on an environment with Phalcon. There have been quite a number of issues to maintain that environment, so we switched to AWS SQS to remove the burden. The maintenance cost for beanstalk became too much for us.

As for Phalcon, we are trying to keep the framework as slim as possible but as feature rich as possible. As mentioned by Serghei, the project has low activity (well zero actually) so we really don't want to support connection to a system that will potentially have bugs or is abandoned.

Moving the functionality to the incubator will have minimal impact to existing applications, since all you will have to do now is include the related composer package. 

HTH

**Comment by Jurigag** [comment]
If we will add rabbitmq as replacement then fine.

**Comment by davidtavarez** [comment]
rabbitmq is a good option

**Comment by 409H** [comment]
@niden I understand. Count me in favour of the proposal then.

**Comment by ruudboon** [comment]
I’m using the beanstalkd a lot. The reason for me to go for beanstalk is the native integration with Phalcon.
+1 for me to keep it part of Phalcon

**Comment by HanXHX** [comment]
Best way: a good refactoring with https://github.com/queue-interop/queue-interop

**Comment by rpacker** [comment]
We use it, but either way, I'd vote to add some other queues such as RabbitMQ, and SQS.

**Comment by marcelwenting** [comment]
New guy here, made an account specifically for this item.
Beanstalkd has become my queue system of choice because of the integration with PhalconPHP, even though I support the many cons that have been mentioned.
Therefor I would like to see another queueing system like RabbitMQ supported in the core before beanstalkd is removed from the core.
I would also like to suggest at transition period, where you would have 2 queueing systems in the core to smoothen the transition for those who do use beanstalkd.

**Comment by marcelwenting** [comment]
@benfavre What you are saying is definitely right, but it:
1) assumes one is using composer in the project.
2) Can cause a lot of work when supporting many projects(codebase, ci/cd etc).
3) It is not part of the precompiled framework anymore, therefor have a negative impact on performance.
The beauty of Phalcon is to have a full framework with support for the different components(db, cache, log etc). 
Where other components like databases, cache and image always gave multiple options. Queue never did. I think by having the framework support for other queuing systems, before removing the only current option is just the more devfriendly way to go.
Again; I support the the current idea of beanstalkd not being the a really viable option because of the lack of support/updates, but would just like a proper alternative introduced first.

**Comment by benfavre** [comment]
@marcelwenting So we shouldn't remove anything and instead access to Beanstalkd should be replaced by a higher level implementation, and we can move Beanstalkd to be one of the options of the wrapper.

**Comment by metaliciouz** [comment]
Alternative: https://github.com/pdezwart/php-amqp (PECL extensions)

**Comment by benfavre** [comment]
Thread should be closed if people are going to comment with Libs and opinions on packet managers.

**Comment by scrnjakovic** [comment]
I'd also like us have a queue system wrapper with adapters, and then roll out beanstalkd when we have decent alternatives.

**Comment by jellisii** [comment]
To extend @scrnjakovic's comment, having a base Queue adapter would fall in line with the Database/Model pattern that is well established within Phalcon.  

As a current user of BeanstalkD in several projects, going the route of an adapter would probably still break things for me, but also would allow for BeanstalkD to be contained in a single file/folder that still lived within the main code, bootstrap the addition of multiple other queue adapters alongside it.

**Comment by stamster** [comment]
All in all - alternative must be made avail. So abstraction layer (interface) which will provide same functionality across different adapters. Example is session adapter in Phalcon.

**Comment by Jurigag** [comment]
Tbh im personally thinking if we need whole adapter over redis/rabbitmq queue. Why reinvent a wheel? Just add only queue adapter using proper extension and some kind of cli class to make it handling of jobs added to queues easier, like we do:

```php
$queue->put('hello', 'world');
```

and

```php
class HelloHandler extends Phalcon\Cli\Task\RabbitMQTask
{
    public function handle($message)
    {
         echo $message->body; // displays world
    }

    public function config()
    {
        // custom function where we can type channel name, by default it uses class name or run it with some kind of sleep or whatever
    }
}
```

And run it in cli. I think we should use already provided extensions, don't write whole rabbitmq/redis queue adapter.

Though php-resque is the whole thing and it's php code.

**Comment by jellisii** [comment]
I guess a question that needs to be answered is "what are the common things that you have to do to a queue?"  Obviously Put/Push, Pop/Reserve, watch, some sort of job inspection method.  I presume other queuing systems (Gearman, RabbitMQ, etc) have some sort of construct for multiple queues so being able switch and inspect queues.  Getting the verbs for acting on queues to a common list would bootstrap the idea of a queue driver/extension, much like has been done for other components.

**Comment by jellisii** [comment]
It looks like there may be a second breath of life in BeanstalkD if today's discussion has any momentum behind it:  https://github.com/cornstalkd/cornstalkd

**Comment by sergeyklay** [comment]
FYI: beanstalkd is get well in [beanstalkd/beanstalkd](https://github.com/beanstalkd/beanstalkd)

**Comment by stamster** [comment]
Well, a little too late IMHO but let's where that will end.

I'm about to implement RabbitMQ native so it looks more promising on the long run than beanstalkd.

**Comment by mia0x75** [comment]
how about nsq? https://nsq.io/, a realtime distributed messaging platform written in golang.

**Comment by stamster** [comment]
It seems that beanstalkd just died (again). 

https://github.com/beanstalkd/beanstalkd/issues/399

For the folks giving thumbs down here - well, you don't have to take it personally - it's just facts, we all loved (past-tense) Beanstalkd.

**Comment by jellisii** [comment]
I still advocate for a driver instead of committing to a single queue.

**Comment by niden** [comment]
Resolved.

Discussion for new component: https://github.com/phalcon/cphalcon/issues/13851

**Comment by zz** [comment]
Beanstalkd just released 1.11 
https://github.com/beanstalkd/beanstalkd/releases/tag/v1.11

**Comment by maxttor** [comment]
buried early

**Comment by slothstronaut** [comment]
Really disappointed to see this was removed from Phalcon. I've used nearly every messaging system and beanstalkd has just the right amount of features and simplicity. RabbitMQ is likely overkill for most Phalcon projects. Removing this was a mistake.
