### ISSUE TITLE
I set up the baseUri, but it didn't work correctly.

### ISSUE THREAD

**Issue by kg-web** [phalcon/cphalcon#13406]
![image](https://user-images.githubusercontent.com/20922287/41328092-ea0b908c-6ef8-11e8-960f-9885518aa65d.png)

![image](https://user-images.githubusercontent.com/20922287/41328186-55c75f2c-6ef9-11e8-8105-3ca61fe24b36.png)
![image](https://user-images.githubusercontent.com/20922287/41328191-5e024fa8-6ef9-11e8-9761-c5783972fb81.png)
https://github.com/phalcon/mvc.The module is simple-volt.

**Comment by kg-web** [comment]
![image](https://user-images.githubusercontent.com/20922287/41328285-df92fb30-6ef9-11e8-8ea0-719da457b883.png)

**Comment by Ultimater** [comment]
Hi kg-web, 

We need more information from you in order to process this as a bug report.
Please share what you are using for the following files:
```
app/controllers/IndexController.php
app/views/index.volt
app/views/index/index.volt
app/config/config.php
```

Your example would be using the IndexController in your case, not TestController like the screenshot you're showing us. Your browser's address bar clearly shows `localhost/mvc/simple-volt/`.
There is nothing in the address bar that would confuse the uri to include `test/index` afterward.

I see you circled `echo 'text';` in your screenshot. This won't display due to output buffering. If you need to echo from a controller to verify it's being called, a quick way to check is like so with the exit on the end:
```
echo 'test';exit;
```

Moving to the next concern.
I see you're attempting to echo the baseUri. How are you outputting it exactly?
Are you sure you don't have code that would echo `/test/index/` after it?
Please try with:
```
[start] {{ url.getBaseUri() }} [end]
```
Expected output is:

> [start] /mvc/simple-volt/ [end]

This would ensure there's no characters getting inserted before or after and you're reading the correct value for baseUri.
