### ISSUE TITLE
[NFR] [VOLT] Add a merge filter for array setting

### ISSUE THREAD

**Issue by gsouf** [phalcon/cphalcon#1341]
Right now we cant merge merge arrays from the set tag

Twig has the following syntax to do it : `{% set myArray = myArray | merge({ "key" : "value" }) %}`
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

**Comment by dlgoodchild** [comment]
Hi guys. I'm coming from twig, and I'm currently mapping out differences between the syntaxes. I very extensively use the afformentioned `|merge( {  } )`. Is there a known way to do this in Phalcon (aside from writing my own filter)?

**Comment by gsouf** [comment]
@dlgoodchild I fell back to keep using twig because it's much more feature rich and both compile to php, that means that volt only takes advante of being written in C during template compilation process.

**Comment by dlgoodchild** [comment]
@gsouf I've been performance testing Twig, and actually many things Symfony, and Twig is really quite slow. At one point there even existed a C extension for PHP just to address the performance of a single function in the Twig codebase. The generated PHP of Twig is hugely different to the generated PHP of Volt.

For sure implementing filters and functions in Twig is much easier/simpler than in Volt, but that, to my understanding, is because of the resulting generated PHP.

A low-level merge would be a great idea.

**Comment by gsouf** [comment]
It would be, I agree, as many other features!

**Comment by dlgoodchild** [comment]
FYI, a simple implementation of merge is:

$oVolt->getCompiler()->addFilter( 'merge',
	function( $resolvedArgs, $exprArgs ) {
		return 'array_replace_recursive('.$resolvedArgs.')';
	}
);
I need to test it much more though, as the variables it operates on may not always be arrays, so it would need used with caution.

**Comment by quasipickle** [comment]
Late followup for anyone else googling this:  You can use PHP in your Volt files, so it would be possible to do this:

```php
<?php $myArray['key'] = 'value'; ?>
```
I'm sure this offends some people's sensibilities about using raw code in templates - but it is simple.

**Comment by Jurigag** [comment]
Better to just add filter.
