### ISSUE TITLE
Logger Interface (PSR-3)

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#13438]
Phalcon's logger must be fully compatible with [Logger Interface (PSR-3)](https://www.php-fig.org/psr/psr-3/) for v4.0.0

---

Refs:
- https://github.com/phalcon/cphalcon/pull/13437

**Comment by niden** [comment]
Implemented

**Comment by niden** [comment]
@virgofx This is not Phalcon to implement other interfaces (although the `Logger` now implements the PSR-3 one). it is to make the logger PSR compliant so it can be used in any application that utilizes that interface.

As for the where it is implemented, have a look at this: https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/logger.zep#L52

This is why v4 will require the PSR extension to be loaded before Phalcon.

**Comment by virgofx** [comment]
@niden I was looking for that in the code ... I see now. So in short, we implement PSR .. meaning it will now be a dependency for Phalcon. Interesting ... I see a little bit of a chicken and egg thing and this potentially becoming more of an issue in the future. I'm not saying it's bad per say ... however, it means that the bundled extension requires autoloaded classes to be loaded ahead of time -- not sure how this will scale.

**Comment by niden** [comment]
@virgofx Sorry for the late reply, just finished scanning my emails :)

Yes it is a chicken and egg situation. There is no other way that we know of to include the PSR extension so that we can take advantage of the PSR interfaces and offer PSR compliance per se.

I think now that alpha is out and we are learning as we go, it will become much easier for people to install the package especially from rpm/deb distributions because we could make PSR a dependency.
