### ISSUE TITLE
[NFR]  Make shared instances removable

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/cphalcon#13440]
From @xueron 

> When I use Phalcon in a multi-process scene, I have to remove any DB connections copied from parent.

> so I add two methods: one check a shared instance for a service exists or not, and another to remove a shared instance. That we can recreate it if needed.

Refs: https://github.com/phalcon/cphalcon/pull/13285

**Comment by sergeyklay** [comment]
@dragoonis Just assigned to you since you are currently working on ContainerInterface implementation in context of Phalcon's DI/ServiceLocator

**Comment by victorgp89** [comment]
Any update about this?

**Comment by dschissler** [comment]
I read the linked PR comments I would like to propose a whole new way of thinking about it.  I think that there is far too little cached short-circuiting around the [DI::get:226](https://github.com/phalcon/cphalcon/blob/b19d84a287477992cfabf258db8784486e140d1d/phalcon/di.zep#L226).  The [Service::resolve:120](https://github.com/phalcon/cphalcon/blob/b19d84a287477992cfabf258db8784486e140d1d/phalcon/di/service.zep#L120) is able to short-circuit from cache if its shared but then the DI doesn't use that state at all.

I'm proposing some logic like the following (it will be written for efficiency later):

```zephir
if service->isShared() && isset this->_sharedInstances[name] {
    return this->_sharedInstances[name];
}

try {
    let instance = service->resolve(parameters, this);
} catch ServiceResolutionException {
    throw new Exception("Service '" . name . "' cannot be resolved");
}

if instance->isShared() {
    let this->_sharedInstances[name] = instance
}
```

I'd like to point out that I made this DI+Service related commit for 4.0.x [right here](https://github.com/phalcon/cphalcon/commit/6766951396d2a097a80a7fba7ba2be0ff3741b4b).  I've been looking at this smelly code for a while now.  In hindsight its obvious as shit that the service name didn't need to be in the service constructor, but there it was.  My point is that `DI::get` shouldn't be treated as gospel and it is basically untouched since the moment it was ported from C to Zephir.  The core logic itself really isn't perfect.  Can we look there for a moment?

So now that we have a functional `DI::get` with cache short-circuiting then we can begin to think about using `get` instead of `getShared` (its used literally everywhere I believe in internal Phalcon) in as many places as possible.  I propose that if it doesn't need to be shared in 100% of every time then change it to `get`.  The DI factory defaults (hopefully soon to be my new preset tech) drops in all of the core tech as shared.  That should also be evaluated.

I'd like to quickly point out that the ["di:afterServiceResolve"](https://github.com/phalcon/cphalcon/blob/b19d84a287477992cfabf258db8784486e140d1d/phalcon/di.zep#L257) event wouldn't trigger if `::get` returned a shared instance but then neither does it ever when using `::getShared`.  So I propose that the before event name be changed to something like "di:beforeServiceDiscovery".  A shared event will trigger both the first time but then subsequent access will only trigger the first event.  I figure that the damn service is setup already and its shared.  Just give me the damn object.

After all of that we could still offer a method to just force restart a shared service, so why not?  Obviously its not working so lets give people the tools to push forward in the brittle wilderness of concurrency and forking.  To solidify my position, we can do a lot just with improving the deficient core  logic as well as offering people a new tool.  Hopefully then they can go farther with the default arrangements before they need to bust out the tricks.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/17027

**Comment by dragoonis** [comment]
I'm still here, lurking :-D  @sergeyklay

**Comment by niden** [comment]
> I'm still here, lurking :-D [@sergeyklay](https://github.com/sergeyklay)

Nice to see you Mr. Lurker :) 

PS: Serghei is no longer working on this project (life priorities).
