### ISSUE TITLE
Invalid Superglobal - Phalcon\Flash\Session

### ISSUE THREAD

**Issue by avitruk** [phalcon/cphalcon#13446]
Hi! This is a duplication of #13254. I get a blank page and getting Invalid Superglobal exception when I open my index page. This issue should be fixed in phalcon 3.4 version. But it still not works to me.

Please check the screenshot with some traces:

![Invalid Superglobal trace](https://image.prntscr.com/image/MTQR7GXGQBGMffnbYH9teg.png)

### Details

* Phalcon version: 3.4.0
* PHP Version: 7.2.0
* Operating System: windows
* Installation type: downloaded .dll from github
* Zephir version (if any): 0.10.7
* Server: Nginx 

What additional info can I provide to help find the solution?

**Comment by avitruk** [comment]
Tried downgrade PHP and Phalcon versions:

Phalcon 3.1.2 (Powered by Zephir - Version 0.9.7-1fae5e50ac) with PHP 7.1.12 - works perfect. 
All newer versions (starting from Phalcon 3.2.0) lead to the Invalid superglobal exception, described above

**Comment by Jurigag** [comment]
To use flash session you need to start session service first. Service in di is not started automatically, it doesn't works perfect because in reality it doesn't works at all without session started, like variable isn't shared between sessions, it was actually a bug like it was "working" but in reality not. In later versions zephir was fixed so it produces error like this if superglobal is not initalized but it's tried to used.

https://github.com/phalcon/cphalcon/issues/12921
