### ISSUE TITLE
[Discussion] Seperate phalcon 4.0 extentions into git submodules

### ISSUE THREAD

**Issue by JABirchall** [phalcon/cphalcon#13526]
I feel that in an effort of maintainability, each seperate exetention of phalcon come 4.0 should be seperarated into their own repositories and joined into the main repo via [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

This can be helpful for seperare smaller code bases, issues and pull requests for each part of phalcon.

Proposed version: 4.0

**Comment by niden** [comment]
This has been discussed between @sergeyklay and myself but we pretty much never came up with a solid decision on how to proceed. Here are a couple of pointers on this.

- Decide what `core` is and what is not.
- Logically split the extension in sub-modules similar to what PHP does (i.e. `php-phalcon-core`, `php-phalcon-orm-mysql` etc.)
- It might be unrealistic to split the submodules to different repos since at times there is common code between them (such as interfaces for instance). That will be a trial and error approach on how things can be reorganized
- To the above, we have our hands full handling issues in one repository, imagine what would happen if we have 10 or so... a solution would be all submodule repos do not allow issues
- Installation will need to change to install `phalcon-full` or `phalcon-core` and then whatever else the developer wants.

I am not sure if we can create two extensions with the same namespace. Can things load cumulatively? For instance your loading:
- `php-phalcon-core`
- `php-phalcon-orm-mysql`

The first extension would load `Phalcon` as the namespace where the second `Phalcon\ORM\Mysql`, I am not sure (have not tested this) if you can do that i.e. load one phalcon namespace on top of another, even if there are no collisions between namespaces.

**Comment by JABirchall** [comment]
Prehaps for some inspiration, laravel does a simular thing where each componant of the framework is seperated https://github.com/illuminate where they can be used standalone or installed as part of the laravel framework.

As an answer to point 1 and 3, illuminate has a [support](https://github.com/illuminate/support) component that provides functionallity which multiple components may share. 
For interfaces and stuff these should be apart of the extention in which they are used with PSR interfaces in the core or a shared submodule.

And I beleive that PHP allows cumulatively namespaces, as long as the namespace isnt already loaded. So you should be able to load `Phalcon` in 1 extention and `Phalcon\ORM\Mysql` in another. There shouldnt be much difference in behavour from exetentions and the lanaguage. Shouldnt be to hard to test. Just compile 2 simple namespace definitions where one extends on the other.

**Comment by niden** [comment]
@JABirchall To clarify my comment above, _I am not sure if we can create two extensions with the same namespace_ I haven't tried it so I don't know if it will work. If it does then great!

Other than that, the rest is just figuring out what to do and doing it :)

**Comment by RayHughes** [comment]
Personally I am against breaking Phalcon out into smaller modules. Unlike frameworks that are delivered by raw PHP, it would have little to no advantage and create confusion when managing the repositories.

One of the main benefits of componentizing a framework is reducing the amount of needed overhead. It makes sense to componentize frameworks like Symfony and Laravel as in their raw form they would be extremely bloated. By comonentizing, it allows a developer to pick and choose what they need and omit the rest. It also allows for usability of features in code bases which may not be organic to the particular framework.

Phalcon is written in Zephir and delivered as an extension. Using a component in a non-phalcon project would require the Phalcon run time regadless. If delivering a component over composer is the goal, the component would have to be translated to PHP which would have an adverse affect on the speed of Phalcon.

If increased speed is what you are after, disable directory based auto-loading and opt for the namespace based auto-loading. I have tested this on several home grown applications and have found they have a marginal speed bump (3-5%).

To truly take advantage of transitioning to a component based framework, Phalcon would have to be completely re-wirtten and a zephir based package manager would have to be developed solely for the purpose of Phalcon.

**Comment by LearnPhalcon** [comment]
Yeah https://github.com/illuminate seems interesting. I like to choose what I need and don't in final extension. There is things that I would never use in some projects. This would also make extension smaller (and maybe faster!?) for things like API or Micro only projects.
