### ISSUE TITLE
Memcached suddenly not working at all, website gives 500 errors

### ISSUE THREAD

**Issue by Brade** [phalcon/cphalcon#13633]
Essentially none of the pages of our web app work now because of a memcached error. NOTHING was changed in the configuration. We've already restarted apache and even rebooted the server, but the problem remains. Apache logs simply state the following: PHP Warning:  Memcached::setOptions(): invalid configuration option in ... index.php

```php
$di->setShared('cache', function () use ($config) {
    $frontend_cache = new FrontendData(['lifetime' => 0]);
    return new BackendMemcached($frontend_cache, ['servers' => [['host' => '127.0.0.1', 'port' => 11211]]]);
});

$di->setShared('session', function () {
    $session = new SessionAdapter(['servers' => [['host' => '127.0.0.1', 'port' => 11211]], 'client' => []]);
    $session->start();
    return $session;
});

```

### Details

* Phalcon version: (`php --ri phalcon`) 3.4.2
* PHP Version: (`php -v`) 7.0.32-0ubuntu0.16.04.1
* Operating System: ubuntu
* Installation type: installing via package manager
* Zephir version (if any):
* Server: Apache
* Other related info (Database, table schema): You can see from the code that only the bare minimum options are set, so not sure what the problem could be. It just randomly broke today. Any help is appreciated!!

**Comment by Brade** [comment]
Also your docs site is currently broken (only loading pages 1% of the time) so maybe it's related?

**Comment by Brade** [comment]
There's no easy way for me to test that, but the problem has only occurred today, and I upgraded to 3.4.2 yesterday.

**Comment by Brade** [comment]
I figured out how to downgrade to 3.4.1 and the problem no longer occurs. So yeah, there must be something wrong with the latest version.

**Comment by sergeyklay** [comment]
@Brade We'll try to sort out ASAP. Let us know if the problem will occurs with the 3.4.1. And any logs or any additional info will be appreciated

**Comment by dschissler** [comment]
Possibly you guys could roll out new versions as `rc` to the docs and forum sites before releasing.  So call it for example `3.4.2-rc1` and then give it about three days or more of being live.  It seems to me that this is likely a Zephir issue and by doing this `rc` you are also expanding the testing of the language as well.  Other frameworks are not using a separate language and so the language bugs can be detected by a huge community.  Unit tests only go so far.  Also lock the `rc` at a specific Zephir version for release.  Then later future Zephir versions can be used and if its a bug you can say that its a Zephir bug and to use the system package or the tarball with the already done `ext` directory setup.  So then you've taken it from being a "Phalcon bug" to a "Zephir bug".  Right now when you get moving fast its all a muddle.  Also for that matter I wouldn't mind seeing lots of `-betaN` releases in the future.

@sergeyklay Another point that I'm shocked and quite frankly disgusted about is that I was told that the `0.11` Zephir branch is not supported by Phalcon (or possibly the other way around).  I mean its beyond great that you've been spending so much time on the projects lately but how is anyone supposed to know about this?  I think that you need to work out a way that both Zephir and Phalcon can move forward in simultaneous or individual spurts while providing the community some degree of assurity that they haven't accidentally wandered into unstable development territory.  I think that you guys have avoided this issue for a long time specifically because of the way that Phalcon 2+ and Zephir were developed together.  In the beginning a Zephir bug was a Phalcon bug, clean and simple.  However now that Zephir is increasingly becoming its own thing the situation isn't good enough and you're going to run into some gnarly bugs if you continue to push the code as hard as you've been.

**Comment by sergeyklay** [comment]
@dschissler You're right. Phalcon v3.4 is not compatible with Zephir v0.11. Please note, Zephir is independent project. Zephir is not Phalcon and it develop independent from Phalcon. We expect that Zephir v0.11 or higher may be used for Phalcon v4.0 or higher. Zephir is a just programming language. That's all. Phalcon just uses Zephir as a main programmin language. Yes, Phalcon is it's well known Zephir consumer, but no more. FYI: We also plan to migrate all Zephir projects to the zephir-lang organization in future.

**Comment by Brade** [comment]
When do you think we will be able to upgrade phalcon with confidence? Right now I've put a `apt-mark hold php7.0-phalcon` in effect on our live server. I just tried upgrading today on my localhost and the same memcached errors still happen. I do notice that when I downgrade back to phalcon 3.4.1-1 apt also installs php7.0-sqlite3 and php7.0-memcached so I assume phalcon 3.4.2 had some pretty significant changes?

**Comment by niden** [comment]
@Brade Do you have a chance to test this with v4? The whole Cache namespace has been refactored to implement PSR-16 so I am pretty sure that this has been addressed.

**Comment by Brade** [comment]
I'll try to get to this soon, but obviously there are quite a few changes in v4, so it might be a while. Please don't close the issue yet =]

**Comment by niden** [comment]
@Brade No problem. Thanks for reporting this.

**Comment by ruudboon** [comment]
@Brade Just checking in to see if you had time to test this against Phalcon 4

**Comment by Brade** [comment]
I looked at it again recently and noticed that the PHP requirements for v4 are fairly tight and would require a version upgrade of ubuntu on our server. TBH I'm not totally sure when I'll be able to do it, so feel free to close this issue if necessary.

**Comment by ruudboon** [comment]
@Brade Thnx for your reply. I'll close it for now but feel free to reopen if you found something.
