### ISSUE TITLE
StringLength Validation after migration from 1.3.5 to 3.4.x 

### ISSUE THREAD

**Issue by pedroresende** [phalcon/cphalcon#13662]
When I use the StringLength validator on Phalcon 1.3.5 with the `max = null`, it works as infinite, however in 3.4.x it considers the limit to be 0 characters. Did something change ?

### Details

* Phalcon version: 3.4.2
* PHP Version: 5.6.38
* Operating System: Debian 8 aka Jessie 
* Installation type: Compiling from source
* Zephir version (if any):
* Server: Nginx

**Comment by jturbide** [comment]
Not sure about this, did you try to entirely remove the max parameter instead of passing null? Looks like they are checking if the option exists,

https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validator/stringlength.zep
https://github.com/phalcon/cphalcon/blob/master/phalcon/validation/validator.zep

**Comment by wajdijurry** [comment]
As Julien said, they check for min OR max. You should pass one of them at
least.

**Comment by niden** [comment]
Closing this. The option can be removed from the setup of the validator

Also as a note, v1 was purely C whereas v2 and later has been developed using Zephir. There are some differences between the two so this is probably coming from that. I am adding docs needed on this to update the documentation.

Thanks
