### ISSUE TITLE
When using the file cache, I encountered the performance degradation caused by too many cached directory files.

### ISSUE THREAD

**Issue by dongasai** [phalcon/cphalcon#13679]
This is a system with a lot of data, and it has too many cache files in its file cache directory,the performance became very poor.

Why not set up a subdirectory?(I turned SafeKey on)
### Details

* Phalcon version: (`php --ri phalcon`)
4.3.2
* PHP Version: (`php -v`)
7.2.6
* Operating System:

* Installation type: Compiling from source || installing via package manager
source
* Zephir version (if any):
* Server: Nginx | Apache | Other
Apache
* Other related info (Database, table schema):

**Comment by dongasai** [comment]
There is a "useSafeKey" function in our function, which can use the first few characters of the security key value generated by this function as the name of the subfolder.

**Comment by dschissler** [comment]
@niden You could use a solution similar to the what we did in [Phalcon Cookbook](https://www.amazon.com/Phalcon-Cookbook-David-Schissler/dp/1784396885) in Chapter 4 section "Using models as information repositories".  Lets say that you take the tiniest quickest file name or data hash of each item and then went base 26, 52 or 62 and then went 2-4 deep.  That is some really nice logarithmic growth there.  Probably make the fastest option default and then allow them to beef it up.  I'd wager that it would solve the shit out of most problems.  Its also easy.  The only challenging part is cleaning up the directories if that was ever needed.  Otherwise screw it, its cache and it will clean itself somehow later or its statically done in a build process and it doesn't matter.  It coul probably 

Also one final point about max files in a directory.  I think that far before a hard cack happens that the performance just goes to shit from the file system indexes being inefficient for that sort of thing.  I guess that probably has something to do with them optimizing for the 99.9% case.

**Comment by niden** [comment]
This has been addressed in https://github.com/phalcon/cphalcon/pull/14051
