### ISSUE TITLE
[4.0.x] Rename Phalcon\Cli\Console

### ISSUE THREAD

**Issue by ekmst** [phalcon/cphalcon#13714]
I propose to rename `Phalcon\Cli\Console` to `Phalcon\Cli\Application`.
Similarly with `Phalcon\Mvc\Application`

**Comment by niden** [comment]
I have no problem doing this, so long as the community decides whether it is best or not. 

I will post this in discord to get feedback.

**Comment by npfedwards** [comment]
In my opinion this creates unnecessary confusion. Just thinking from a developer efficiency standpoint, it'd be far to easy import the wrong class using your IDE. I can understand the viewpoint behind changing it but also, if it ain't broke...

**Comment by jturbide** [comment]
I like it separated in order to avoid confusion, in my case, I'm doing this from my bootstrap:

```
use Phalcon\Mvc\Application;
use Phalcon\Cli\Console;
...
$this->mode === 'console' ? Console::class : Application::class,
```

changing it would result extra noise as:

```
use Phalcon\Mvc\Application as MvcApplication;
use Phalcon\Cli\Application as CliApplication;
...
$this->mode === 'console' ? CliApplication::class : MvcApplication::class,
```

**Comment by dschissler** [comment]
I think that `Mvc` is already quite overused and I've changed it to `Web` in my framework.  I plan to introduce a swoole async mode application for first class server-sent instead of overlaying it onto a "cli" setup.  I dislike how much web first stuff there is in Phalcon and it shows that the cli stuff was added on mid-stride and then never refactored.

**Comment by ekmst** [comment]
I suggest the following options:

`Phalcon\Mvc\Application` to `Phalcon\Application\Mvc`,
`Phalcon\Mvc\Micro` to `Phalcon\Application\Micro`,
`Phalcon\Cli\Console` to `Phalcon\Application\Cli` or `Phalcon\Application\Console`.

And we take out the entry points to applications in a separate namespace.

**Comment by jturbide** [comment]
@ekmst +1

**Comment by virgofx** [comment]
Yeah I like make it component based. +1 @ekmst

**Comment by ekmst** [comment]
> How about `Phalcon\Application\Mvc` becomes `Phalcon\Application\Web`? If its not in the `Phalcon\Mvc` namespace then it can be renamed.
> 
> So:
> 
> ```
> use Phalcon\Application\Cli;
> use Phalcon\Application\Micro;
> use Phalcon\Application\Web;
> ```
> 
> or
> 
> ```
> use Phalcon\Application\Cli as CliApp;
> use Phalcon\Application\Micro as MicroApp;
> use Phalcon\Application\Web as WebApp;
> ```
> 
> End the MVC madness in 2019.

I think `Web` is a general case. Since the framework itself implies the creation of web applications, it will be more appropriate to use the types of these applications as the name(`mvc` and `micro`).

And `Cli` is a special case.

**Comment by jturbide** [comment]
@dschissler not all web app are using mvc, I think it's important to keep the pattern in order to differentiate different architectures

```php
use Phalcon\Application\Cli;
use Phalcon\Application\Micro;
use Phalcon\Application\Mvc;
use Phalcon\Application\Hmvc;
use Phalcon\Application\Pac;
use Phalcon\Application\Mvvm;
use Phalcon\Application\Mvt;
...
```

**Comment by ekmst** [comment]
> @dschissler not all web app are using mvc, I think it's important to keep the pattern in order to differentiate different architectures
> 
> ```
> use Phalcon\Application\Cli;
> use Phalcon\Application\Micro;
> use Phalcon\Application\Mvc;
> use Phalcon\Application\Hmvc;
> use Phalcon\Application\Pac;
> use Phalcon\Application\Mvvm;
> use Phalcon\Application\Mvt;
> ...
> ```

I agree

**Comment by ViltusVilks** [comment]
Yep, +1 for  `Phalcon\Application\xyz` as component
but arch-specific stuff under required architecture namespace

so then it make sense to separate Web (pool by httpserver) and Cli (direct exec) ... but... also running from cli is possible with Swoole (like self-hosted app in NET for example),

```
use Phalcon\Application\Cli;
use Phalcon\Application\Web\Micro;
use Phalcon\Application\Web\Rest;
use Phalcon\Application\Web\Rest\Swoole;  // just an example
use Phalcon\Application\Web\Mvc;
```

**Comment by dschissler** [comment]
What about the following?

```
use Phalcon\Application\Type\Cli;
use Phalcon\Application\Type\Micro;
use Phalcon\Application\Type\Mvc;
use Phalcon\Application\Type\Hmvc;
use Phalcon\Application\Type\Pac;
use Phalcon\Application\Type\Mvvm;
use Phalcon\Application\Type\Mvt;
```

There is already `Phalcon\Application\Exception`.  Additionally my Perch project has a lot of stuff in `Perch\Application` namespace because it is opinionated.  For example there is an app config class which reads the root application.yml.  I'd like to be able to use the same naming scheme as Phalcon.  I think that claiming the entire Ph\App namespace could get us into trouble (it already does with the Exception, although I don't know if the application needs its own exception).

If you guys can get behind this in the next 1-2 days then I can make it happen.

**Comment by dschissler** [comment]
@ViltusVilks I like your idea.  I don't believe that we can use the root of `Phalcon\Application` namespace due to other stuff needing to go in there like `Exception`.  So what about this, its basically the similar to using `type` but separating by if its initiated from the cli or through a web server.

```php
use Phalcon\Application\Cli\Console;
use Phalcon\Application\Cli\Pm;
use Phalcon\Application\Cli\Swoole;
use Phalcon\Application\Web\Micro;
use Phalcon\Application\Web\Mvc;
```

Guys we need to get moving on this since its unlikely to happen if we approaching a beta.

**Comment by jturbide** [comment]
I am still voting for my previous proposition without the cli/web context. I don't see any problem of sharing a namespace with other classes like Exception. I fact, I do this all the time in different other contexts.

Contradictory, within my application I currently use App\Cli\Console as well as App\Mvc\Application in order to match Phalcon's logic but in the end I wouldn't really mind altering that namespace for another explicit approach.

**Comment by dschissler** [comment]
I have four other files in my `Perch\Application` directory.  It will be five with Exception.

**Comment by dschissler** [comment]
Please vote in #13868 for the way to rename the application classes.

**Comment by dschissler** [comment]
I refactored my project to Choice 3 of the vote since its close enough to Choice 4 that I can update it easily depending on how the vote goes (even though I chose 4).  I'm seeing that Choice 3 is really quite fine if I just ignore that some of the classes in the root Application namespace aren't application classes.  If there ended up being many types of applications and other application support classes then it would be a bit of a muddle.  Nothing huge but more difficult for a newbie to see what is what.

@erisrayanesh might be presenting some research on refactoring the parts of the application class sometime soon.  I'm imagining how the different modes of an application break down and how much commonality there is between all types of applications and the two specific "runmodes" of Cli and Web.  For web there is micro and mvc and for cli there is "tasks" and in the future other looping/async types of apps like Swoole.  How much is it worth considering since we don't know exactly what that will look like?  I'm not sure if a CLI Swoole and Task app will look anything alike.  So I'm wondering if there is any value in the Choice 4 (`App\Web` and `App\Cli`) since its a separation that organizes app classes which may not inherit the same things.

**Comment by jturbide** [comment]
@dschissler I agree, will do the same from my end too.

**Comment by dschissler** [comment]
@jturbide Please vote in 13868.  I created the other issue to vote (without too much discussion) based on the feedback from here.  So far the vote seems to be successful in that there haven't been any new proposed structures.  To be clear it kind of needs a straight up vote.  Its non-binding but don't see why it wouldn't be respected by everyone (including the Team) in the end.
