### ISSUE TITLE
[NFR] Cache Compression

### ISSUE THREAD

**Issue by CameronHall** [phalcon/cphalcon#13740]
I was reading an article the other day about [Redis Cache Compression](https://doordash.engineering/2019/01/02/speeding-up-redis-with-compression/). I was thinking it'd be a fantastic idea to add support for it? Perhaps it's better suited for the incubator?

**Comment by CameronHall** [comment]
Absolutely, but for things like the model's metadata cache I could see it making sense.

**Comment by CameronHall** [comment]
Thanks for all that @ViltusVilks. I didn't even realize `igbinary` was compressing the data structure anyway. I had never really looked into what makes it different. If it was something that actually went ahead, I'd be more interested in having it implemented as a `CompressableInterface` or something of the like. That way "Frontends" such as `Data``, `base64` and `JSON` could implement it and have it optionally enabled.

It does look like there is existing support for Frontends that already solve this problem, so if you haven't got any troubles with adding a new extension this NFR seems unnecessary.

**Comment by ViltusVilks** [comment]
`Backend` is only KV store. How You save is Up-to-You, this is why `Frontend` exists and can be overriden. Problem can appear if somebody else reads/writes these KV's.

As I said, if you have big "content" and want hit billions req/sec and also have cluster then every request will hit more or less same compressed data and decompressing data will take CPU time... And then you will be paid for wasted CPU time. This is in terms of cloud/docker deployment (per cpu cycle).

NFR is good if igbinary not available, because we need it to execute at low-level and compression is needed, otherwise pure `Frontend` fine-tuning + Multi-Level cache in PHP now works fine

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
