### ISSUE TITLE
Running PHQL with the FROM clause inside functions

### ISSUE THREAD

**Issue by ronald677br** [phalcon/cphalcon#13756]
I was trying to run this query, with PHQL:

`$phql = "SELECT * FROM Robots WHERE extract(DOW FROM my_timestamp_column) = 0";
 $this->modelsManager->executeQuery(($phql));`

This led me to the following problem:

`Syntax error, unexpected token FROM, near to ' my_timestamp_column) = 0', when parsing: SELECT * FROM Robots WHERE extract(DOW FROM my_timestamp_column) = 0 `

I think this is a problem related to the "protected" SQL keyword "FROM" being used inside functions with the syntax similar to the "EXTRACT" function.

This problem also occurs when using the QueryBuilder class, but does not when running raw SQL.

* Phalcon version: 3.4.2
* PHP Version: 7.2.13
* Operating System: Ubuntu 18.04
* Installation type: Compiling from source
* Zephir version: 0.10.14-975ad02db4
* Server: Apache
* Other related info (Database, table schema): Using PostgreSQL, version 10

**Comment by niden** [comment]
This is because what you are trying to do is not supported by PHQL. PHQL is and needs to be as simple as possible and as DB agnostic as possible. There are a lot of features that exist unique for each RDBMS and PHQL does not support those. 

You can however try to define your own custom dialect - if applicable. Have a look at this.

https://blog.phalconphp.com/post/phalcon-2-0-3-released

**Comment by niden** [comment]
Closing this
