### ISSUE TITLE
PHQL doesn't support postgres '||' operator.

### ISSUE THREAD

**Issue by hks2002** [phalcon/cphalcon#13761]

**Comment by JABirchall** [comment]
Isn't that just the OR operator.

**Comment by hks2002** [comment]
`||` in postgres not means `OR`, it means `+` or  `concat `.

**Comment by hks2002** [comment]
Thanks. 
My current phalcon version is 3.4. If I use phql, some sql error doesn't feedback to me, no query result, no error message, it let me hard to find the root issue. 
I prefer to use raw sql, so that all sql statements could be run at other database client, and result be checked/confirmed.

**Comment by TimurFlush** [comment]
@hks Open a new issue if you experience this behavior.

**Comment by niden** [comment]
@hks2002 This is not a bug. We never supported that because it is specific to Postgresql. 

You can either use a custom dialect as @TimurFlush mentioned or switch to raw sql.

Now if you do see issues when using PHQL, please open a new issue and provide as much information as possible for us to fix it. 

Thank you!
