### ISSUE TITLE
Feature Requst: Factory for Metadata

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#13780]
Hello, I just suggest to add factory for Metadata =)

**Comment by v00v** [comment]
What do you mean by Metadata? Please more details.

**Comment by TimurFlush** [comment]
@v00v I'm sorry, but I'm gonna assume you're retarded.
Please see https://github.com/phalcon/cphalcon/tree/master/phalcon/mvc/model/metadata

**Comment by niden** [comment]
@TimurFlush I get that English might not be your native tongue, but kindly refrain from using expressions like that for other contributors. First and final warning.

**Comment by TimurFlush** [comment]
@niden Okay, i'm sorry. Sometimes it happens to me.

**Comment by TimurFlush** [comment]
@niden is it clear. Thank you

**Comment by v00v** [comment]
@TimurFlush I forgive you :-) And yes English is my 2nd language. But this is not the problem. I simply wanted for you to explain in more detail what you are requesting. But if you are unable to, I understand ^_^

@niden Thanks for the help. It's not suprising people are so mean online. Because they are behind a computer and think they are 100% anonymouse they can say anything. The problem with that is that you never know who the person you talking to is ;-)

**Comment by TimurFlush** [comment]
@v00v I forgive you too)

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
Will be addressed in https://github.com/phalcon/cphalcon/issues/13672
