### ISSUE TITLE
NFR Use REQUEST_URI by Default

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13812]
Why do we need to use ``$_SERVER['REQUEST_URI']`` in Phalcon v4 ? Can we simply use ``REQUEST_URI`` by default if nothing is defined there? Its a bit weird having to do something like this;

Required Usage Now in Phalcon v4. Note this was not needed in v2,v3.
```php
echo $app->handle($_SERVER['REQUEST_URI'])->getContent();
```

Request NFR, if Nothing is defined use ``$_SERVER['REQUEST_URI']`` by default.
```php
echo $app->handle()->getContent();
```

and while we are at it, why use ``$app->handle()`` if you can simplify it like ``$app->getContent()`` ? Love Phalcon framework, but sometimes it seems like some functions are over complicated. Does ``handle()`` have other purpose than just doing ``getContent()`` that I don't know about?

**Comment by dschissler** [comment]
How about `$app->run()`?

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.

**Comment by niden** [comment]
I had a look at the code behind this and here are my comments.

First of all `handle()` does a lot of work, pretty much everything your application needs to do in order to finally display something on screen based on the input provided by the user.

This includes routes calculation and resolving, dispatching, modules calculations and more. The bulk of the logic is in `handle()`. As we all know this process does not always need to "output" anything. As a result the `getContents()` is a different method that the developer must call in order to "display" data.

`getContent()` is a shortcut to get the data from the view layer and send it back to the user. In reality this will be a string (HTML/Json/XML  etc.) that need to be send back to the user. The `handle` will then pick it up and send it along with any necessary headers, cookies etc.

Passing the URI in the handle offers a lot more flexibility to handle various parts of the application or even create some sort of sub applications, should there is a need to.

One of the big changes in v4 is that we are removing pretty much all the superglobals inside Zephir code. If a superglobal array needs to be accessed, we will need to pass it as a parameter so that the actual superglobal is immutable. Using the `$_SERVER['REQUEST_URI']` inside the `handle()` of the application (if a URI has not been passed) breaks that contract and opens the door to segfaults in the future for Zephir/Phalcon.

I was thinking about the cost vs. reward in addressing this. The safest way to address this would be to have a collection object in the Application object which would store a copy of the `$_SERVER` array initialized by say `->setServerArray($_SERVER)`, That would take the copy of the superglobals and store it internally.

The issue though is that we only need the URI and I cannot find a use case that the `$_SERVER` superglobal would be required inside that object other than one element (REQUEST_URI). As such, we will be wasting some memory every single time our application handles by holding an array, only to use one string in the case that the `uri` has not been passed as a parameter. This to me is an overkill.

Final thought is that once the application is set and bootstrapped, a developer would pretty much never change the code

```php
$app->handle()->getContent();
```

This remains as is and in reality it is part of the initial boostrapping and setup of the application. Changing the above to be:

```php
$uri = $_SERVER['REQUEST_URI'];
$app->handle($uri)->getContent();
```

is really negligible as a change while offering more options for use cases.

I am in favor of closing this but will wait for the core team to comment on this

cc @phalcon/collaborators

**Comment by ruudboon** [comment]
Creating a global collection sounds like an overkill. So I agree with @niden it's a mall change in your bootstrap and offers a lot of new possibilities to use the handle.

**Comment by niden** [comment]
Closing this.
