### ISSUE TITLE
NFR disableSuffix()

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13813]
Request for new ``disableSuffix()`` option, instead of having to use empty ``setControllerSuffix()`` and ``setActionSuffix()``. I never use suffix on any of my projects. I find it too cumbersome.

The way It used now:
```php
$di->set('dispatcher', function() {
   $dp = new Dispatcher();
   $dp->setControllerSuffix('');
   $dp->setActionSuffix('');
  return $dp;
});
```

New Request NFR to be used like this:
```php
$di->set('dispatcher', function() {
   $dp = new Dispatcher();
   $dp->disableSuffix();
  return $dp;
});
```

**Comment by TimurFlush** [comment]
lol?

**Comment by niden** [comment]
I really don't like adding the positive _and_ the negative of an action i.e. `enableX` and `disableX`.

Since this happens only in one spot (i.e. the dispatcher) which is pretty much a set and forget component, honestly I don't think that it will add value to the framework. You can do the same thing as you mentioned in the first example, even it is with two lines of code.

**Comment by niden** [comment]
Unless there is another scenario that I have not considered, please let me know. Otherwise this will be on the won't fix tag

**Comment by v00v** [comment]
@niden Fair enought. Thanks for explaining.
