### ISSUE TITLE
NFR voting system?

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#13810]
Technically, this isn't a feature but I think should be discussed here rather than on the forum due to the advantage in reach this repo has.

I feel that community is growing and every now and then NFR's pop up here and as interesting as they may be, they are very rarely followed by PR's.

There are a lot of features found in other frameworks that phalcon lacks and it would be nice to have them implemented in Zephir. In other aspects, however, phalcon leaves those frameworks in the dust. Given that our community is still relatively small, one cannot expect phalcon's maintainers to match features of frameworks run by big teams and backed by huuge communities, like Laravel.

Having that said, I think that we, as community, would benefit from having a NFR tracker, where community could cast their votes for the new features which would then be prioritized by the maintainers and contributors. I think that NFR's should stand out from the issues, not be buried among them. That way, we'll have a clear insights into what are most requested features.

What'ya think?

**Comment by niden** [comment]
We have done this in the past (pre v2 versions) to prioritize things that the community needs more than others. That would be a great tool to help with the prioritization of NFRs.

One other thing that will definitely help with this is v4 getting to stable. In this version we concentrated removing all bugs from the issues and leaving all NFRs. In subsequent versions we will continue addressing bugs first and then with the help of a tool such as the one you describe, prioritize NFRs.

**Comment by scrnjakovic** [comment]
So, basically, you're for introducing such a tool once v4 becomes stable?

**Comment by v00v** [comment]
Voting on NFRs would be a great idea :-) And having a NFR tracker is even better. GitHub is good for NFRs discussions but having one huge database with all NFRs with statuses like "Acceted" "Rejected" etc. would be awesome. Because we can all check the progress, vote on something we need and developers can then look at NFRs popularity and do those first. This will also be good to see which NFRs are not welcome by Phalcon community.

**Comment by dschissler** [comment]
The vote was already put forth.  This can be closed.

**Comment by niden** [comment]
Since Github does not offer a voting system and I really do not want to introduce new apps (made from others or us making one) I will close this issue for now.

In the future we can pin an issue as we have recently done and ask the community to vote for their favorite NFRs. Also a blog post should help with that.
