### ISSUE TITLE
NFR Phalcon Auto Refresh Browser On File Change

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13818]
Can we have a feature in Phalcon to monitor file changes like (created modified) and auto-refreshing page in browser like firefox, chrome. This can be an optional development only option enabled under bootstrap for example. This is very useful for any static data changes like HTML/CSS/JSON/YAML for example. I'm sure there is browser plugins and other software that can do this. But to this day I could not find anything that works well with modified files. So it got me thinking on direct Phalcon feature for this :-) I don't know how difficult this would be to implement or if even possible. Comments or suggestions are welcome!

**Comment by JABirchall** [comment]
This isn't possible. Phalcon has no control over the browser after the request has finished. And also phalcon doesn't running unless there is a request to handle in the first place.

AKA: out of scope. you need a JS framework for that, such a vue.

**Comment by dschissler** [comment]
Its not within the scope of Phalcon.  This should be closed since its extremely unlikely to be readdressed for at least a year.

**Comment by niden** [comment]
@v00v Help me understand this correctly

Phalcon (and its applications) are sitting on the server. The only exposed part is the view you create to show to your guests/visitors. 

Even if there was a monitoring service in Phalcon that would react to a change in a file etc. there would be no way (as things are now) for the application to notify the browser of user A or user B. To establish that communication you will need some javascript on the visitor's browser or sockets (I think).

Is that what you were thinking of?

**Comment by dschissler** [comment]
webpack can do this easily because it loads JS into the browser that then receives updates from the webpack-dev-server via websocket.  For Phalcon to do this you would first need to implement some kind of cross-platform inotify/inode support and then either settle on server-sent or websockets.  Since Phalcon can't/shouldn't rely on PHP it would need to be provided by the [Swoole](https://www.swoole.co.uk/) extension.  I believe that Swoole and Phalcon are natural allies but there is almost no synergy there at the moment.  

The way that Phalcon is now it basically offers very limited "Framework" support and its much more of being only a low-level library.  I don't see that changing for at least the remainder of the v4 lifecycle until Phalcon possibly splits itself into different packages.  Even then it will be more than enough work just splitting it and its unlikely to many new features like this until its  rerefactored with some new features (v6?).

I have big ambitions to provide a Swoole async mode in my Perch framework, but its a ways off since the two classic web and cli modes are not yet completed.  I think that its 1000% more likely that my upcoming Perch Framework could offer something like this within say the next two years than Phalcon proper.  This is very interesting but I can't fathom it going anywhere for so long.

**Comment by david-duncan** [comment]
@v00v you are looking for a solution like livereload. Webpack offers something better, but this would be pretty trivial to setup with a file watcher like grunt

https://github.com/gruntjs/grunt-contrib-watch#live-reloading

**Comment by ViltusVilks** [comment]
Phalcon is backend. It can take care only on cache control, etag and dynamic js serving.

**Comment by niden** [comment]
Closing this one as it is not actually a Phalcon bug
