### ISSUE TITLE
NFR setDefaultNamespace() Alias setNamespace()

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13814]
Can you guys rename ``setDefaultNamespace()`` or simply add additonal alias like ``setNamespace()`` or maybe even use default "App\Controllers" if nothing is set.

How its used now:
```php
$di->set('dispatcher', function() {
   $dp = new Dispatcher();
   $dp->setDefaultNamespace('App\Controllers');
   return $dp;
});
```

Request alias command:
```php
$di->set('dispatcher', function() {
   $dp = new Dispatcher();
   $dp->setNamespace('App\Controllers');
   return $dp;
});
```

**Comment by v00v** [comment]
@niden Thank you for NFR tag!

**Comment by dschissler** [comment]
I'm working on this now and it seems like deprecation is a poor fit for a new major version.

Take a look at this function:

```zephir
	protected function _resolveEmptyProperties() -> void
	{
		// If the current namespace is null we used the set in this->_defaultNamespace
		if !this->_namespaceName {
			let this->_namespaceName = this->_defaultNamespace;
		}

		// If the handler is null we use the set in this->_defaultHandler
		if !this->_handlerName {
			let this->_handlerName = this->_defaultHandler;
		}

		// If the action is null we use the set in this->_defaultAction
		if !this->_actionName {
			let this->_actionName = this->_defaultAction;
		}
	}
```

That is pretty much the extent of the most of the `default` crap instead of just setting it directly in the service definition.  However!, there could be serious consequences like if someone was doing a `if defaultNamespace === currentNamespace` in an event or plugin.  Is there a use case for that.  There may or may not be a killer use case for that?  I would love to just delete this crap that I've never used without using a deprecation notice but it could have some big consequences for someone.  Probably 99% of the users could benefit from just simpler function names but that 1% might be SOOL if we remove it.

**Comment by niden** [comment]
Closing in favor of #13855. Will revisit if the community votes for it, or in later versions.
