### ISSUE TITLE
Replace minifiers (css/js)

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#13819]
The current minifiers for JS/CSS rely on a library by Douglas Crockford and its license is "BSD with restriction".

We need to remove this library and replace it with one that does not have restrictions or roll out a in-house implementation.

The library needs to be removed from v4 but the Phalcon classes will remain as they are, returning back (for now) the original file i.e. pretty much doing nothing. This is in order to keep SemVer happy when we do roll out the new minifying library (in future versions of v4)

Reference: #10118

**Comment by ruudboon** [comment]
With all the current tools (webpack, grunt, less, sass. typescript etc) that are available noways I'm wondering if this is still a wanted feature in the framework and if it should be removed from the framework totally.

**Comment by dschissler** [comment]
I make extensive use of an optional Webpack in my Perch Framework.  I would never consider using Phalcon for minifying.

**Comment by niden** [comment]
Resolved

**Comment by dschissler** [comment]
Less is more.  If there is a solution for this then it is likely using a composer package.  It would be nice in the future if Phalcon could have an official ecosystem of supporting PHP-land packages which are designed to act as glue code between other famous libraries.

**Comment by david-duncan** [comment]
I couldn't agree more with the comments in this thread. Focus efforts on 7.4 and 8.x

**Comment by dschissler** [comment]
@niden Is there a way to augment the filter factory from PHP land?  If not then please design the API so that more filters could be added (if its not already).

@sergeyklay @niden 
I'm thinking that you guys could make something like a `phalcon_extras` git repository.  Then each directory could be for a composer package.  Then make an effort to gobble up community created packages and to put it under the official Phalcon banner in `phalcon_extras`.  Then give each (quality) package owner commit access to the repository to maintain their package.  Then you can just control the release of the actual composer packages to make sure that crap doesn't get put out.  Perhaps assign a new person to this role since you guys sometimes drop out for weeks at a time.  This will all give the community a foot hold into the Phalcon project for contributing code.  As it is now is too damn much of a chasm to get started.  In regards to this particular minifier - I wouldn't use it but other people might and especially noobs or for toy projects.
