### ISSUE TITLE
NFR Volt setMinify()

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13816]
Request for output minify option in Volt. To be used something like this;

Options can be;
* ``static``-- to minify html output (*.html)
* ``style`` -- to minify stylesheet (*.css)
* ``script`` -- to minify javascript (*.js)
* ``extension`` -- to set file extensions.

Example Usage:
```php
$di->set('view', function() {
  $view = new View();
  $view->setViewsDir('../app/views/');
  $view->registerEngines([
    '.volt' => function($view, $di) {
      $volt = new Volt($view, $di);
      $volt->setMinify([
        // specific examples
      	'static' => true,
      	'style' => true,
      	'script' => true,
        // extensions example
      	'extension' => 'html,css,js'
      ]);
      $volt->setOptions([
        'compiledPath' => '../app/cache/',
        'compiledExtension' => '.html',
        'compiledSeparator' => '_',
        'stat' => true,
        'compileAlways' => true,
      ]);
      return $volt;
    }
  ]);
  return $view;
});
```

**Comment by TimurFlush** [comment]
There is no need to explain for a long time how regular expressions work at high load projects.
I support only the minify html output and this should be done once when writing to the cache.

**Comment by niden** [comment]
This will definitely have a performance impact on the framework especially when the `compileAlways` is on, because every template used in the request will have to be parsed to minify certain fragments.

@v00v can you offer a bit more information as to why this would help? We do have the css/js minify functionality in assets.

**Comment by v00v** [comment]
@niden ``compileAlways`` is there for offline development only. I also recently found [1] assets. But as far as I understand this is only for CSS/JS and not HTML it self.

[1] https://docs.phalconphp.com/3.2/en/assets

**Comment by JABirchall** [comment]
Ref: #2349

**Comment by david-duncan** [comment]
I vote closing this in favor of a more extensible options like filters like demonstrated by @JABirchall in #2349

**Comment by niden** [comment]
I agree. Lets close this and figure out a good way for everyone to work with this. 

Honestly I don't think that Phalcon should perform this task i.e. minify JS/CSS or HTML. However we can come up with some sort of mechanism where we can attach a filter, custom or supplied that would do the operation of minifying or otherwise. We can address it in #2349

**Comment by Jurigag** [comment]
Im not sure we need this, i don't feel like framework should do this. You have cloudflare which can do it, as well as pagespeed extension for nginx/apache to do this job.
