### ISSUE TITLE
Model::unserialize wrong signature

### ISSUE THREAD

**Issue by fizzka** [phalcon/cphalcon#13848]
i've been checked my project with psalm (https://github.com/vimeo/psalm) 3.0.17, and:

```
$ psalm models/Files.php

ERROR: MethodSignatureMismatch - models/Files.php:11:7 - Argument 1 of Phalcon\Mvc\Model::unserialize has wrong type 'mixed', expecting 'string' as defined by Serializable::unserialize
class Files extends Model
```

```php
class Files extends Phalcon\Mvc\Model {}
```

### Details

* Phalcon version: 
php --ri phalcon

phalcon

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.4.2
Build Date => Feb  2 2019 08:19:15
Powered by Zephir => Version 0.10.14-975ad02db4

* PHP Version: PHP 7.3.2 (cli) (built: Feb  9 2019 02:11:33) ( NTS )
* Operating System: alpine3.9
* Installation type: https://hub.docker.com/r/mileschou/phalcon/
* Zephir version (if any): Powered by Zephir => Version 0.10.14-975ad02db4

**Comment by Jeckerson** [comment]
@niden

**Comment by metaliciouz** [comment]
Oh, I know this.
Same issue: https://github.com/phalcon/ide-stubs/issues/17

**Comment by niden** [comment]
This one has to do with the stubs generated from Zephir. We will need the wizzardry of @sergeyklay

**Comment by niden** [comment]
@fizzka @metaliciouz 

I looked at this a bit more in depth. So we have in Zephir:

```zephir
public function unserialize(var serialized) -> void
```
This translates to
```php
public function unzerialize(mixed $serialized)
```

Looking at this: https://php.net/manual/en/serializable.unserialize.php the above is wrong. According to the manual the signature should be:

```php
abstract public Serializable::unserialize ( string $serialized ) : void
```

Now if you look at say PHPStorm, the signature of the stub is:
```php
    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized);
```

I have made the change and run it through Travis [here](https://travis-ci.org/niden/cphalcon/builds/535562579) and as you can see the build fails.

![002](https://user-images.githubusercontent.com/1073784/58181640-2af40400-7c7a-11e9-96e5-316b2fc1a610.png)

Compiling the application against PHP clearly fails on this since the PHP ZTS version that Travis uses, does not provide the signature with `string $serialized` rather `mixed $serialized`

Reverting the change allows the build to pass.

![001](https://user-images.githubusercontent.com/1073784/58181636-26c7e680-7c7a-11e9-9a01-d7db0fe26a18.png)

@sergeyklay  any thoughts ?
