### ISSUE TITLE
Divide Phalcon\Application handle method routine into separated methods and subroutins

### ISSUE THREAD

**Issue by erisrayanesh** [phalcon/cphalcon#13873]
## Problem
There is no way to do minor modification on `handle` method of `Phalcon\Application` routine, except using events. Events are great but sometimes the routine requires to be changed.
The only way is using Manual bootstrapping which doesn't worth. 

##  Solution
The solution could be dividing `handle` method into separated `protected` methods.

> Example: `handle` method from line 147 to 175 could call another method for parsing matched route
```php
let matchedRoute = router->getMatchedRoute();
if typeof matchedRoute == "object" {
	let match = matchedRoute->getMatch();
        if match !== null {
        	return this->callMatched(match);
        }
```

Also other parts of this routine could be changed like the code above. 
* Parsing module
* Dispatching
* Parsing dispatcher returned value
* View rendering.

**Comment by dschissler** [comment]
For something like this I recommend that you offer a PR with some of the changes.  The PR doesn't need to be merged for it to be effective, nor do the tests need to pass.  Then you can point to your code specifically instead of writing in the abstract.  Do you know how to develop for Phalcon and to provision a system to get it ready?  If not then I recommend starting with my [setupify](https://github.com/perch-foundation/setupify) provision system.  Its real easy to get going on an Ubuntu 18.04 this way.  Otherwise you need to just install the zephir compile extension, Zephir and then clone the 4.0.x Phalcon tree.  There are a lot of steps though and it can be cumbersome to switch between development sources, official builds and other things, which is why I made setupify.

**Comment by erisrayanesh** [comment]
@dschissler Thanks for your recommendation. I'll try it and present it as soon as possible.
