### ISSUE TITLE
ORM doesn't make use of Relation::HAS_ONE_THROUGH

### ISSUE THREAD

**Issue by CameronHall** [phalcon/cphalcon#13903]
Phalcon has a definition for a relationship through an intermediary table but doesn't actually make use of it. Can we please consider adding support for `hasOneThrough`?

Thanks.

**Comment by dschissler** [comment]
I say that recently Serghei has been doing a great job at improving Zephir and that we could really use that money for improving Volt and PHQL.  Since I'm between work right now I was already spending many days on improving things with a flurry of PRs.  I'm thinking that I could do a whole full-time month of work for possibly as little as $2000 or possibly just for much less and super part time.  Otherwise, ha, just not going to happen.  I've worked a bit in that code before when I basically fixed nested queries by digging through the AST with the nasty codes and the whole bit (the hard way).  I'm weak in C though which is the only thing.

I can just hear Nick now:

> Of all of the programmers loved by the gods, I hate him the most.

What do you say @niden?

**Comment by dschissler** [comment]
The reality of Phalcon is that people continue to propose huge time sinks and there are few willing to do any work while the huge pot of cash just keeps getting larger.  Its a pretty weird situation actually.

**Comment by JABirchall** [comment]
Wheres the definition you are refering too.

**Comment by CameronHall** [comment]
`Phalcon\Mvc\Model\Relation` I believe.

**Comment by zsilbi** [comment]
Implemented in https://github.com/phalcon/cphalcon/pull/14511
