### ISSUE TITLE
both `configure.ac' and `configure.in' are present

### ISSUE THREAD

**Issue by phpfangting** [phalcon/cphalcon#13916]
hi

onfiguring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
autoconf: warning: both `configure.ac' and `configure.in' are present.
autoconf: warning: proceeding with `configure.ac'.
autoheader: 'configure.ac' and 'configure.in' both present.
autoheader: proceeding with 'configure.ac'

**Comment by sergeyklay** [comment]
As you can see it is just warnings, not error. This is what we got from the PHP team- it's by design.

**Comment by phpfangting** [comment]
> As you can see it is just warnings, not error. This is what we got from the PHP team- it's by design.

thanks

**Comment by levaconline** [comment]
I know, warnings are just warning (not error). But,why not remove term Warnings from programming since it make confusion among people (since terminals by default colors Warning text in red same as errors). Sometime, warning block can be huge, so one need to scroll up to beginning to find is it warning or error. If terminal buffer is too low, beginning of block cannot be found and one don't know is it error or warning. No big deal, but just notice.

**Comment by levaconline** [comment]
E.g.
![image](https://github.com/user-attachments/assets/b8f3ee60-3726-4008-9b01-5e25692d113c)
