### ISSUE TITLE
[NFR] Phalcon GitHub Documentation

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#13983]
Request for Phlacon GitHub Documentation, to better explain to people who don't use GitHub whole process like what all this labels like NFR - New Feature Request mean etc. This may help more new people get involved in GitHub process like Issues by reporting Bugs/NFRs. You can start by defining all the GitHub labels used for Phalcon project like;

GitHub Issues Labels:
* NFR "New Feature Request" - and then a small explanation...
* RFC "Request For Comments" - and then a small explanation...
* BUG - and then small explanation about a bug and the process.

Then move to when/how the bug is resolved/closed/fixed etc... Then maybe even some explanation how things are added and done in Phalcon changelog.

I think you get the idea. I'm a developer myself and don't have many problems with many of this technical terms. But you can see how it can get confusing to new people trying to get involved - especially if they don't use GitHub or even ever seen what NFR is.

Another example, recently I posted a bug https://github.com/phalcon/cphalcon/issues/13968 and it later changed to closed then "4.0 Release automation moved this from To do to Done 15 hours ago" what is all this process means? Will this fix be in next alpha build or in stable v4.0 build?

**Comment by sergeyklay** [comment]
Hello @v00v,

Well, sounds reasonable.
I propose start with improvements of [CONTRIBUTING](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md) file which is used in pull request page 
![image](https://user-images.githubusercontent.com/1256298/56324591-f28f7080-6177-11e9-8289-0577aef91193.png)

**Comment by v00v** [comment]
@sergeyklay Sure, but maybe at least a link to it in documentation somewhere. Also, if possible maybe you could guys as in official phalcon develpers can include some sort of explanation or drawings of phalcon release cycle? Good example can be found on XFCE wiki [1]

[1] https://www.xfce.org/about/releasemodel

**Comment by niden** [comment]
@v00v can you please create a new PR with whatever you think we should have as descriptions etc. so that we can add it in the documentation? It doesn't have to be complete if you do not know certain parts of the terminology, we just need a starting point so that we can all work together and address this issue.

I am going to close this for now and waiting for your PR. Feel free to reference this with your PR.

And FYI `4.0 Release automation moved this from To do to Done 15 hours ago` comes from the 4.0 project (see repo -> projects -> 4.0). It happens when we move the cards from one column to another.

Thanks!
