### ISSUE TITLE
Rename methods `getSchema`, `getSource` on Mvc\Model

### ISSUE THREAD

**Issue by CameronHall** [phalcon/cphalcon#14036]
I propose we rename the methods `getSchema` and `getSource` to `getModelSchema` and `getModelSource`. Though this is just a bandaid.

I'm open to anything, as long as the ORM isn't restricting what I can use as column names.

**Comment by sergeyklay** [comment]
What about `model_schema` column name ?

**Comment by CameronHall** [comment]
Like I said, I'm open to anything, perhaps even renaming those methods to `_getSchema` or something. Whatever it takes to prevent the restriction of using certain column names.

**Comment by sergeyklay** [comment]
`_getSchema` will cause PSR/Code style error notifications from the 3rd party tools for users who will use inheritance in PHP  :man_shrugging:

**Comment by sergeyklay** [comment]
Anyway [columMap](https://docs.phalconphp.com/3.4/en/db-models.html#independent-column-mapping) is your friend in such cases :wink:

**Comment by SidRoberts** [comment]
I'm hesitant to change it to anything else. I think this is something we should address when we look at building the model system with the data mapper pattern.

**Comment by Jurigag** [comment]
I agree with this, many times there are issues and you can't use pretty much column name as name of get* method from model because it will break some functionalities. I think we should either rename such methods or simply just throw exception if we get any of reserved columns as name and tell them to use columnMap and other property name on class than in database.

**Comment by JABirchall** [comment]
What if this was moved out of the model into the base database class.
`$schema = $this->db->getSchema(Model::class);`

That way you can avoid conflicts.
