### ISSUE TITLE
[NFR] Logger formatter per message type

### ISSUE THREAD

**Issue by scrnjakovic** [phalcon/cphalcon#14178]
It would be nice if we could define formatter for specific message types instead one for all, so we could add red color for error, blue for notice etc.

**Comment by niden** [comment]
You can use the `FormatterInterface` and specify the formatter you want. Since it supports interpolation you can easily inject content to the relevant message. 

The `FormatterInterface` accepts a `Logger\Item` object and thus you should know the type of it as well to apply colors.

It think that should cater for this use case.

**Comment by scrnjakovic** [comment]
Actually, it does. Thanks @niden. We could add it to incubator?

Closing this one.
