### ISSUE TITLE
How do I convert an array to a simple object?

### ISSUE THREAD

**Issue by sowork** [phalcon/cphalcon#14183]
```
$users = User::find();

$posts = Post::find();

$newPosts = [];
foreach($posts as $post) {
      if (in_array([1, 2, 3], $post->id)) {
            $newPosts[] = $post;
      }
}

$users->posts = $newPosts; // It's an array, and I think it should be a (simple|model) object
```
* This scenario is encountered in preloading, but I don't know what to do with it?

**Comment by sowork** [comment]
https://forum.phalconphp.com/discussion/9051/array-convert-to-phalconmvcmodelresultset

This is some information I searched on the Internet, but there is no answer.  
tks.

**Comment by gaurangkumar** [comment]
Here, in_array() function has invalid arguments.
```
in_array ( mixed $needle , array $haystack [, bool $strict = FALSE ] ) : bool
```
```
$posts = Post::find();

$newPosts = [];
foreach($posts as $post) {
      if (in_array($post->id, [1, 2, 3])) {
            $newPosts[] = $post;
      }
}
```
[function.in-array](https://www.php.net/manual/en/function.in-array.php)

**Comment by sowork** [comment]
@gaurangkumar yes
but can convert an array to a simpleResult object?

**Comment by niden** [comment]
@sowork the simple answer is you cannot. The only thing you can do is:

```
$myObject = (object) $myArray
```

which will return back a `stdClass` object. 

In your example, `$users` is already a collection of objects and the same thing with `$posts`, so provided that `$users->posts` is a defined relationship, the `$newPosts` array contains the array of `Posts` objects needed.

```php
$users = User::find();
$posts = Post::find();

$newPosts = [];
foreach($posts as $post) {
      if (in_array([1, 2, 3], $post->id)) {
            $newPosts[] = $post;
      }
}

$users->posts = $newPosts
```

**Comment by sowork** [comment]
but `$user->posts` to define an associated relationship triggers n+1
so I need to query the required post data and then assign the value to the `$user` object
Now I'm assigning $user to an array
```
$users = User::find();
$userIds = array_column($users->toArray(), 'id');
$posts = Post::find([
      'conditons' => "id in $userIds"  // just example
])
$posts = array_column($posts, null, 'userId');
foreach ($users as $user) {
      $user->post[] = $posts[$user->id];
}
```
The returned `$user` object `post` property is an array

**Comment by niden** [comment]
<?php

I don't understand exactly what you need to do/ Do you just want to get the data or update them also?

To avoid n+1 you can do:
```php

$builder = (new Builder())
   ->addFrom(Users::class, 'u')
    -innserJoin(Posts::class, 'p.user_id = u.id', 'p')
    ->orderBy('u.name')
    ->getQuery()
    ->execute()
;
```

Now you have all the data you need and you can either create `Resultset` objects and populate them manually or use the `Complex` resultset you get from the collection above and work with that data.

If you want to be able to update data that you got, then instead of doing a pre-loading or eager loading which will give you a great number of results that is stale i.e. not really used by the application (in most cases), it will be **much** faster and you will consume a lot less resources by querying the data only when you need it and not preloading it.

Phalcon does not support eager loading as it inherently consumes a lot more resources than necessary. However you can have a look at this repository: https://github.com/stibiumz/phalcon.eager-loading.for an implementation that might help.

**Comment by sowork** [comment]
>I don't understand exactly what you need to do

I want to append the data from the eager load to the simple object
make it look natural, instead of binding the array to the property above the object
it’s like this now:
```
$eagerLoad = [['id' => 1], ['id' => 2], ['id' => 3]];
$simple = User::find();
$simple->eagerLoad = $eagerLoad;
```

> Phalcon does not support eager loading as it inherently consumes a lot more resources than necessary. 

I don't understand why it consumes a lot more resources. 
example：
```
User::with('posts')->find([]);
// will make two queries,
//select * from users;
// select * from posts where userId in (1,2,3)
or
User::with(['posts' => function($builder){
       $builder->columns(['filed1', 'filed2']);
}])->find([
      'columns' => 'id, name'
]);
// will make two queries,
// select id, name from users;
// select field1, field2 from posts where userId in (1,2,3)
```
i will see how the resultsSet operates. 
english is not too good, sorry.
tks.

**Comment by niden** [comment]
I wrote above Phalcon does not support eager loading. There is a github repo that might help you. 

To achieve what you want to do in the example above you can do this:

```php
$builder = (new Builder())
   ->columns(['id', 'name')
   ->addFrom(Users::class, 'u')
    -innserJoin(Posts::class, 'p.userId = u.id', 'p')
    ->whereIn('u.userId', [1,2,3])
    ->orderBy('u.name')
    ->getQuery()
    ->execute()
    ->toArray()
;
```
All the data is in the array now

**Comment by sowork** [comment]
it looks like the builder performs better sql

consider outputting data of the following structure
```
{
  "data": [
          [
               "id": 1, 
                "name":"name1", 
                "post": [
                       “field1”: "value1",
                        "field2": "value2"
                 ]
           ],
           ......
    ]
}
```
obviously builder is not suitable for organizing deep data structures

**Comment by niden** [comment]
You need to create the array structure the way your application needs. The database will not always be able to construct the array the way you want it. Since you have the 'data' node there you might want to have a look at Fractal, which allows you to perform transformations to resultsets easily

https://fractal.thephpleague.com/

**Comment by sowork** [comment]
tks, looks great！

but does eager load bring too much resource consumption?

**Comment by niden** [comment]
The eager vs non eager loading is the same as use tabs vs spaces in your code. No answer is correct and both answers are correct depending on who you ask.

For me, eager loading in the database layer offers more complexity than the problem it solves. If you have your ORM perform the eager loading for you, you will never get all the potential use cases that developers will need. To offer the most functionality to developers, your ORM becomes much more complex and heavy because it has to calculate all sorts of paths in order to parse developer input and produce the results needed. This is what I mean by too much resource consumption.

Doing the eager loading yourself based on your needs at the time is much more desirable since you will be able to adjust your query and criteria.
