### ISSUE TITLE
Unable to install package: php7.3-phalcon : Depends: phpapi-20180731

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14258]
When installing Phalcon from the mainline under Debian using the following flow. Phalcon fails to install with the error message:
```
The following packages have unmet dependencies:
 php7.3-phalcon : Depends: phpapi-20180731
E: Unable to correct problems, you have held broken packages.
```
This behaviour is reproducible using the following steps (docker required)
```
docker run -it php:7.3-cli-stretch bash
apt-get update -y
rm /etc/apt/preferences.d/no-debian-php
curl -s https://packagecloud.io/install/repositories/phalcon/mainline/script.deb.sh | bash
apt-get install php7.3-phalcon
```
If the /etc/apt/preferences.d/no-debian-php file isn't removed the package cannot be found at all.

**Comment by ruudboon** [comment]
@sergeyklay Can you explain the label? Is this something I'm doing wrong, otherwise we can close this.

**Comment by sergeyklay** [comment]
> php7.3-phalcon : Depends: phpapi-20180731

Any PHP package in Debian based systems requires a `phpapi-*` package. Let's look at `php-memcached` package for instance:

```shell
$ apt-get update &> /dev/null
$ apt-cache show php-memcached -a | egrep -o "phpapi\-[[:digit:]]+"
phpapi-20151012
```

So _in this_ test we see that `php-memcached` requires `phpapi-20151012`.

Every time when you install a package using a package manager, it looks for the dependencies installed with the package manager (i.e. `apt-get install ...`, `dpkg -i ...`, etc). If these dependencies have not satisfied, package manager will look for these dependencies in available repositories.

Your image has PHP installed using the compile from sources method. So it is nonstandard way. Package manager know nothing about installed PHP API version. 

To install php7.3-phalcon from packagecloud.io you have satisfy its dependencies: install PHP 7.3.* using the package manager. Otherwise you'll need to clone cphalcon repo and then call build/install.sh script.

**Comment by Jurigag** [comment]
https://github.com/docker-library/php/blob/master/7.3/stretch/cli/Dockerfile This image as you can see is build from source.

**Comment by ruudboon** [comment]
I see, thnx for the explanation. Let's close this. And will try to add a note in the docs.
