### ISSUE TITLE
Calling model::create() does an _exists() twice if the record doesn't exist

### ISSUE THREAD

**Issue by maxgalbu** [phalcon/cphalcon#14256]
### Expected and Actual Behavior

Calling model::create() does an _exists() twice if the record doesn't exist.
https://github.com/phalcon/cphalcon/blob/2be495d9d12fb17e6da997a4c175e00566c7306f/phalcon/Mvc/Model.zep#L964
https://github.com/phalcon/cphalcon/blob/2be495d9d12fb17e6da997a4c175e00566c7306f/phalcon/Mvc/Model.zep#L2316

### Details

* Phalcon version: (`php --ri phalcon`) all the way to 4.0.x from 3.0.x
* PHP Version: (`php -v`) any
* Operating System: any
* Installation type: any
* Zephir version (if any): none
* Server: any
* Other related info (Database, table schema): any

😞 😞

**Comment by niden** [comment]
Looking at the code it kind of makes sense because `create()` throws an exception if the record exists already, where `save()` will change to update mode if the record exists. 

Not sure how to refactor this to keep on offering the same functionality. We can certainly remove `create()` because it does the same thing as `save()` but then you will lose the functionality of having an exception thrown if the record exists.

Thoughts?

**Comment by david-duncan** [comment]
There is definitely a bug here - 

`create()` should check the write connection.

Replica lag means that you will never be 100% correct when checking if a record exists if you check the read connection.

**Comment by niden** [comment]
@david-duncan good catch

**Comment by ruudboon** [comment]
Maybe we could set operationMade to OP_CREATE in the create method before calling save and skip the check if it's already defined?

**Comment by niden** [comment]
Resolved

**Comment by maxgalbu** [comment]
Wait t still does two selects... since we do a check on the write connection, the check on the read one is not useful... this will slow down the app if there are a lot of inserts
