### ISSUE TITLE
[Q] [4.x] namespace of DiInterface.zep

### ISSUE THREAD

**Issue by lajosbencz** [phalcon/cphalcon#14254]
Shouldn't ```phalcon/Di/DiInterface.zep``` be in the root path: ```phalcon/DiInterface.zep```?

Placing the corresponding interface for ```phalcon/Di.zep``` in a different folder seems counter-intuitive, and the usage is convoluted aswell.

**Comment by niden** [comment]
We are trying to keep the root namespace as clean and thin so to speak as possible. The `DiInterface` relates to the `Di` namespace. So two options here: either leave it in the root namespace and have to remember that it does indeed relate to Di or put it in the `Di` namespace/folder.

Now looking at `Phalcon\Di\DiInterface` (2 instances of the word `Di`) might not be ideal but since we cannot use the word `Interface` on its own we have to prefix it with `Di`.

This move has been part of a larger effort to group things much tighter with their namespaces and as mentioned keep the root namespace thin - i.e. not many things on it. The ideal scenario would be to only have folders for the root and each namespace has its own component(s) in it. We did try to move things around in the last few months but ended up having `Phalcon\Config\Config` which was not really ideal. 

Hope this helps clear up things a bit.

**Comment by lajosbencz** [comment]
Then how about this refactoring like so:

```phalcon/Di.zep``` -> ```phalcon/Di/Container.zep```
```phalcon/Di/DiInterface.zep``` -> ```phalcon/Di/ContainerInterface.zep````

**Comment by niden** [comment]
`Container` is reserved for the PSR-11 container that exists now as a proxy to the DI component but in subsequent v4 versions will be rewritten from scratch. 

So these two have to be separate since the new container (Container) cannot be a drop in replacement for the existing one (Di)

**Comment by ruudboon** [comment]
I think we can close this one. In v5 this will change.
