### ISSUE TITLE
[NFR] Native Markdown Support

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14370]
Request for markdown support in Volt or as an optional library that can be enabled by namespace like ``Phalcon\Output\Markdown``. Maybe using some tags like ``{% mdstart %}`` ``{% mdend %}`` tags. In the past I've used Parsedown library.

[1] https://parsedown.org/

**Comment by sergeyklay** [comment]
This already discussed 4 years ago https://github.com/phalcon/cphalcon/pull/10090 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
