### ISSUE TITLE
[NFR]: Volt PHP Block

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#14473]
Can we have dedicated volt php blocks? Instead of having to use ``<?php`` we can use something more volt like ``{% php %}``. I got this idea from another issue here #14436

```php
{% php %}
  function myPrint($text) {
    echo "<h1> $text </h1>";
  }
{% php %}

{% myPrint("Hello Phalcon World!") %}
```

**Comment by niden** [comment]
Are you describing this? https://github.com/phalcon/cphalcon/issues/1253

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that. 

A little hint for those who want to get started: You will need to work on [lexer](https://en.wikipedia.org/wiki/Lexical_analysis) (C99), language [parser](https://www.hwaci.com/sw/lemon/) (C99), grammar ([LALR(1)](https://en.wikipedia.org/wiki/LALR_parser)), [memory leaks](https://en.wikipedia.org/wiki/Memory_leak) ([Zend Engine](https://en.wikipedia.org/wiki/Zend_Engine)) and refine the View Engine ([Zephir](https://docs.zephir-lang.com/0.12/en/welcome)). Yes. Just to provide yet another view of `<?php` tags.

**Comment by v00v** [comment]
@niden No not #1253, this is for PHP. Instead of using ``<?php ?>``

**Comment by niden** [comment]
@v00v Honestly there is no value for making an alias of this

`{% php %}`

for this

`<?php`

Are you trying to make us have carpal tunnel man? (more keystrokes) :D :D :D
