### ISSUE TITLE
[BUG]: Inconsistency in handling cache prefix

### ISSUE THREAD

**Issue by krazzer** [phalcon/cphalcon#14503]
It looks like \Phalcon\Cache\BackendInterface::queryKeys implementations are inconsistent in the use of the global prefix.

**To Reproduce**
```php
<?php

use Phalcon\Cache\Backend\File;
use Phalcon\Cache\Backend\Memory;
use Phalcon\Cache\Frontend\Data;

$cache = new Memory(new Data, ['prefix' => 'prefix:']);
$cache->save('key', 'value');

print_r($cache->queryKeys('prefix'));

$cache = new File(new Data, ['prefix' => 'prefix:', 'cacheDir' => __DIR__ . '/']);
$cache->save('key', 'value');

print_r($cache->queryKeys('prefix'));
```

**Output**

```php
Array
(
    [0] => prefix:key
)

Array
(
)

```

**Expected behavior**
I expect neither requiring to provide the prefix
```php
Array
(
)

Array
(
)

```
**Details**
 - Phalcon version: 3.4.4
 - PHP Version: 7.2.19
 - Operating System: MacOS High Sierra
 - Server: Apache

**Comment by Jeckerson** [comment]
Can you try with latest `v3.4.5` version?

**Comment by krazzer** [comment]
I have tested it with v3.4.4, where it's the same. I can't test v3.4.5.

**Comment by niden** [comment]
I checked this in v4 and it seems that the keys returned are identical (in usage that is) for all adapters. The keys returned have the prefix indeed but they are not empty in Memory and filled in others. Also since the whole cache component has been rewritten, the `getKeys` (new name) does not require the prefix.

I am marking this as Won't Fix, since v3 is not supported and v4 does not have this problem. 

Relevant tests
https://github.com/phalcon/cphalcon/blob/4.0.x/tests/unit/Cache/Adapter/Stream/GetKeysCest.php#L48
https://github.com/phalcon/cphalcon/blob/4.0.x/tests/unit/Cache/Adapter/Redis/GetKeysCest.php#L51
https://github.com/phalcon/cphalcon/blob/4.0.x/tests/unit/Cache/Adapter/Memory/GetKeysCest.php#L55
https://github.com/phalcon/cphalcon/blob/4.0.x/tests/unit/Cache/Adapter/Libmemcached/GetKeysCest.php#L69
https://github.com/phalcon/cphalcon/blob/4.0.x/tests/unit/Cache/Adapter/Apcu/GetKeysCest.php#L58

**Comment by niden** [comment]
Closing this. Please re-open or open a new one if other issues persist with the cache
