### ISSUE TITLE
[BUG]: Transactions not working on the Logger component

### ISSUE THREAD

**Issue by diplopito** [phalcon/cphalcon#14514]
Phalcon v3.x had support for transactions in the [Logger component](https://docs.phalcon.io/3.4/en/logging#transactions) but they got lost in v4. Would be ideal to bring them back.

**Comment by niden** [comment]
In the logger for v3 we used to have transactional logging with `$logger->begin()` and $logger->commit()`

Although those methods exist in each adapter, there is no real way to access an adapter as an object from the logger so that you can call `begin` or `commit`

We need to add something like this `$logger->getAdapter('prod')->begin()`

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14516

**Comment by niden** [comment]
Thank you @diplopito
