### ISSUE TITLE
[BUG]: Cannot build in alpine based docker with PHP7.4

### ISSUE THREAD

**Issue by adhocore** [phalcon/cphalcon#14574]
The minimal Dockerfile looks like:

```Dockerfile
# ./Dockerfile
FROM php:7.4.0-fpm-alpine3.10

RUN apk --update add --no-cache autoconf g++ file re2c make libtool

RUN docker-php-ext-install pdo_mysql

RUN curl -Lo /tmp/phalcon.tar.gz https://codeload.github.com/phalcon/cphalcon/tar.gz/v3.4.5 \
    && cd /tmp/ && tar xvzf phalcon.tar.gz \
    && cd cphalcon-3.4.5/build && sh install
```

Build: `docker build -t my/phalcon:7.4 .`

The error is basically about `php_pcre_match_impl`

PS: Same problem with phalcon3.4.4 as well

**Comment by ruudboon** [comment]
PHP 7.4 isn't supported for Phalcon 3.4. You should be able to run Phalcon 4 on 7.4.

**Comment by sergeyklay** [comment]
\

**Comment by adhocore** [comment]
> PHP 7.4 isn't supported for Phalcon 3.4

hmm cool. would you care to explain why? is it by design or choice or philosophical reason?

---
anyway, is phalcon 4 production ready? then that would be where anyone should go for

**Comment by ruudboon** [comment]
@adhocore We're a small team and currently we need all our resources finishing Phalcon 4. We would love to support everything but need to make choices in the end.
Not exactly sure what needs to be done to run 3.4 on 7.4 but it will take effort. Only releasing on 3.4 branch itself will take some time since it isn't as much automated as the 4 branch. 

Phalcon 4 is almost ready. We're working on the bug's that are reported by our community who are testing the RC.3. You can track our progress here. https://github.com/phalcon/cphalcon/projects/3

**Comment by adhocore** [comment]
ok thanx for info, appreciated :+1:

**Comment by adhocore** [comment]
we will try out and test our app with phalcon 4 and let you know

**Comment by niden** [comment]
@adhocore The upgrade guide is here:

https://docs.phalconphp.com/4.0/en/upgrade

**Comment by bitmammoth** [comment]
I've been able to get Phalcon v4.0.0-rc3 to run on php 7.4.1 (CLI) compiled from source on Ubuntu 19.10 but not on the apache2 web server I don't know if that helps but the module loads and mostly everything works when I run Phalcon code from the terminal. Doesn't seem to be loading the extension in the php.ini

**Comment by Jeckerson** [comment]
Did you added in both .ini files: web and cli?

**Comment by adhocore** [comment]
getting phalcon 4.0rc on PHP 7.4.1 is rather straight forward and easy it seems:
https://github.com/adhocore/docker-phpfpm
