### ISSUE TITLE
Remove ACL Firewall before 4.0 release

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14630]
We want to deliver 4.0 fully documented. Currently we are struggling with the ACL firewall documentation. It's unclear how to exactly use it and how it internally works.
It's a really nice new feature for Phalcon but before we release it we must make sure we fully understand it so we can document it and help out community when they have questions.
For the release I want to rollback these changes and add them as a NFR for 4.1.

This is the main pull #14078
I see the following related pulls.
#12561
#11590
#14450
#14455

**Comment by ruudboon** [comment]
Implemented

**Comment by sergeyklay** [comment]
Branch with firewall https://github.com/phalcon/cphalcon/tree/4.0.x-with-firewall

**Comment by v00v** [comment]
Thank you for releasing v4.0.0-stable. But I think in the future its better to do another RC version instead of incomplete stable version. Even if documentation is not complete. Don't remove the features, instead do another RC version. Then release stable once everything including documentation is complete. When I seen v4.0.0 I got excited, until I seen features been removed and version is incomplete. Will wait for v4.1 now ehh. All phalcon documentation should be complete for the stable version before it is released. This is one of the things I like about phalcon, its most complete documentation. So again, thank you but this is kind of weird.
