### ISSUE TITLE
[BUG]:Route Delimiter doesn't reset

### ISSUE THREAD

**Issue by ruudboon** [phalcon/cphalcon#14680]
Running the following test will result in a failed test.

```php
<?php 
use Phalcon\Cli\Router\Route;

$route = new Route("test");

//Default delimiter
$I->assertEquals(" ", $route::DEFAULT_DELIMITER);
$I->assertEquals(" ", $route->getDelimiter());

$route = new Route("test");
$route->delimiter("-");
$I->assertEquals(" ", $route::DEFAULT_DELIMITER);
$I->assertEquals("-", $route->getDelimiter());

$route = new Route("test");
$I->assertEquals(" ", $route::DEFAULT_DELIMITER);

//Fails "-" getDelimiter gives "-"
$I->assertEquals(" ", $route->getDelimiter());
```

Expecting that getDelimiter gives " " back on a new instance.

**Comment by niden** [comment]
This is the nature of the static methods and properties. They stay in memory and you cannot know when they will be destroyed and when. 

I checked the code and wrote some more tests. If you try to run the `Router\Route` tests on their own they will fail because somewhere before that there is a call to `Router::delimiter()` that sets the delimiter and because it is static it stays in memory.

I made several changes to the tests to ensure that the state is reset before we run the test itself and restored when it is completed.

This really is not a bug, it is the usual problem of having static properties and methods - hence one more reason why I hate using them.

The new router that we will introduce when deploying the ADR patter will no longer use static methods. Also we could refactor the router/route to no longer use static methods and properties which will solve this issue also.
