### ISSUE TITLE
[BUG]: Model findFirst() and UUID

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/cphalcon#14730]
**Describe the bug**
In documentation is written:
```php
// Find record with id = 3
$robot = Robots::findFirst(3);
```
it works but only if ID is type of Integer, if ID is UUID that does not work.

**Details**
 - Phalcon version: 4.0.0 (3.4.1 also)
 - PHP Version: 7.2
 - Operating System: Debian
 - Installation type: Compiling from source in Docker
 - Server: Nginx
 - Other related info (Database, table schema): MySQL 5.5

**Comment by niden** [comment]
Can you explain a bit what you mean by _if ID is UUID_ ? Are you talking about the type of the column in MySQL or are you using a string/varchar to store the UUID?

**Comment by zak-wojtek77** [comment]
Sometimes primary key may be char(36) for example "1c53079c-249e-0c63-af8d-52413bfa2a2b". This problem is because in Phalcon in this function:
Robots::findFirst("1c53079c-249e-0c63-af8d-52413bfa2a2b");
"1c53079c-249e-0c63-af8d-52413bfa2a2b" is treat like "integer", in generated SQL is like that:
"select * from robot where id = 1c53079c-249e-0c63-af8d-52413bfa2a2b"
and correct should be:
"select * from robot where id = '1c53079c-249e-0c63-af8d-52413bfa2a2b'"

**Comment by tidytrax** [comment]
Can confirm on phalcon v4.0.2 + Php 7.4.1 Postgresql 12.1 

Table Primary key uuid type, does not have a sequential ID
column type uuid

```
 $test = VisionPosition::findFirst("5741bfd7-6870-40b7-adf6-cbacb515b9a9");
 var_dump($test->toArray());

```
**_The method broke on dash_** ( **-** )  and look's like transform on a column instead of searching on a primary_key, Column '5741bfd7' doesn't belong to any of the selected models (1)

**Comment by Jeckerson** [comment]
For now, you can write like that and it will work:

```
$uuid = '5741bfd7-6870-40b7-adf6-cbacb515b9a9';
$model = ModelWithStringPrimary::findFirst([
    'uuid = ?0',
    'bind' => [$uuid],
]);
```

**Comment by Jeckerson** [comment]
After internal team discussions with implementation of autodetect and just pass you mentioned. And also after benchmarks. We opt to leave it as is, because by design it wasn't never supposed to support that approach.

Use bind approach as mentioned above.

Docs updated and described this situation - https://docs.phalcon.io/4.0/en/db-models#findfirst

Closed.
