### ISSUE TITLE
[BUG]: Container is not passed to the autoloader registration method.

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/cphalcon#14787]
Hello there!

I was wondering if it is a bug or not? (Please see the link)

https://github.com/phalcon/cphalcon/blob/a48b31967a1ce27c10cbed61bee42e0c90addc86/phalcon/Cli/Console.zep#L118

Why is the current container not passed to the module's autoloader registration method?
I noticed that this is only relevant for the application Phalcon\Cli\Console.

**Details**
 - Phalcon version: ^4

**Comment by niden** [comment]
Bug for sure.

**Comment by TimurFlush** [comment]
Thank you, @niden. Maybe in this situation, make the container argument mandatory in the registerAutoloaders () method?

**Comment by niden** [comment]
@TimurFlush Unfortunately we cannot do that because it will break the interface and we are only allowed to do that during major versions i.e. v5. We can correct this however by just injecting the container in the place you mentioned.

If it not too much trouble can you send a PR for this? If not I will try and get that sorted out

**Comment by TimurFlush** [comment]
@niden , it's clear
Please check: https://github.com/phalcon/cphalcon/pull/14790

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14790 Thank you!
