### ISSUE TITLE
[BUG]: Volt cache for view fragments does not work in version 4.0.*

### ISSUE THREAD

**Issue by brucelin** [phalcon/cphalcon#14907]
Volt cache for view fragments does not work in version 4.0.*

When i try to cache the view fragments
```php
{% cache 'sidebar' 3600 %}
    <!-- ... -->
{% endcache %}
```
It throw the error
```php
Phalcon\Di\Exception : Service 'viewCache' wasn't found in the dependency injection container
```

Then I registered the `viewCache`  service in the Di container with a redis adapter.  But it throw the error
```php
Uncaught Error: Call to undefined method Phalcon\Cache\Adapter\Redis::start()
```

Did I miss some config or this functionality of volt cache has been removed in version 4.0.* ?

**Comment by Jeckerson** [comment]
Show how do you declare `viewCache` service, please.

**Comment by niden** [comment]
@brucelin You are correct. the `viewCache` has been removed from v4 because the cache service was incompatible with the old cache/viewCache.

Actually you found an area where we missed removing the service so thanks for that - it will be sorted out shortly.

You can use services such as varnish, cloudflare etc. to cache pages as an alternative. For fragments you can always use the `render()` from the `Simple` view or you can use the new `toString()` method from the `View`.

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/14914

**Comment by mahen3d** [comment]
"You can use services such as varnish, cloudflare etc. to cache pages as an alternative." this is very bad solution, i too have the same issue, how can you just remove cache from the templating service and say to use "cloudflare" ... :(
