### ISSUE TITLE
volt - conflict of variable name and service name

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/cphalcon#15047]
If I have serwis name "xxx" and I declare in view variable "xxx" in *.volt when I write

```
{{ xxx }}
```
in variable "xxx" will be service "xxx" not variable.

Is it possible to give any prefix for every service inject to volt?

Or is it possible to change order that if is conflict then in volt exists a variable not a service.

**Comment by niden** [comment]
We cannot change the name right now (of services etc.) so there will always be a conflict between a service and a variable with the same name. 

Potential solutions:
Instead of using the `FactoryDefault` DI, you can set your own, and prefix the services with say `service*`. That however will not work for say `modelsMetadata` or the `db` service because those names are required to be as they are.

Use different variable names - prefixed with whatever you want say `viewVar*`

I am not sure that changing the order will work because we will need to figure out what property (in volt) is a service or not and it will be difficult.

**Comment by zak-wojtek77** [comment]
Here
https://github.com/phalcon/cphalcon/blob/master/phalcon/Mvc/View/Engine/Volt/Compiler.zep
in line 129
```php
if typeof this->container == "object" && this->container->has(variable) {
```
can be changed order.
