### ISSUE TITLE
[NFR]: if not body to maintain zephir why not merge cphalcon7?

### ISSUE THREAD

**Issue by astinx** [phalcon/cphalcon#15166]
I noticed nobody maintain zephir this project, and maybe in the future phalcon will write in PHP, it means phalcon advantages will lose, and I found the other derivative of phalcon insist use clang develop phalcon and already supported php8, it's [cphalcon7 ](https://github.com/dreamsxin/cphalcon7) why not merge cphalcon7 to phalcon, keep phalcon advantages. 

cphalcon7 fixed many bugs from phalcon , and it supports more functions like WebSocket, etc.

I think phalcon the best way is back to the original. Use c to develop it.

**Comment by mustafa519** [comment]
Sounds exciting and i agree with him.

> it means phalcon's advantages will lose

Already, there are many frameworks which are already have most of benefits, except the good performance.

**Comment by Jeckerson** [comment]
> if not body to maintain zephir why not merge cphalcon7?

Because this is one-person-project, which does not have anything to do with `phalcon/cphalcon`.

> I think phalcon the best way is back to the original. Use c to develop it.

Here is some small retrospective:
1. Original developer of phalcon, wrote it in C.
2. The main idea to do that was to improve bad performance of PHP5 and at that time it was huge success. 
3. Then appeared Zephir with perspective that people will come and start to contribute. 
4. PHP core developers released PHP7 with finally good performance
5. Contributors quantity of Zephir didn't growed up
6. Now, as phalcon is completely in Zephir and last active developer (Serghei) quit.

So, your suggestion is make reverse evolution?

The niche of Phalcon was during specific time for specific projects. That time is passing due less and less difference between native PHP and another implementations, meanwhile support of specific language (Zephir) every year is harder. The difference between calling function inside PHP or inside C is miserable. Put your code inside memory - native PHP already gives you this possibility via opache and preload.

If we (phalcon team) wanted to RIP the project, we would do it now. But we want to accept new challenges and make as fast as possible the new version of framework with PHP native. Try to grow from local niche framework, to something bigger!

P.S. And if you review the retrospective above, you could understand that main goal always was (and still is) to call attention for community to help. And nowadays reality dictates that new coming developers, from 1 month courses, barely PHP (or even JS/CSS) knows... And you want all it again in C :)

**Comment by Fenikkusu** [comment]
I'm probably speaking for the minority here, but I personally love Zephir. I've several active projects that have been written in Zephir along side Phalcon. I'm willing to do what I can to keep Zephir alive. I know PHP, and I can learn C if I need to.

That aside, What I would like to see is more improvement for a conversion from PHP to Zephir. I think this would give the best of both worlds. Sure, Phalcon 5 can be written in PHP, but I'd like to be able to convert it to Zephir and in doing so, compile it into C if I want to. This to me seems the best of both worlds. Food for Thought.

**Comment by Jeckerson** [comment]
Also, consider to not forget that phalcon 4 is supported for versions PHP 7.2, 7.3 and 7.4 - which is 2+ years of support from our side.

**Comment by corentin-begne** [comment]
Really ...
Phalcon is not only used for the fast functions call but also to don't need to include a lot a files each times ... 
So bad, I would like to contribute to Zephir dev but I don't know how doing it, give some tutorials, tell us what to do.
If this framework will be written in php I think I won't use it anymore :(

**Comment by Jeckerson** [comment]
Closing, feel free to continue inside Discussion section - https://github.com/phalcon/cphalcon/discussions by opening new topic.
