### ISSUE TITLE
[BUG]Function Redis::setTimeout() is deprecated

### ISSUE THREAD

**Issue by HZMarico** [phalcon/cphalcon#15229]
Fixed By Commit : https://github.com/phalcon/cphalcon/commit/18d3f8b5e5a345b34ccb1bd654778b791e0ae734

When I download v3.4.5-releases With https://codeload.github.com/phalcon/cphalcon/tar.gz/v3.4.5

In releases, is still use `setTimeout` function

Please tar the newest  v3.4.5-releases

**Comment by Jeckerson** [comment]
Hello!

`v3.4.5` was released in 30th of October - https://github.com/phalcon/cphalcon/releases/tag/v3.4.5
Meanwhile fix commit was made at the day after, in 31th of October.

Phalcon `v3` is deprecated more then year ago and if you still need working with current fix `v3` you can always compile from source. So instead of downloading the release, clone `v3.4.x` branch and compile it - https://github.com/phalcon/cphalcon/tree/3.4.x
