### ISSUE TITLE
The Future of Phalcon

### ISSUE THREAD

**Issue by v00v** [phalcon/cphalcon#15233]
About Blog Post @ https://blog.phalcon.io/post/the-future-of-phalcon

"The team decided to switch to native PHP for Phalcon 5. We will try to support Phalcon 4 as much as possible and try to release Phalcon 4.1. We will use our funds to fix some critical Zephir issues that are blocking Phalcon."

I think more discussion on this subject should be done by all coders/users invovled in Phalcon. Maybe put it to the vote? This would be more fair! Also, I agree with what some other users said. You should try and raise enought money to hire dedicated coders, instead of doing something like switching to native PHP. I'm sure by now many companies use Phalcon for there projects, who will be more than happy to donate or raise needed funds.

**Comment by Jeckerson** [comment]
There are some ideas that we (team) are picking and validating, nothing specific can't be tell atm. Stay tuned...

**Comment by niden** [comment]
Answers to your issue from my perspective

> Its better to find coders interested maintaining Zephir/cPhalcon or even rewriting, but still continue keeping it as a php module. 

We have been trying to find people that know C for more than 3 years. We offered money for tasks etc. Nobody could, wanted to or was interested in contributing.

> Coding Zephir to maintain Phalcon was a wrong move in the first place. 

Zephir was built to help with contributions. We did have some throughout the history of Phalcon which we would have not had in the first place. At least Zephir helped a bit.

> You should of just stick to c-lang, because there is many coders who can code in "c". 

If you know any, point them here, maybe they would want to keep the work on cphalcon. Personally I gave up trying to find people. If people do not want to contribute it is their choice.

> But few to none know or care to code in Zephir. You can even code it in another popular language such as Go or Rust for example. 

Zephir is just a translating language. It converts its PHP/JS like syntax to C. Nothing more. Changing Zephir to Rust/Go or whatever is rewriting Zephir. You still need to know C to "convert" the code.

> Please reconsider coding Phalcon in native PHP. Because I for one, would just stop using it! If I wanted to use native PHP I would use Laravel or just code my own framework. Please do not destory cphalcon as a php module! Thank you!

Open source project. People like it, people do not. People choose to use it, people do not. More importantly, people choose to contribute to it and people do not. 

> I think more discussion on this subject should be done by all coders/users invovled in Phalcon. Maybe put it to the vote? 

You are more than welcome to initiate any discussion you want, even votes etc. Bare in mind that you will have to bare the results of that vote i.e. if people want to keep Phalcon as is (as a C extension) then be prepared to maintain it.

> This would be more fair! 

Fairness has nothing to do in open source. People contribute as much or as little as they want. And since end users receive something for free, if they want something more, they can do so themselves.

> Also, I agree with what some other users said. You should try and raise enought money to hire dedicated coders, instead of doing something like switching to native PHP. I'm sure by now many companies use Phalcon for there projects, who will be more than happy to donate or raise needed funds.

We have funds. We have not spend money in years (apart from this summer with Covid). We have been asking desperately for help and even contacted people from Zend. Nothing happened.

Anyhow, I do see this as being a moot point of discussion. If people want to keep cphalcon alive by all means, go for it.

**Comment by v00v** [comment]
Have you tried a place like Hacker News (https://news.ycombinator.com/) ? There is many companies and skilled people there that I'm sure would be willing to chip in one way or another. But very suprised that you could not find anyone even for money. Perhaps no one wants to use Phalcon than!? But in that case converting it to native PHP would not help at all. Mostly everyone uses native php Laravel.

But if you do convert phalcon into native PHP. Would you still have all the same features as 4.1? Or ability for people to create there projects how they want, like now? Custom placement of folders/files for example. If the answer is NO, than I think phalcon is dead. This sucks, because I coded few projects in phalcon and now I have to switch to another framework.

**Comment by Jeckerson** [comment]
@v00v Phalcon 5 (in PHP) will be almost identical as Phalcon 5, in terms of interfaces and functionality. One big change will be installation process, it will be installed via composer.

**Comment by v00v** [comment]
@Jeckerson, Okay this sounds good! But it can be installed manually without using composer right? I do not use or like compser :-)

**Comment by Jeckerson** [comment]
@v00v yes, as most of projects that are compatible with composer, might be copied directly as folder and used via includes as far as you wish.

**Comment by v00v** [comment]
@Jeckerson if this is the case. Than I think Phalcon 5, will be great! Can't wait! My most biggest concern was phalcon loosing features. The second, is the ability to customize my project the way I want, like now with v4.1 with folders/files for example. If you say it will be identical, it gives me a peace of mind! Thank you!

**Comment by v00v** [comment]
I must say that I completely missunderstood phalcon conversion to native PHP. My thought was that it would dramaticly change phalcon or the way we enjoy coding in it now. Flexibility and features provided in 4.1 is why I chose phalcon for all my projects for many years. I would hate learning another framework. Thank you for your replies @Jeckerson and @niden
