### ISSUE TITLE
[NFR] [Volt] escape_url is missing

### ISSUE THREAD

**Issue by oh-ren** [phalcon/cphalcon#1533]
It seems in Volt we can escape everything Phalcon\Escaper offers, except for escapeUrl? This should be added?

Btw; wouldn't it be more elegant to use the Twig way of <code>...|escape(TYPE)</code>? (e.g. <code>...|escape('js')</code>
(And still use <code>'html'</code> as default of course.)

This way of calling could easily be added, and exist next the current built-in filters?

(Of course, as an user, I can also overwrite the built-in escape function..)
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
