### ISSUE TITLE
[BUG]: Mode::find() not casting numeric and float ->toArray()

### ISSUE THREAD

**Issue by tidytrax** [phalcon/cphalcon#15361]
Phalcon 4.1.0 / PHP 7.4.16 / PgSql 12 / Ubuntu 20.04

When I use find and call toArray the numeric and float fields are not casting, bool,string and int are fine,
also on findFirst is working. 

To work i have to do a foreach and create a new array, and each row calling toArray();

I did try with and without modelsMetadata.

I have try both configurations

```
phalcon.db.force_casting
phalcon.orm.cast_on_hydrate
```

```
 Model::setup([
          'forceCasting' => true,
          'castOnHydrate' => true
      ]);

```

Does not cast!

```
$objects = Model:find();
$object->toArray() // not casting numeric and float
```

Works if  you loop or call by a key.
`$object[0]->toArray();
` 

string,bool and int are ok.

**Comment by Jeckerson** [comment]
Hello

Could you please give examples of data: actual and expected?

**Comment by tidytrax** [comment]
using Model::find()->toArray() each row return 

```
status: (integer) 1 
updated_at: (string) "2021-04-02 03:09:03"
created_at: (string) "2021-04-02 03:09:03"
lat(string) "7588176"
lon(string) "295247"
position: (string) "0"
v: (string) "-0.4085732221"
h: (string) "-0.004871870497"

```

Using Model::findFirst()->toArray()
```
status: (integer) 1 
updated_at: (string) "02-04-2021 3:09:03"
created_at: (string) "02-04-2021 3:09:03"
lat(float) 0 
position: (float) 0 
position: (float) 1 
v(float) -0.25721408870034 
h: (float) -0.18646341038777 
```

**Comment by tidytrax** [comment]
Same on PHP 8!

**Comment by niden** [comment]
This has been resolved in v5 https://github.com/phalcon/cphalcon/pull/15764

The Mysql adapter will use by default:

`\PDO::ATTR_EMULATE_PREPARES]  = false` and 
`\PDO::ATTR_STRINGIFY_FETCHES]  = false`

This speeds things up just a bit (emulate prepares) but also allows numbers to return as numbers in resultsets. This however does not affect decimal fields, since the precision has to be maintained when the data comes back.

@tidytrax Thanks for reporting this.
