### ISSUE TITLE
[BUG]: Can't setParams to dispatcher beforeExecuteRoute

### ISSUE THREAD

**Issue by crewsycrews** [phalcon/cphalcon#15603]
### **Describe the bug**
We want to `setParams()` of the dispatcher on `beforeExecuteRoute` event but it have no effect on the method. 

### **Expected behavior**
An ability to `setParams()` on `beforeExecuteRoute` event.

```php
    /**
     * @param Event $event
     * @param Dispatcher $dispatcher
     * @throws ReflectionException
     */
    public function beforeExecuteRoute(Event $event, Dispatcher $dispatcher): void
    {
        $controllerName = $dispatcher->getControllerClass();
        $actionName = $dispatcher->getActiveMethod();
        try {
            $reflection = new ReflectionMethod($controllerName, $actionName);
        } catch (ReflectionException $e) {
            return;
        }

        $parameters = $this->instantiateParams($reflection, $dispatcher->getParams());
        // next line has no effect here
        $dispatcher->setParams($parameters);
    }
```

### **Details**
 - Phalcon version: 4.0.5
 - PHP Version: 7.4.15
 - Operating System: Linux
 - Installation type: installing via package manager
 - Zephir version (if any): Version 0.12.17-6724dbf
 - Server: Nginx

**Comment by BeMySlaveDarlin** [comment]
`beforeExecuteRoute` expects first argument to be instance of `Dispatcher`, not `Event`.

**Comment by crewsycrews** [comment]
Sorry, I've not mentioned that beforeExecuteRoute declared in ServiceProvider, not in the controller. Can you check this one more time, please?

**Comment by kirill-voronov** [comment]
[Documentation](https://docs.phalcon.io/4.0/en/dispatcher#events) says us:

_NOTE: Methods on event listeners accept an Phalcon\Events\Event object as their first parameter - methods in controllers do not._

And it is true, because ` 'dispatch:beforeExecuteRoute'` calls here
https://github.com/phalcon/cphalcon/blob/041a4e09ad65dd7f14fc5fd3c61d9d92980e31ed/phalcon/Dispatcher/AbstractDispatcher.zep#L401

and then eventsManager fires event here

https://github.com/phalcon/cphalcon/blob/041a4e09ad65dd7f14fc5fd3c61d9d92980e31ed/phalcon/Events/Manager.zep#L297
`let status = handler->{eventName}(event, source, data);`

so the firs argument will always be instance of `Event` in any type of events. 

**Anyway the order of arguments in plugin is not the topic!
The topic is that calling `$dispatcher->setParams` in `beforeExecuteRoute` callback **has no effect**. 

This happens because in line 335 of Dispatcher params are copied into local method variable  
https://github.com/phalcon/cphalcon/blob/041a4e09ad65dd7f14fc5fd3c61d9d92980e31ed/phalcon/Dispatcher/AbstractDispatcher.zep#L335
 and since then only that variable is used, so any further call of `$dispatcher->setParams` has no effect, including such call in `beforeExecuteRoute` callback, because `setParams` modifies `this->params` not local `params` variable.

**Comment by kirill-voronov** [comment]
@BeMySlaveDarlin @Jeckerson @niden

**Comment by niden** [comment]
>  ...
> and since then only that variable is used, so any further call of `$dispatcher->setParams` has no effect, including such call in `beforeExecuteRoute` callback, because `setParams` modifies `this->params` not local `params` variable.

But this is the `dispatch()` method which happens after everything is said and done no?

**Comment by BeMySlaveDarlin** [comment]
@niden Looks like events firing during `dispatch()` method run doesn't affects `params` attribute because it was assigned to local variable as @kirill-voronov mentioned.
Made minor fix in #15794

**Comment by BeMySlaveDarlin** [comment]
Case using in controller or dispatcher itself fires before dispatch loop abd works fine, but when using events managed way - it fires during dispatch loop and doesnt affects params

**Comment by niden** [comment]
Resolved in https://github.com/phalcon/cphalcon/pull/15794

**Comment by kirill-voronov** [comment]
Thanks y'all ❤️

**Comment by niden** [comment]
@kirill-voronov Thank you for finding this. The second PR has tests that confirm that this works as expected.

https://github.com/phalcon/cphalcon/pull/15795
