### ISSUE TITLE
[BUG]: Code typo in database adapter class

### ISSUE THREAD

**Issue by wurst-hans** [phalcon/cphalcon#15848]
Can anyone check, if the dollar sign in [this line of code](https://github.com/phalcon/cphalcon/blob/master/phalcon/Db/Adapter/AbstractAdapter.zep#L633) is correct there? (Last commit was on 1st of november)

**Comment by niden** [comment]
@wurst-hans that is correct.

There are certain reserved words in Zephir that also appear as method calls for PHP. `fetch` is one of them as well as `inline`. In order to call those methods, we need to prefix them with `$` so that Zephir understands that this is not its own internal `fetch` command but a method on an object.

If you recall we changed some things in the ACL because of that (`Component` used to be called `Resource` which is also a reserved word in Zephir).

**Comment by wurst-hans** [comment]
Thanks a lot for clarification. Can be closed.
