### ISSUE TITLE
[BUG]: Cannot add grant for wildcard component in ACL

### ISSUE THREAD

**Issue by wurst-hans** [phalcon/cphalcon#16232]
I'm still using Phalcon 4 on some projects and have to integrate ACL now.

Copy and paste the sample from [documentation](https://docs.phalcon.io/4.0/de-de/acl#querying) throws an error:

```
Phalcon\Acl\Exception: Access 'view' does not exist in component '*' in /var/www/my-project/app/Components/Acl.php:187
Stack trace:
#0 [internal function]: Phalcon\Acl\Adapter\Memory->allowOrDeny()
#1 /var/www/my-project/app/Components/Acl.php(187): Phalcon\Acl\Adapter\Memory->allow()
#2 /var/www/my-project/app/Components/Acl.php(39): App\Components\Acl->prepareAcl()
```

To overcome this, I've tried to add a wildcard component using

`$acl->addComponent('*', 'view');`

Which throws another error:

```
Phalcon\Acl\Exception: Component name cannot be '*' in phalcon/Acl/Component.zep:38
Stack trace:
#0 [internal function]: Phalcon\Acl\Component->__construct()
#1 /var/www/my-project/app/Components/Acl.php(184): Phalcon\Acl\Adapter\Memory->addComponent()
#2 /var/www/my-project/app/Components/Acl.php(39): App\Components\Acl->prepareAcl()
```

How to solve this?

**Comment by niden** [comment]
I take that back. 

Looking at the code there are a lot of areas where the component _must not_ be a '*' (wildcard) and you pointed out the `addComponent` method. 

I will have to correct the example in the documentation for this. Making such a change will definitely affect backwards compatibility and since this is the ACL i do not want to mess people's application access.

Later on in v6 I do have plans to simplify the ACL component and at that time we can add the wildcard for components if necessary.

**Comment by niden** [comment]
Addressed in https://github.com/phalcon/cphalcon/commit/8caf99ca816474e05fe6be522ea98c437e206908 and https://github.com/phalcon/docs/commit/e7244b6786c9971ddc9f22207d579ccf9f59e26e

Thank you @wurst-hans
