### ISSUE TITLE
[BUG]: The "setDefault" method does not work for forms of type "text" with name "value"

### ISSUE THREAD

**Issue by hostbox2** [phalcon/cphalcon#16382]
The "setDefault" method does not work for forms of type "text" with name "value".

Example Form initialize:
```php
class notificationsEditForm extends Form {

        public function initialize($entity = null) {
...
            $value = new Text('value', array(
                'maxlength' => '20'
            ));
            $value->setDefault('10');
            $value->addValidators(array(new Between(array(
                'minimum' => -999999999,
                'maximum' => 999999999,
                'message' => 'The field is filled incorrectly',
            ))));
            $this->add($value);
...
        }
    }
``` 

Example Form in controller:
```php
$notificationsEditForm = new \dashboard\notificationsEditForm();
``` 

Example Form in view:
```php
<?=$notificationsEditForm->render('value')?>
``` 

As a result, the form is displayed, but it has no default value (just a blank field).

IF you rename the form, for example, call the field "valuer" - the default value is inserted

**Details**
 - Phalcon 5.2.2
 - PHP Version: 8.1.20
 - Operating System: Ubuntu 22.04.2 LTS
 - Server: Nginx + Apache

**Comment by niden** [comment]
This is not a bug, it is how the forms were built. You cannot have an element with the name "value". 

This has been here since the v3 version maybe earlier (https://github.com/phalcon/cphalcon/blob/3.4.x/phalcon/forms/form.zep#L618C19-L618C19)

In order for the form to be able to get the values either from itself or the children elements, it needs to call some methods. In the case of elements `getDefault()` in the case of the form `getValue()`.

The `getValue()` method is called in the form to get the value for the relevant element. In there, it checks if there are certain places that the value can be stored. One is the Form object and another the Element object. It checks the properties as well as getters. In your case you name your field `value` and the `getValue()` method tries to check the getter i.e. `getValue()` and therefore calls itself ending up in a crash.

Since it is a reserved word, you get `null` back.

**Comment by niden** [comment]
I added a section in the docs

https://docs.phalcon.io/5.0/en/forms#reserved-names

Thank you for reporting this @hostbox2
