### ISSUE TITLE
[NFR]ModelView instead of Phalcon\Tag

### ISSUE THREAD

**Issue by tugrul** [phalcon/cphalcon#1703]
Phalcon\Tag is unnecessary feature. I prefer write tags without Phalcon\Tag everytime. There will be ModelView for every required html tags and be able to render view's dependency hierarchy. Also can bind data to fields and validate fields are very handy. Also same logics with same views are reusable or extendable and reusable anywhere. 
I'm going to share some use cases.

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

Refs: https://github.com/phalcon/cphalcon/issues/476, https://github.com/phalcon/cphalcon/issues/218
