### ISSUE TITLE
Volt Named Block End-Tags

### ISSUE THREAD

**Issue by moorereason** [phalcon/cphalcon#1744]
**Enhancement request:**

I'd like to be able to use named block end-tags when using inheritance in Volt.  Jinja supports it (http://jinja.pocoo.org/docs/templates/#named-block-end-tags).

**Example:**

```
{% block content %}
  {# content here #}
{% endblock content %}
```
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
