### ISSUE TITLE
[NFR] Allow aliasing in Loader

### ISSUE THREAD

**Issue by aleemb** [phalcon/cphalcon#1777]
Laravel and a few other frameworks allow aliasing classes. This is particularly useful for example when in my view I would rather use:

```
Form::foo()
```

as opposed to:

```
Vendor\HTML\Form::foo()
```

The latter syntax quickly becomes cumbersome when uses liberally. Right now I have resorted to putting my `HTML` classes in the root namespace but that's not ideal. The other work around is to add `use Vendor\HTML\Form` on the top of every view which is also not ideal.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
