### ISSUE TITLE
[NFR] Support RETURNING in models and PHQL

### ISSUE THREAD

**Issue by zbitname** [phalcon/cphalcon#1816]
Example:

``` sql
INSERT INTO table(field1, field2) VALUES(:value1, :value2) RETURNING id, field3;
```

instead of this

``` sql
:uuid = SELECT uuid_generate_v4();
INSERT INTO table(id, field1, field2) VALUES(:uuid, :value1, :value2);
:field3 = SELECT field3 FROM table WHERE id=:uuid;
```

It's very usefull feature for <i>uuid</i> data type, or other autogenerated string types.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
