### ISSUE TITLE
Volt Compiler - minify option

### ISSUE THREAD

**Issue by naNuke** [phalcon/cphalcon#1924]
Hello, I would like to request a feature for volt engine to minify it's compiled php source, strip out comments, new lines, tabs and multiple spaces into just one space, etc...

Possible issue with this might be [PRE](http://www.w3schools.com/tags/tag_pre.asp) tags.

Thanks!
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
