### ISSUE TITLE
[NFR] Merge Component, Module and Plugin

### ISSUE THREAD

**Issue by boast** [phalcon/cphalcon#1936]
Hello there!

`\Phalcon\Mvc\User\Component`, `\Phalcon\Mvc\User\Module` and `\Phalcon\Mvc\User\Plugin` are literally the same classes: they extend `\Phalcon\DI\Injectable` and thats it. Moreover, I think their namespace is poorly chosen (Why in Mvc, isn't it a Service? Who is the User?).

I propose to either:
- drop them in favour of `\Phalcon\DI\Injectable`, or
- add functionality and separate them clearly, and move them into a better suited namespace.

Or maybe I am wrong and there is a brilliant idea behind this :) 

See als: #308 which is over a year old and it seems, this idea has been dropped?
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
