### ISSUE TITLE
[BUG] missing custom header in output from request->getHeaders()

### ISSUE THREAD

**Issue by zdenekgebauer** [phalcon/cphalcon#2294]
Array returned from native php functions getallheaders() and apache_request_headers() contains item "Authorization" (header injected via angular), but output from $this->request->getHeaders() don't.
Expected result: request->getHeaders() should return all available headers

Tested on: phalcon 1.3.0, Apache/2.4.4 (Win32) PHP/5.4.16
##

**Comment by dragosdm** [comment]
if your header is: X-SOMETHIN-ELSE you can get it with $app->request->getHeader('HTTP_X_SOMETHING_ELSE');

**Comment by santosh-zenith** [comment]
me too same problem with Phalcon 1.3.2

**Comment by w3yyb** [comment]
phalcon 2.0.0  too

**Comment by nask0** [comment]
Phalcon 2.0.10 is affected too. 
IMHO Request->getHeaders() should simply return getallheaders()

Any good reason for header checks in Request->getHeader() ?

**Comment by micheleangioni** [comment]
I confirm that Phalcon 2.0.10 is affected as well!
Imho this needs a quick fix!

**Comment by rahuldroy** [comment]
The implementation seems to be correct. The implementation also happens to be very similart to Zend Framework's implementation as well. 

The Issue seems to be that the users are using PHP as a CGI/FastCGI. We will need to do some .htaccess magic in order for it to appear in request->getHeaders();

Something like this maybe? - 
```
# On .htaccess
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1] # Authorization will now be returned by getHeaders()
```

The reason why getAllHeaders() works is because it actually calls an Apache function to get all the headers. One thing we need to take into account is that not everyone uses Apache as their server! While I haven't tried this, I would imagine this would be an issue in say NGINX or even IIS.

I guess there are two ways we can go about addressing this "bug" - 

1. Check if apache_request_headers() returns anything, then use that otherwise use ​_SERVER with keys starting with HTTP_​ (current implementation).
2. Update the documentation stating that if you want to capture custom headers, you will need to update .htaccess

I prefer the second option because of the reasons stated above.

References - 
Zend implementation - https://github.com/zendframework/zend-xmlrpc/blob/master/src/Request/Http.php#L81

Phalcon implementation - https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/http/request.zep#L791

**Comment by rahuldroy** [comment]
@andresgutierrez / @sergeyklay, 

Are we going to do some changes for this based on previous comments?

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by rahuldroy** [comment]
@sergeyklay, let me know if I can help in any way
