### ISSUE TITLE
PHP gets segfaulted when is running phalcon.so in secondary php-fpm pool

### ISSUE THREAD

**Issue by rbolforski** [phalcon/cphalcon#2403]
Hello,

When I add extension to my php.ini file:

root@haze ~ # cat /etc/php5/fpm/conf.d/30-phalcon.ini
; configuration for php phalcon module
; priority=30
extension=phalcon.so
root@haze ~ #

It's working fine, but I won't have it available globally so I've created secondary pool in fpm, then in it's configuration placed:

php_admin_value[extension]=phalcon.so

The library is being loaded however after serving few requests it gets killed:

[06-May-2014 19:48:59] WARNING: [pool phalcon] child 3442 exited on signal 11 (SIGSEGV - core dumped) after 13.347036 seconds from start

GDB output from core:

http://pastebin.com/8yegt9vp

Thanks & Best Regards

**Comment by cyhex** [comment]
I can confirm the issue, creating new php-fpm pool with phalcon loaded using php_admin_value[extension]=phalcon.so throws every second request SIGSEGV
Using latest 2.0 branch of phalcon under ubuntu 14.04 with PHP 5.5.9-1ubuntu4.5

**Comment by andresgutierrez** [comment]
Could you please try again using latest Phalcon 2?

**Comment by cyhex** [comment]
tested with latest 2.0 branch, the problem is still there. Once in a while i get 
`Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1898812445 bytes) in /home/gx/sites/shpc/shpc/app/libs/plugins/Acl.php on line 20` 
but most of the time it just dies with 104: Connection reset by peer.

If phalcon.so is loaded with conf.d there problem is no longer there, same with php build in server.
