### ISSUE TITLE
Implement Iterator (Traversable) in result of - Phalcon\Mvc\Collection::find

### ISSUE THREAD

**Issue by ghost** [phalcon/cphalcon#2771]
Is there any reason why it should not be implemented ?

Would be nice to see that.
##

**Comment by szytko** [comment]
:+1: 
In my opinion the current solution in find method is slightly inefficient because of iterator_to_array use

[https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/collection.zep#L431](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/collection.zep#L431)
```
let collections = [];
for document in iterator_to_array(documentsCursor) {

	/**
	 * Assign the values to the base object
	 */
	let collections[] = static::cloneResult(base, document);
}
```

I have rewritten find method to return cursor, which in turn is wrapped by proxy class that implements Iterator

```
// \Phalcon\Mvc\Collection
protected static function _getResultCursor($params, $collection, $connection)
{
    $source = $collection->getSource();
    if (empty($source)) {
        throw new \Exception('Method getSource() returns empty string');
    }

    $mongoCollection = $connection->selectCollection($source);

    if (!is_object($mongoCollection)) {
        throw new \Exception('Couldn\'t select mongo collection');
    }

    /**
     * Convert the string to an array
     */
    if (!isset($params[0])) {
        if (!isset($params['conditions'])) {
            $conditions = [];
        } else {
            $conditions = $params['conditions'];
        }
    } else {
        $conditions = $params[0];
    }
    if (!is_array($conditions)) {
        throw new \Exception('Find parameters must be an array');
    }

    /**
     * Perform the find
     */
    if (isset($params['fields'])) {
        $documentsCursor = $mongoCollection->find($conditions, $params['fields']);
    } else {
        $documentsCursor = $mongoCollection->find($conditions);
    }

    /**
     * Check if a 'limit' clause was defined
     */
    if (isset($params['limit'])) {
        $documentsCursor->limit($params['limit']);
    }

    /**
     * Check if a 'sort' clause was defined
     */
    if (isset($params['sort'])) {
        $documentsCursor->sort($params['sort']);
    }

    /**
     * Check if a 'skip' clause was defined
     */
    if (isset($params['skip'])) {
        $documentsCursor->skip($params['skip']);
    }

    /**
     * If a group of specific fields are requested we use a Phalcon\Mvc\Collection\Document instead
     */
    if (isset($params['fields'])) {
        $documentsCursor->fields($params['fields']);
    }

    return $documentsCursor;
}

public static function find(array $parameters = null)
{
    $className = get_called_class();
    $collection = new $className;
    $cursor = static::_getResultCursor($parameters, $collection, $collection->getConnection());

    return new LazyLoadingCursor($cursor, $collection);
}
```

Proxy class
```
class LazyLoadingCursor implements \Iterator
{
    /**
     * @var \MongoCursor
     */
    protected $cursor;

    /**
     * @var \Phalcon\Mvc\Collection
     */
    protected $collectionInstance;

    /**
     * @param \MongoCursor $cursor
     * @param \Phalcon\Mvc\Collection $collectionClass
     */
    public function __construct(\MongoCursor $cursor, \Phalcon\Mvc\Collection $collectionClass)
    {
        $this->cursor = $cursor;
        $this->collectionInstance = $collectionClass;
    }

    public function current()
    {
        $collection = clone $this->collectionInstance;
        foreach ($this->cursor->current() as $k => $v) {
        	$collection->writeAttribute($k, $v);
        }

        return $collection;
    }

    public function next()
    {
        $this->cursor->next();
    }

    public function key()
    {
        return $this->cursor->key();
    }

    public function valid()
    {
        return $this->cursor->valid();
    }

    public function rewind()
    {
        $this->cursor->rewind();
    }
}
```

There are some benchmarks


| Test 500 records                             | Time usage | Memory usage |
|----------------------------------------------|------------|--------------|
| Phalcon\Collection::find                     | 4ms        | 14.25Mb      |
| Phalcon\Collection::find -> iterations             | 0ms        | 14.25Mb      |
| Phalcon\Collection::find with cursor         | 3ms        | 14.00Mb      |
| Phalcon\Collection::find with cursor -> iterations | 3ms        | 14.00Mb      |


| Test 1000 records                            | Time usage | Memory usage |
|----------------------------------------------|------------|--------------|
| Phalcon\Collection::find                     | 7ms        | 16.50Mb      |
| Phalcon\Collection::find -> iterations             | 0ms        | 16.50Mb      |
| Phalcon\Collection::find with cursor         | 2ms        | 16.00Mb      |
| Phalcon\Collection::find with cursor -> iterations | 5ms        | 16.00Mb      |


| Test 10000 records                           | Time usage | Memory usage |
|----------------------------------------------|------------|--------------|
| Phalcon\Collection::find                     | 121ms      | 48.50Mb      |
| Phalcon\Collection::find -> iterations             | 16ms       | 48.50Mb      |
| Phalcon\Collection::find with cursor         | 18ms       | 28.25Mb      |
| Phalcon\Collection::find with cursor -> iterations | 54ms       | 28.50Mb      |


| Test 100000 records                          | Time usage | Memory usage |
|----------------------------------------------|------------|--------------|
| Phalcon\Collection::find                     | 1.145s     | 381.00Mb     |
| Phalcon\Collection::find -> iterations             | 170ms      | 381.00Mb     |
| Phalcon\Collection::find with cursor         | 180ms      | 123.00Mb     |
| Phalcon\Collection::find with cursor -> iterations | 556ms      | 126.25Mb     |

**Comment by sergeyklay** [comment]
:+1:

**Comment by arius86** [comment]
Using cursor is way more efficient. :+1:  for @szytko
