### ISSUE TITLE
Is it possible to create new <%%> directives in Phalcon?

### ISSUE THREAD

**Issue by dschissler** [phalcon/cphalcon#3095]
I want to create a translation directive for Volt because I think that the syntax is a better fit then the helper function notation.

For example I find the first form to be more appropriate than the second form.  

```
<% t "Singular Form" "Plural Form" n %>

{{ t('Singular Form, 'Plural Form', n) }}
```

Its also a hell of a lot easier to parse the first form for gettext strings than the second form.

**Comment by dugwood** [comment]
Second syntax is easier to read: commas delimit parameters. For developers knowing PHP, it's quite the same syntax in PHP language, so that makes a lot of sense.

But if you really want to use your first syntax, you'll have to update the core code of Volt:
https://github.com/phalcon/cphalcon/blob/2.0.0/ext/phalcon/mvc/view/engine/volt/base.c#L58
