### ISSUE TITLE
phalcon Encrypt Class how to set PKCS5Padding

### ISSUE THREAD

**Issue by dcboy** [phalcon/cphalcon#3211]
hi
i want to use DES encrypt decrypt the mode is ECB but how to setPadding for `PKCS5` padding?

**Comment by 7thcubic** [comment]
http://us3.php.net/manual/en/ref.mcrypt.php#69782

The php method to do it. 

Will look into making a commit for this. Not sure if it will get pulled though

**Comment by sergeyklay** [comment]
We don't support `PKCS5` encryption anymore. 

The `PKCS5` padding is identical to `PKCS7` padding, except that it has only been defined for block ciphers that use a 64-bit (8 byte) block size. In practice the two can be used interchangeably.

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started for [Incubator](https://github.com/phalcon/incubator), I'd love that.
