### ISSUE TITLE
[Phalcon 2] Phalcon\Db\Adapter doesn't fill OnUpdate and OnDelete actions in method describeReferences()

### ISSUE THREAD

**Issue by RemyJeancolas** [phalcon/cphalcon#3219]
Hello,

It seems that for all the objects returned by a call to describeReferences(), the methods getOnUpdate() and getOnDelete() return null, for example :

``` php
$references = $connection->describeReferences('my_robots_parts');
foreach ($references as $reference) {
    echo $reference->getOnUpdate(); // returns null
    echo $reference->getOnDelete(); // returns null
}
```

Thanks for your return.

**Comment by olivier-monaco** [comment]
https://github.com/phalcon/cphalcon/blob/2.0.0/phalcon/db/adapter.zep#L1069

Definition array not populated with onUpdate/onDelete. In fact, there seems to be nothing about them in method describeReferences of dialects.

**Comment by 7thcubic** [comment]
i found the sql to fix that. attempting to write a patch for it.

//var sql = "select a.TABLE_NAME,a.COLUMN_NAME,a.CONSTRAINT_NAME,a.REFERENCED_TABLE_SCHEMA,a.REFERENCED_TABLE_NAME,a.REFERENCED_COLUMN_NAME,b.update_rule,b.delete_rule from information_schema.KEY_COLUMN_USAGE as a join information_schema.REFERENTIAL_CONSTRAINTS as b on a.CONSTRAINT_NAME = b.CONSTRAINT_NAME and a.CONSTRAINT_SCHEMA = b.constraint_schema where a.REFERENCED_TABLE_NAME is not null and ";
		//if schema {
			//let sql .= "a.CONSTRAINT_SCHEMA = '" . schema . "' AND a.TABLE_NAME = '" . table . "'";
		//} else {
			let sql .= "a.TABLE_NAME = '" . table . "'";
		//}
		//return sql;

Ideally that will give mysql adapter the 6th and 7th field providing the actions. just need to fix it > >

**Comment by 7thcubic** [comment]
fixed. well it only works in mysql though and i kinda had to alter adapter to do it. its not pretty at all for those who arent using mysql. =/

since i dont use other db's i cant fix it

**Comment by RemyJeancolas** [comment]
@olivier-Monaco: in fact, I saw that it was not implemented, the question was about the possibility of precisely implement this functionality.
Like @7thcubic I use mysql, and I implemented a fix similar to its own that solves the problem (for mysql only).
I wonder if the act of pushing this fix respects the Phalcon's "philosophy", knowing that it will make a difference for people using other backends. But since this feature is currently not implemented, it improves the mysql backend without impacting the functioning of other backends, free to those who use them to implement a similar fix if they need it .
What do you think about it?

**Comment by 7thcubic** [comment]
Well my fixed altered adapter. But i did a check at least. So hopefully it wouldnt break the other adapters. 

Since it returns a longer array. And by default it will be null. Maybe i shld do a check. If on update or on delete is null do not add them. 

The thing is there is also another issue with the current describe reference. 

Suppose i have purchasing and sales on a different schema. And if both had invoice table and both referenced a common hr schema for the user table. 

The current describe doesnt cater for same constrict keys names but different schema. It simply overwrite them. My fix for it is to return the schema name as part of the array key. So the names are automatically stored as schema.table. Makes sense?

**Comment by dschissler** [comment]
@Jurigag Is this still relevant?  Can you make sense of it?

**Comment by sergeysviridenko** [comment]
For MySQL `describeReferences` method works fine. @rianorie has fixed this bug. I guess this issue can be closed.
