### ISSUE TITLE
Phalcon pagination bug

### ISSUE THREAD

**Issue by softdream** [phalcon/cphalcon#3233]
Hi i think that i was found a bug in pagination. 

When i have builded "little" complicated filter and find that using Model:find($params), the pagination object works fine until i try to load unexist page for example ( in the request is result: 2 pages ) and when i try to load page 3 the paginator return me a first result ( page 1 ) instead of null or empty result.

**Comment by 7thcubic** [comment]
I dont think its a bug. Its more of a safety feature. 

Because any user of your web can edit the url and force the page to go out of bounds. So it makes sense to fall back to page 1. Alot of existing web/backend does this. Especially shopping carts and such. 

Besides the query isnt empty. And it could be argued that due to a wrong url/post a user might actually think it is empty rather than retrieving what ever it can. 

Unless you intend for the user to view a empty page of the page count is invalid.

**Comment by softdream** [comment]
I think that is, due to that is work like charm when i use simple filtration ( not so much params ).

**Comment by Green-Cat** [comment]
Not a bug.
