### ISSUE TITLE
[NFR] Implement standalone validators

### ISSUE THREAD

**Issue by alvassin** [phalcon/cphalcon#491]
In phalcon framework there are many nice and wonderful solutions.. except validators :)

We have 2 validator classes for email for MVC and for forms validation.. but there could be one, that could also be used as standalone element, it would be much easier to understand how it works and to build complex own applications.

Current solution is not flexible enough (from my point of view).
Please have a look at Zend Validators (i don't like this framework for it's giant code amount and because they don't use ready solutions.. but.. it's much more flexible):

http://framework.zend.com/manual/1.12/en/zend.validate.set.html

Standalone elements could be used by MVC or Forms classes.. and this could work...
##

**Comment by Jurigag** [comment]
Well in phalcon 3 pretty much there is already `Phalcon\Validation` for using in both models and forms. In phalcon 3.1 `Phalcon\Mvc\Validator`(which is used only in collections) will be marked as deprecated since collection will have option to use `Phalcon\Validation`, in 4 removed. About standalone there is still need for Validation class, but i like this better.
