### ISSUE TITLE
[NFR] Phalcon\Loader. Allow to set for one namespace multiply dirs (array of dirs)

### ISSUE THREAD

**Issue by ephrin** [phalcon/cphalcon#691]
Project on phalcon use composer and grab all its ClassLoader data (include paths, class map, namespaces). Then making unregister to composer loader and register ints own Phalcon\Loader. (for performance). But composer unlike phalcon loader have the feature to search for one namespace in multiply dirs. So in Phalcon we have no way to do so and some parts of libs (custom namespace dirs) are out of Phalcon\Loader sight.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

**Comment by ephrin** [comment]
You are welcome. As a reporter I don't have any requirement for the improvement. So let's wait for reaction for couple of days and then close if no one need this.
