### ISSUE TITLE
Possible bug: SQL injection in tableExists(), viewExists()

### ISSUE THREAD

**Issue by ghost** [phalcon/cphalcon#748]
Because table/column/index/etc names are never escaped (and the documentation does not whether it is up to the developer of framework to escape names), it is possible to inject an arbitrary SQL.

For example, for SQLite the following:

``` php
$dialect = new Phalcon\Db\Dialect\Sqlite();
echo $dialect->tableExists("test'; DROP TABLE test; SELECT * FROM sqlite_master WHERE '"), "\n";
```

produces

``` sql
SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END FROM sqlite_master WHERE type='table' AND tbl_name='test'; DROP TABLE test; SELECT * FROM sqlite_master WHERE ''
```

Whil I understand that these methods will almost never (hopefully) interact with untrusted data, it would be nice to make sure that there is no way for [Little Bobby Tables](http://xkcd.com/327/) out there.
##

**Comment by niden** [comment]
This method was never designed to be used in areas where code can be injected into the `tableExists` or `viewExists`. 

The only thing I can do right now is to use the `escape` method so that the schema and/or table names can be escaped.

The dialect is designed to return the SQL not execute it. It is up to the developer to make sure that the proper placeholders are used.

In 4.x we have plans to revisit the Db layer and offer additional checks for methods like the ones mentioned above.
