### ISSUE TITLE
[NFR] Forms\Element\Option

### ISSUE THREAD

**Issue by philippgerard** [phalcon/cphalcon#805]
Should offer the possibility to add option inputs, API similar to Select.
##

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. If there are bugs, we can follow up in a separate issue. I'll open it again if the need arises. 

I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything any at time, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
