### ISSUE TITLE
Missing headers from request->getHeader (like content-type)

### ISSUE THREAD

**Issue by RenaudParis** [phalcon/cphalcon#9934]
Hi,

I noticed that the "content-type" HTTP header is not returned by Phalcon when doing request->getHeader().

I had to go with my own home-made function to retrieve that header (that function parses $_SERVER and retrieves every "HTTP_*" key, plus the "CONTENT_TYPE" key).

Thank you,

**Comment by Atriedes** [comment]
try fetch with this `$this->request->getHeader("HTTP_CONTENT_TYPE")`

**Comment by RenaudParis** [comment]
Nope, no luck, empty string

**Comment by dreamsxin** [comment]
What version with PHP and Phalcon?

**Comment by RenaudParis** [comment]
Apache 2.4.9, PHP 5.5.12, and Phalcon 1.3.3
Everybody here at the office can reproduce the issue

**Comment by Atriedes** [comment]
could you please update phalcon version 1.3.5 and try my suggestion, I have experienced it before it solved when I uppdate my phalcon to latest version.

**Comment by RenaudParis** [comment]
You want my sysadmin to kill me, right? :) He spent weeks trying to properly setup and package all dependencies (Phalcon and others). I'm not sure he will like the idea of updating so soon.

But nevertheless I'll try on my local env and keep you posted!

Thanks for the tip!

**Comment by Atriedes** [comment]
I have experience it take a look at this : https://github.com/Atriedes/phalcon-restful-webservice/blob/master/app/Core/Security.php#L31

In header I set `X-API-KEY` but when I retrieved, it has to be `HTTP_X_API_KEY` also that code wont work on phalcon v1.3.3 or lower

**Comment by rifflock** [comment]
I was also having this issue, so I updated to Phalcon 1.3.5 and was able to get the Content-Type header by pulling it from `$request->getServer("CONTENT_TYPE");`

Is it planned to have the headers that are in `$_SERVER` available in the same way as the `$request->getHeaders()` method? If not it might be good to have a note in the documentation since both `Content-Type` and `Content-Length` are fairly commonly used. Or to just have methods to access them directly: `$request->getContentLength()` and `$request->getContentType()`? Would be very useful for simplicity header checks.

**Comment by RenaudParis** [comment]
I agree with @rifflock for the shortcut methods, it'd be pretty useful to have a method for each commonly used header

**Comment by andresgutierrez** [comment]
Could you please try again using Phalcon 2 or close this issue as 1.3.x is no longer supported
